<?php
/**
 * @package     universal
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>

<style>
	.login_loader {
	    position: fixed;
	    z-index: 9999999;
	    background: rgba(255, 255, 255, 0.5);
	    width: 100vw;
	    height: 100vh;
	    top: 0;
	    left: 0;
	    display: flex;
	    justify-content: center;
	    align-items: center;
	}

	.lds-facebook {
	  display: inline-block;
	  position: relative;
	  width: 64px;
	  height: 64px;
	}
	.lds-facebook div {
	  display: inline-block;
	  position: absolute;
	  left: 6px;
	  width: 13px;
	  background: #F2655D;
	  animation: lds-facebook 1.2s cubic-bezier(0, 0.5, 0.5, 1) infinite;
	}
	.lds-facebook div:nth-child(1) {
	  left: 6px;
	  animation-delay: -0.24s;
	}
	.lds-facebook div:nth-child(2) {
	  left: 26px;
	  animation-delay: -0.12s;
	}
	.lds-facebook div:nth-child(3) {
	  left: 45px;
	  animation-delay: 0;
	}
	@keyframes lds-facebook {
	  0% {
	    top: 6px;
	    height: 51px;
	  }
	  50%, 100% {
	    top: 19px;
	    height: 26px;
	  }
	}
</style>

<div class="account-login">
	<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="registered-users">
			<div class="auth-box">
				<h2 class="auth-title">Já tem cadastro?</h2>
			</div>
			<div class="content">
				<?php echo $this->getMessagesBlock()->toHtml() ?>
				<div class="email-container">
					<label for="email">E-mail</label>
		        	<div class="input-box">
		            	<input type="text" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" name="login[username]" id="email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" class="input-text validate-user required-entry" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
		        	</div>
		        	<span id="situacao"></span>
		        </div>
		        <div class="pass-container" id="pass-container">
					<label for="pass">Senha</label>
		        	<div class="input-box">
						<input type="password" name="login[password]" autocomplete="off" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
					</div>
					<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="esqueci_senha"><?php echo $this->__('Forgot Your Password?') ?></a>
				</div>
				<?php echo $this->getChildHtml('persistent.remember.me'); ?>
				<div class="clearfix">
					<button type="submit" class="btn ui-button auth-button btn-login"
						title="Login"
						name="send"
						id="send"
						/>
						<span>
							<span>
								Login
							</span>
						</span>
					</button>
						<hr />
						<?php echo $this->getChildHtml('inchoo_socialconnect_facebook_login_button'); ?>
					    <hr />
					<div class="register">
						<p>Voc&ecirc; &eacute; novo aqui?</p>
						<a href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"
							title="<?php echo $this->quoteEscape($this->__('Create an Account')) ?>"
							class="create-count-button">
							<?php echo $this->__('Cadastre-se agora!') ?>
						</a>
				</div>
				
				<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
			</div>
		</div>
		<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
			<input name="context" type="hidden" value="checkout" />
		<?php endif; ?>
	</form>
</div>
<script type="text/javascript">
//<![CDATA[
	if(!BASE_URL)
		var BASE_URL = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";

	var dataForm = new VarienForm('login-form', true);

	$('email').observe('keypress', bindLoginPost);
	$('email').observe('keypress', mascara);
	$('email').observe('blur', bindExists);
	$('pass').observe('keypress', bindLoginPost);

	function bindLoginPost(evt){
	 	if (evt.keyCode == Event.KEY_RETURN) {
	 		//evt.preventDefault();
	 	}
	}

	function mascara() {
		$('situacao').hide();
		value = this.value;
		if (!checkMail(value)){
			var er = new RegExp(/^[0-9\-\.\/]+/);
			if (er.test(value)) {
				value = value.replace(/\D/g,"");
				if (value.length >= 1 && value.length <= 11) {
					mascaraCPF(this);
				} else {
					mascaraCNPJ(this);
				}
			} else {
				value = this.value;
				value = value.replace(/[^a-zA-Z0-9_\-\.@]/gi,"");
				this.value = value;
			}
		}
	}

	function bindExists() {
		value = $('email').value;
		//$('send').writeAttribute('disabled',true);
		if (value.length > 3) {
		    if (checkMailDocument(value)) {
		   		var ok = false;
		    	var url = BASE_URL + 'onestic_checkout/customer/exists/';

		   		new Ajax.Request(url, {
		      		method: 'post',
		      		async: false,
		     		parameters: 'user=' + encodeURIComponent(value),
		       		onSuccess: function(transport) {
			       		var obj = response = eval('(' + transport.responseText + ')');
			        	if (obj.result === true) {
			          		$('pass-container').show();
			          		$('send').show();
			          		//$('send').writeAttribute('disabled',false);
			          		$('situacao').hide();
		           		} else {
							$('situacao').innerHTML = 'Email ou CPF/CNPJ não encontrado. Tente outro ou clique abaixo para se Cadastrar agora.';
							$('situacao').show();
							//$('send').hide();
		           		}
			        },
		          	onComplete: function() {
		          		//if ($('advice-validate-user-exist-email')) {
		          			//$('advice-validate-user-exist-email').remove();
		            	//}
		        	}
		      	});

		      	return ok;
		    } else {
		  		Validation.add('validate-user', 'Por favor, confira seus dados!', function(value) {
	    			return Validation.get('IsEmpty').test(value);
				});
		    }
		}
	}
//]]>
</script>
<script>
    'use strict';

    var regions = {
        AC: 485,
        AL: 486,
        AP: 487,
        AM: 488,
        BA: 489,
        CE: 490,
        DF: 511,
        ES: 491,
        GO: 492,
        MA: 493,
        MT: 494,
        MS: 495,
        MG: 496,
        PA: 497,
        PB: 498,
        PR: 499,
        PE: 500,
        PI: 501,
        RJ: 502,
        RN: 503,
        RS: 504,
        RO: 505,
        RR: 506,
        SC: 507,
        SP: 508,
        SE: 509,
        TO: 510
    };
</script>