<?php
/**
 * ShopInDev
 *
 * @category    ShopInDev
 * @package     ShopInDev_SuperXmlFeed
 * @copyright   Copyright (c) 2016 ShopInDev
 * @license     http://opensource.org/licenses/GPL-3.0 GNU General Public License (GPL)
 */
?>
 
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.22.2/codemirror.min.css">
<style>
.CodeMirror {
    position: relative;
    overflow: hidden;
    background: #fff;
    border: 1px solid #CCC;
    height: 400px;
    font-size: 14px;
}
</style>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.22.2/codemirror.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.22.2/mode/xml/xml.min.js"></script>
 