<div class="footer">
    <div class="menu-inferior">
        <div class="formas-pagamento">
            <h5>Formas de pagamento</h5>
            <ul class="selo-seguro">
                <li>
                    <img alt="visa" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/visa.png'); ?>"/>
                </li>
                <li class="itemRight">
                    <img alt="amex" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/amex.png'); ?>"/>
                </li>
                <li>
                    <img alt="mastercard" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/mastercard.png'); ?>"/>
                </li>
                <li class="itemRight">
                    <img alt="boleto" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/boleto.png'); ?>"/>
                </li>
                <li>
                    <img alt="elo" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/elo.png'); ?>"/>
                </li>
                <li>
                    <img alt="diners" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/diners.png'); ?>"/>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>

  <!-- MASCOTE NEWSLETTER -->
  <div class="footer-container">
            <div class="footer-session1">
                <div class="wrapper">
                    <div class="need-help-session">
                        <div class="content">
                        <img src="<?php echo $this->getSkinUrl('images/logo-mobile.png') ?>" class="logo-help-session" alt="Farmadelivery - A Melhor Farmácia Online do Brasil - (11) 4972-8188" itemprop="logo" width="273px" height="auto"/>
                            <!--div class="vantagens">
                                <a href="https://ofertas.farmadelivery.com.br/central_de_atendimento/" target="_blank">
                                    <div class="send-mail">
                                        <span>Fale<br>Conosco</span>
                                    </div>
                                </a>
                                <a href="https://reclameaqui.farmadelivery.com.br/" target="_blank">
                                    <div style="cursor: pointer" class="chat open-chat">
                                        <span>Abra um<br>Chamado</span>
                                    </div>
                                </a>
                                <a href="https://reclameaqui.farmadelivery.com.br/faq/" target="_blank">
                                    <div class="main-question">
                                        <span>Principais<br>Dúvidas</span>
                                    </div>
                                </a>
                            </div-->
                            <h4>Insira seu e-mail e receba informações e <b>ofertas exclusivas </b></h4>
                            <div class="newsletter">
                                <?php print $this->getLayout()
                                    ->createBlock("core/template")
                                    ->setTemplate("newsletter/subscribe.phtml")
                                    ->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="mascote"></div>
                </div>
            </div>
			<?php /*<div class="footer-session-social">
				<div class="social-share-session">
                    <?php /*echo $this->getLayout()->createBlock('cms/block')->setBlockId('social-share-session-content')->toHtml(); ?>
                    <div class="content">
                        <h2>Curta nossa p&aacute;gina!</h2>
                            <span style="font-weight: bold;">Fique por dentro das novidades</span> <a class="facebook-icon" href="https://www.facebook.com/FARMADELIVERY" target="_blank">facebook.com/farmadelivery</a>
                            <span style="font-size: 14px; margin: 31px auto 22px;">Acompanhe tamb&eacute;m:</span>
                            <div style="text-align: left;width: 100%;margin: 20px 88px;">
                                <a class="twitter" href="https://twitter.com/farmadelivery" target="_blank"></a>
                                <a class="instagram" href="https://www.instagram.com/farmadelivery/" target="_blank"></a>
                                <a class="youtube" href="https://www.youtube.com/user/FarmaDelivery/" target="_blank"></a>
                            </div>
                   </div>
				</div>
			</div>*/ ?>
        </div>
		<div class="col-menu">
			<div class="menu-footer">
				<h4>Institucional <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
				<ul class="institucional">
					<li><a href="<?php echo $this->getUrl()?>">Home</a></li>
					<li><a href="<?php echo $this->getUrl('quemsomos') ?>" rel="nofollow">Quem Somos</a></li>
					<li><a href="http://blog.poupafarma.com.br/nossas-lojas/" target="_blank">Lojas</a></li>
                    <li><a href="http://blog.poupafarma.com.br/mais-vantagens/" target="_blank">Mais Vantagens Poupa</a></li>
                    <li><a href="http://blog.poupafarma.com.br/clube-saude/" target="_blank">Convênio Empresa</a></li>
                    <li><a href="https://poupafarma.infojobs.com.br/empregos.aspx" target="_blank">Trabalhe Conosco</a></li>
                    <li><a href="http://blog.poupafarma.com.br/farmacia-popular/" target="_blank">Aqui tem farmácia popular</a></li>
                    <li><a href="<?php echo $this->getUrl('glossario-de-produtos') ?>">Glossário de Produtos</a></li>
				</ul>
			</div>
			<div class="menu-footer">
				<h4>Políticas <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
				<ul class="politicas">
					<li><a href="<?php echo $this->getUrl('politica_de_troca_devolucao_arrependimento') ?>">Pol&iacute;tica de Troca, Devolu&ccedil;&atilde;o e Arrependimento</a></li>
					<li><a href="<?php echo $this->getUrl('politica_de_envio') ?>">Pol&iacute;tica de Envio</a></li>
					<li><a href="<?php echo $this->getUrl('politica_de_pagamento') ?>">Pol&iacute;tica de Pagamento</a></li>
					<li><a href="<?php echo $this->getUrl('politica_de_privacidade') ?>">Pol&iacute;tica de Privacidade</a></li>
					<li><a href="<?php echo $this->getUrl('politica_de_seguranca') ?>">Pol&iacute;tica de Seguran&ccedil;a</a></li>
				</ul>
			</div>
			<div class="menu-footer">
				<h4>Navegação <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
				<ul class="navegacao">
					<li><a href="<?php echo $this->getUrl('catalog/seo_sitemap/category') ?>">Mapa do site</a></li>
				</ul>
			</div>
			<div class="menu-footer">
				<h4>Redes Sociais <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('redes-mobile')->toHtml(); ?>
			</div>
		</div>
     </div>
</div>

<div id="footer-store-info">
    <div class="store-contact">
        <p><i class="icon-font icon-ic_mail_black_24px"></i> <a href="https://ofertas.farmadelivery.com.br/central_de_atendimento/" target="_blank">Reclame Aqui</a></p>
        <p><i class="icon-font icon-ic_local_phone_black"></i> Televendas: (13) 3202-1000</p>
        <p><i class="icon-font icon-ic_shopping_cart_black_24px"></i> <a href="<?php echo Mage::getUrl('customer/account/') ?>"><?php echo $this->__('My Orders') ?></a></p>
        <p><i class="icon-font icon-ic_home_black_24px"></i> <a href="<?php echo Mage::getUrl('sales/order/history/') ?>"><?php echo $this->__('Registered Customers') ?></a></p>
    </div>

    <div class="seguranca">
        <ul>
            <!--
            <li><a href="https://www.ebit.com.br/farma-delivery" target="_blank"><img style="width:90px;" src="" alt="" /></a></li>
            -->
            <li>
                <a id="seloEbit" href="http://www.ebit.com.br/6449" target="_blank" data-noop="redir(this.href);"> </a>
                <script type="text/javascript" id="getSelo" src="https://imgs.ebit.com.br/ebitBR/selo-ebit/js/getSelo.js?6449"> </script>
            </li>
            <li><a href="https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.farmadelivery.com.br%2F" target="_blank">
                    <img style="width: 150px;" src="<?php echo $this->getSkinUrl('images/selo_google_sb.png'); ?>" alt="" /></a></li>
            <li><a href="http://abcomm.org/certificado.php?url=WWW.FARMADELIVERY.COM.BR" target="_blank"><img src="https://www.farmadelivery.com.br/media/wysiwyg/selocomm.png" style="width: 80px;" /></a></li>
        </ul>
    </div>

    <div class="selo-interno">
        <dl>
            <dd class="selosonestic">
                <a href="https://onestic.com/" title="Onestic - Lojas Virtuais para E-commerce" rel="external" target="_blank">
                    <img src="<?php echo $this->getSkinUrl('images/poweredby.png') ?>" alt="Onestic - Lojas Virtuais para E-commerce" title="Onestic - Lojas Virtuais para E-commerce" />
                </a><br />
            </dd>
        </dl>
    </div>

    <div class="info" style="margin: 25px 0 0;text-align: center;color: #666;font-size: 12px;">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('poupafarma-info')->toHtml(); ?>
    </div>
</div>

<div id="frete-gratis-condicoes" class="frete-gratis-condicoes">
    <div class="frete-gratis-condicoes-modal">
        <a href="#frete-gratis-condicoes" class="close-modal">Fechar</a>
        <div class="frete-gratis-condicoes-content">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('frete-gratis-condicoes')->toHtml(); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery('.open-modal').click(function(){
        var target = jQuery(this).attr('href');
        jQuery(target).show();
        return false;
    });
    jQuery('.close-modal').click(function(){
        var target = jQuery(this).attr('href');
        jQuery(target).hide();
        return false;
    });
</script>

<script type="text/javascript">

    function trocarImagemAlgolia() {

        jQuery("[class^=result], [class^=algoliasearch-autocomplete-hit]").each(function(index) {
            var _ids = jQuery(this).attr("category-ids");
            var pague_leve = jQuery(this).attr("pague-leve");
            var frete_gratis = jQuery(this).attr("frete-gratis");
            var image_promotion = jQuery(this).attr("image-promotion");
            var before_special = Number(String(jQuery(this).attr("before-special")).replace(/[^0-9.-]+/g,""));
            var after_special = Number(String(jQuery(this).attr("after-special")).replace(/[^0-9.-]+/g,""));

            if (_ids) {
                var split_str = _ids.split(',');
                if (split_str.indexOf("26") !== -1) {
                    jQuery(this).find("img").attr("src", "/media/wysiwyg/Imagens/produto-sem-imagem-controle-especial-farmadelivery-277.jpg");
                }else if(split_str.indexOf("295") !== -1){
                    jQuery(this).find("img").attr("src", "/media/wysiwyg/Imagens/produto-sem-imagem-antimicrobiano-farmadelivery-277.jpg");
                }else if(split_str.indexOf("14") !== -1 && split_str.indexOf("28") !== -1){
                    jQuery(this).find("img").attr("src", "/media/wysiwyg/Imagens/caixa-genericos-tarjados-farmadelivery-277_1.jpg");
                }else if(split_str.indexOf("28") !== -1){
                    jQuery(this).find("img").attr("src", "/media/wysiwyg/caixa-tarjados-farmadelivery.jpg");
                }
            }

            if (pague_leve) {
                if(pague_leve == "Não") {
                    jQuery(this).find("#algolia_pague_leve").css("display", "none");
                }else{
                    jQuery(this).find("#algolia_pague_leve").css("background-color", "#F25300");
                    jQuery(this).find("#algolia_pague_leve").html(jQuery(this).find("#algolia_pague_leve").html().split("&lt;br /&gt;").join("<br />"));
                }
            }

            if (frete_gratis) {
                if(frete_gratis == "Não"){
                    jQuery(this).find("#algolia_frete_gratis").css("display", "none");
                }else{
                    jQuery(this).find("#algolia_frete_gratis").css("background-color", "#F25300");
                    jQuery(this).find("#algolia_frete_gratis").html(jQuery(this).find("#algolia_frete_gratis").html().split("&lt;br /&gt;").join("<br />"));
                }
            }

            if (before_special > 0) {
                var percent = 100 - (after_special * 100 / before_special);

                if(jQuery(this).find("#algolia_percent_discount").html() == 0) {
                    jQuery(this).find("#algolia_percent_discount").html(jQuery(this).find("#algolia_percent_discount").html().split("0").join("-" + Math.round(percent) + "%"));
                    jQuery(this).find("#algolia_percent_discount").css("background-color", "#ff7f0b");
                }
            }

            // atualizando SKU para produtos configuráveis
            jQuery('.result-sub-content .product-sku').each(function() {
                var skuContent = jQuery(this).text();
                if (!(skuContent.indexOf(',') == -1)) {
                    jQuery(this).html(skuContent.substr(0, skuContent.indexOf(',')));
                }
            });

        });

        // Corrige tag BR
        /*var tagbr = jQuery('div.is-widget-container-frete_gratis_dropdown label').html();
        tagbr = tagbr.replace('&lt;br /&gt;', '<br>'); 
        jQuery('div.is-widget-container-frete_gratis_dropdown label').html(tagbr);*/

    }

    jQuery(window).load(function() {
        setTimeout(function() { trocarImagemAlgolia(); }, 300);
    });

    jQuery(document).bind('keypress, keydown', function(e){
        if(e.which) {
            setTimeout(function() { trocarImagemAlgolia(); }, 300);
        }
    });

    jQuery(document).click(function() {
        setTimeout(function() { trocarImagemAlgolia(); }, 300);
    });

    // Corrige tag BR
    /*var tagbr = jQuery('div.is-widget-container-frete_gratis_dropdown label').html();
    tagbr = tagbr.replace('&lt;br /&gt;', '<br>'); 
    jQuery('div.is-widget-container-frete_gratis_dropdown label').html(tagbr);*/

</script>

<?php $storeId = Mage::app()->getStore()->getStoreId(); ?> 
<?php if ($storeId == 1): ?>
    <!-- CÓDIGO DE MONITORAMENTO RD -->
    <script type="text/javascript" async src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/9f3175c9-992a-4be4-be76-d3c695e6af75-loader.js"></script>
<?php endif; ?>

<?php echo $this->getChildHtml('track-scripts'); ?>