<div id="topo-site" class="header-container">
    <div class="header">

        <div id="modal-televendas" class="simple-modal">
            <div class="simple-modal-overlay"></div>
            <div class="simple-modal-content">
                <a href="#modal-televendas" class="simple-modal-close">Fechar</a>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('televendas')->toHtml(); ?>
            </div>
        </div>

        <div class="header-main">
            <div class="header-center">
                <i id="menu-toggle" class="icon-font icon-ic_menu_black_24px"></i>

                <?php echo $this->getChildHtml('logo') ?>
                <!--a target="_blank" href="http://blog.farmadelivery.com.br/"><span class="blog-mobile">Blog</span></a-->
                <!--a href="https://www.serviir.com.br/atendimentochat/ac/17e62166fc8586dfa4d1bc0e1742c08b" target="_blank" class="selo-serviir">
                    <img src="https://www.serviir.com.br/media/img/selo_serviir.png" width="45">
                </a-->

                <div id="cart-box">
                    <i id="icon-cart" class="icon-font icon-title icon-ic_shopping_cart_black_24px"></i>
                    <?php echo $this->getChildHtml('mini_cart_top') ?>
                </div>
            </div>
        </div>

        <div class="top-nav">
            <div class="header-center">
                <div class="acesso-rapido">
                    <div class="link-acesso">
                        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
                            <a href="<?php echo $this->getUrl('customer/account/index') ?>">Minha Conta</a>
                            <a href="<?php echo $this->getUrl('customer/account/logout') ?>">Sair</a>
                            <?php } else { ?>
                            <a href="<?php echo $this->getUrl('customer/account/login') ?>">login </a>
                            <a href="<?php echo $this->getUrl('customer/account/create/') ?>">Cadastre-se</a>
                            <?php } ?>

                            <i class="icon-font icon-error"></i>

                    </div>
                </div>

                <?php echo $this->getChildHtml('catalog.topnav') ?>
            </div>
        </div>

    </div>
    <div id="search-box">
        <?php echo $this->getChildHtml('topSearch') ?>
    </div>
</div>
<div class="banner-frete-mobile">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-frete-mobile')->toHtml(); ?>
</div>


<div class="banner-home">
    <?php echo $this->getChildHtml('banner-principal-mobile') ?>
</div>