<?php
/**
 * Inchoo is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>" class="btn ui-button auth-button btn-primary"><span><span><?php echo $this->__('Conectar com Facebook') ?></span></span></a>
