<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Followupemail
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

if(!Mage::getStoreConfig('followupemail/general/displaysubscribebuttononcheckoutpage')) return;

$_title = Mage::helper('followupemail')->__('Sign Up for Newsletter');

if(!$isSubscribed = $this->getIsSubscribed()): ?>
<form action="" id="checkout-subscribe" onsubmit="return false;">
    <div class="checkout-subscribe">
        <input type="checkbox" id="subscribe-newsletter" name="subscribe-newsletter" value="1" onclick="setSubscribed();" title="<?php echo $_title ?>" <?php echo !$isSubscribed ? ' checked="checked"' : '' ?> />
        <label for="subscribe-newsletter"><?php echo $_title ?></label>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var fIsSubscribed = document.createElement('input');
    fIsSubscribed.type = 'hidden';
    fIsSubscribed.name = 'newsletter-subscribed';
    fIsSubscribed.id = 'newsletter-subscribed';
    fIsSubscribed.value = '<?php echo (int)$isSubscribed ?>';
    $('co-payment-form').appendChild(fIsSubscribed);

    function setSubscribed(){
        $('co-payment-form').elements['newsletter-subscribed'].value = $('subscribe-newsletter').checked ? 1 : 0;
    }

    enableSetSubscribed = function(event){
        $('newsletter-subscribed').disabled = false;
    }

    Event.observe($('opc-payment'), 'click', enableSetSubscribed);
//]]>
</script>
<?php endif; ?>