<div class="content-header">
    <table class="grid-header">
        <tr>
            <td><h3>Logs do Sistema</h3></td>
            <td class="a-right">
            	<button onclick="editForm.submit()" class="scalable save" type="button"><span>Limpar Selecionados</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post')?>" target="_self">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    	<div class="grid">
            <table class="data" cellspacing="0" cellpadding="0">
            	<colgroup>
            		<col width="20" class="a-center">
                    <col>
                    <col width="180" class="a-center">
                    <col width="180" class="a-center">
                </colgroup>
            	<thead>
            		<tr class="headings">
	            		<th >#</th>
	            		<th>Arquivo</th>
	            		<th>Tamanho</th>
	            		<th class="a-center">Ações</th>
            		</tr>
            	</thead>
            	<?php 
            		$even = true;
            		foreach ($this->getLogFiles() as $index => $file):
            	?>
                <tr class="<?php echo ($even) ? "even" : ""; $even = !$even;?>">
                    <td><input type="radio" name="log" id="log_<?php echo $index; ?>" value="<?php echo $file['name']; ?>" /></td>
                    <td><label for="log_<?php echo $index; ?>"><?php echo $file['name']; ?></label></td>
                    <td align="center"><label for="log_<?php echo $index; ?>"><?php echo $file['size']; ?>KB</label></td>
                    <td align="center"><a href="<?php echo $this->getUrl('*/*/view') . 'file/' . $file['name']; ?>">Visualizar</a> | <a href="<?php echo $this->getUrl('*/*/post') . 'log/' . $file['name']; ?>">Limpar</a></td>
                </tr>
                <?php endforeach; ?>
            </table>
    	</div>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>