<?php $file = $this->getFile(); ?>
<div class="content-header">
	<h3 class="icon-head head-backups-control">Visualização de arquivo: <?php echo $file['name']; ?></h3>
	<div class="a-right">
    	<button onclick="setLocation('<?php echo $this->getUrl('*/*'); ?>')" class="scalable back" type="button"><span>Voltar</span></button>
    	<button onclick="deleteConfirm('Deseja realmente limpar esse arquivo?','<?php echo $this->getUrl('*/*/post') . 'name/' . $file['name']; ?>')" class="scalable delete" type="button"><span>Limpar</span></button>
    	<button onclick="deleteConfirm('Deseja realmente excluir esse arquivo?','<?php echo $this->getUrl('*/*/delete') . 'name/' . $file['name']; ?>')" class="scalable delete" type="button"><span>Excluir</span></button>
    	<button onclick="setLocation('<?php echo $this->getUrl('*/*/download') . 'name/' . $file['name']; ?>')" class="scalable" type="button"><span>Download</span></button>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend">Conteúdo do Arquivo</h4>
    </div>
    <fieldset>
        <pre style="white-space: pre-line"><?php echo $file['content']; ?></pre>
        <form id="exception_form" name="exception_form" action="<?php echo $this->getFormAction(); ?>" method="POST">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
            <input type="hidden" name="type" id="type" value="<?php echo $file['type']; ?>" />
            <input type="hidden" name="download" id="download" value="<?php echo $file['name']; ?>" />
        </form>
    </fieldset>
</div>
