<?php 
$helper = Mage::helper("onestic_skyhub");
?>
<div class="content-header">
    <table class="grid-header">
        <tr>
            <td><h3>Importação de Pedidos Skyhub</h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <ul id="andamento"></ul>
    <div id="loader"><img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/> Processando importação...</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var totalService = 0;
    var updatedTotal = 0;
    var current_page = 0;
    function startUpdate() {
		$('andamento').innerHTML = '';
		$('andamento').insert('<li><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>Importando pedidos, por favor aguarde... </li>');
		updateProgress();	
    }
    function updateProgress() {
    	new Ajax.Request( '<?php echo $this->getUrl("*/*/populate"); ?>', {
			method: 'GET',
			evalScripts: true,
			onLoading: function(transport) {
				$('loader').show();
			},
			onComplete: function(transport) {
				$('loader').hide();
			},
			onSuccess: function(transport) {
				if (200 == transport.status) {
					response = transport.responseText.split('|');
					if(response[0] != '' && response[0] != '0') {
						$('andamento').insert('<li style="background-color:#DDF;"><img src="<?php echo $this->getSkinUrl('images/fam_bullet_success.gif');?>" class="v-middle" style="margin-right:5px"/> Pedidos importados: '+response[0]+' - Erros: '+response[1]+'</li>');
						updatedTotal = updatedTotal + parseInt(response[0]);
						totalService = parseInt(response[2]);
						percent = (updatedTotal / totalService) * 100;
						$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/> Importado ' + Math.round(percent) + '% de ' + totalService + ' pedidos. Processando importação...'; 
						updateProgress();
					
					} else if(response[0] == '0' && response[1] == '0' && response[2] == totalService && response[2] != '') {
						$('andamento').insert('<li><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>Processo Finalizado</li>');
					} else {
						$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/> Ocorreu um erro, repetindo o processo.';
						updateProgress();
					}
				}
			},
			onFailure: function() {
				$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/> Ocorreu um erro, repetindo o processo.';
				updateProgress();
			}
		});
    }
    document.observe('dom:loaded', function() {
        startUpdate();
    });
//]]>
</script>
<style type="text/css" >
	td.label {
		text-align: right;
		padding-right: 10px;
	}
    ul#andamento { list-style-type:none; padding:0; margin:0; }
    ul#andamento li, #loader { margin-left:0; border:1px solid #ccc; margin:2px; padding:2px 2px 2px 2px; font:normal 12px sans-serif; }
    ul#andamento li img, #loader img { margin-right:5px; }
</style>