<?php 
$helper = Mage::helper("onestic_skyhub");
?>
<div class="content-header">
    <table class="grid-header">
        <tr>
            <td><h3>Sincronização de Pedidos Skyhub</h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <ul id="andamento"></ul>
    <div id="loader"><img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/> Processando sincronização...</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var totalService = 0;
    var updatedTotal = 0;
    var current_page = 0;
    function startUpdate() {
		$('andamento').innerHTML = '';
		$('andamento').insert('<li><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>Sincronizando pedidos, por favor aguarde... </li>');
		updateProgress();	
    }
    function updateProgress() {
    	new Ajax.Request( '<?php echo $this->getUrl("*/*/resync"); ?>', {
			method: 'GET',
			evalScripts: true,
			onLoading: function(transport) {
				$('loader').show();
			},
			onComplete: function(transport) {
				$('loader').hide();
			},
			onSuccess: function(transport) {
				if (200 == transport.status) {
					response = transport.responseText.evalJSON();
					if(response.count != 0 && response.count != totalService) {
						$('andamento').insert('<li style="background-color:#DDF;"><img src="<?php echo $this->getSkinUrl('images/fam_bullet_success.gif');?>" class="v-middle" style="margin-right:5px"/> Pedidos sincronizados: '+response.success+' - Erros: '+response.errors+'</li>');
						updatedTotal = parseInt(response.count);
						totalService = parseInt(response.total);
						percent = (updatedTotal / totalService) * 100;
						$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/> Importado ' + Math.round(percent) + '% de ' + totalService + ' pedidos. Processando sincronização...'; 
						updateProgress();
					} else if(response.success == 0 && response.errors == 0 && response.count == 0 && response.total != 0) {
						$('andamento').insert('<li><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>Processo Finalizado</li>');
					} else {
						$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/> Ocorreu um erro, verifique o log do sistema.';
					}
				}
			},
			onFailure: function() {
				$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/> Ocorreu um erro, verifique o log do sistema.';
			}
		});
    }
    document.observe('dom:loaded', function() {
        startUpdate();
    });
//]]>
</script>
<style type="text/css" >
	td.label {
		text-align: right;
		padding-right: 10px;
	}
    ul#andamento { list-style-type:none; padding:0; margin:0; }
    ul#andamento li, #loader { margin-left:0; border:1px solid #ccc; margin:2px; padding:2px 2px 2px 2px; font:normal 12px sans-serif; }
    ul#andamento li img, #loader img { margin-right:5px; }
</style>