<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php
$watermarks = Mage::getStoreConfig( 'checkout/watermarks' );
$inline_validation_messages = Mage::getStoreConfig( 'checkout/inline_validation_messages' );
$countryOptions = $this->getCountryOptions();
$countryOptionsCount = count( $countryOptions );
$pincode_maxlength = Mage::getStoreConfig( 'checkout/options/pincode_maxlength' );
$separate_shipping_method_step = Mage::getStoreConfig( 'checkout/options/separate_shipping_method_step' );
$disable_postcode_autocomplete = Mage::getStoreConfig( 'checkout/options/disable_postcode_autocomplete' );
?>

<script type="text/javascript">
	var countryOptions = <?php echo json_encode( $countryOptions ) ?>;
</script>
<header>
	<h2 class="page-title">Endere&ccedil;o de Entrega</h2>
	<h4>Selecione um endereço e escolha uma das opções de frete disponíveis</h4>
</header>
<form action="<?php echo $this->getUrl( 'checkout/onepage/saveShipping' ) ?>" id="co-shipping-form" method="post">
	<ul class="form-list">
		<?php if ( !$this->isCustomerLoggedIn() ): ?>
			<?php echo $this->getChildHtml( 'login' ); ?>
		<?php endif; ?>
		<?php if ( $this->customerHasAddresses() ): ?>
			<li class="form saved-address">
				<!-- <label for="shipping-address-select"><?php //echo $this->__( 'Select a shipping address from your address book or enter a new address.' ) ?></label> -->
				<ul class="row">
					<?php 
					$addresses = $this->getAddressesHtmlSelect( 'shipping' );
					foreach ($addresses as $address): 
						$title = 'Outro Endere&ccedil;o';
						$checked = '';
						$class = '';
						if ($address['main']) {
							$title = 'Endere&ccedil;o Principal';
							$class = '';
							$checked = '';
						}
					?>
					<li class="col-xs-6 col-sm-4 col-md-4">
						<label for='shipping_customer_address_<?php echo $address['id']; ?>' 
							class='box-address <?php echo $class; ?>' id='shipping_address_label_<?php echo $address['id']; ?>'>
							
							<!-- <div class='address-title pull-left'>
								<?php //echo $title ?>
							</div> -->

							<div class="input">
								<input type='radio' name='shipping_address_id'
									id='shipping_customer_address_<?php echo $address['id'] ?>'
									value='<?php echo $address['id']?>' <?php echo $checked; ?>
									onclick='shipping.newAddress(!this.value)' style="display: none;" />
								<i class="fa fa-check-circle"></i>
							</div>
							<div class='address'>
								<div class='name'>
									<strong>
										<?php echo $address['name']; ?>
									</strong>
								</div>
								<span><?php echo $address['street']?></span>
								<span><?php echo $address['neighbor']?></span>
								<span><?php echo $address['city']?> - <?php echo $address['region']?></span>
								<span>CEP: <?php echo $address['postcode']?></span>
							</div>
							<div class="selected">Selecionado</div>
						</label>
					</li>
					<?php
					endforeach; 
					?>
					<li class="col-xs-6 col-sm-4 col-md-4 text-center">
						<label for='shipping_customer_address_new' class="box-address box-address-new">
							<div class='input'>
								<input type='radio' name='shipping_address_id'
									id='shipping_customer_address_new'
									value=''
									onclick='shipping.newAddress(true);' />
							</div>
							<div class='address'>
								<i class="fa fa-plus-circle"></i>
								<span>Adicionar Novo</span>
							</div>
						</label>
					</li>
				</ul>
				<span class="please-wait" id="address-please-wait" style="display:none;">
					<img src="<?php echo $this->getSkinUrl( 'onestic/checkout/images/opc-ajax-loader.gif' ) ?>" alt="<?php echo $this->__( 'Atualizando...' ) ?>" title="<?php echo $this->__( 'Atualizando...' ) ?>" class="v-middle" /> <?php echo $this->__( 'Atualizando...' ) ?>
				</span>
			</li>
		<?php endif; ?>
		
		<li class="form" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> 
			style="display:none;"<?php endif ?>>
			<div class="panel panel-default">
	  		<div class="panel-body">
		  		<div class="row">
						<fieldset class="col-md-8 col-md-offset-2">
							<legend>Endereço de envio</legend>
							<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
							<ul>
								<li class="fields row">
									<?php echo $this->getLayout()->createBlock('onestic_checkout/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?>
								</li>

								<li class="fields row">
									<div class="col-xs-6">
										<label for="shipping:telephone" class="required">
											<?php echo $this->__('Telephone') ?>
										</label>
										<div class="input-box">
											<input type="text" name="shipping[telephone]" id="shipping:telephone" 
												value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" 
												title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" 
												class="form-control required" />
										</div>
									</div>
									<div class="col-xs-6">
										<label for="shipping:fax">Celular</label>
										<div class="input-box">
											<input type="text" name="shipping[fax]" id="shipping:fax" 
												value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" 
												title="Celular" 
												class="form-control" />
										</div>
									</div>
								</li>

								<li class="fields row">
									<div class="col-xs-6 postcode">
										<label for="shipping:postcode" class="required">
											<?php echo $this->__('CEP') ?>
										</label>
										<div class="input-box">                            
											<input type="text" name="shipping[postcode]" 
												value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" 
												title="<?php echo $this->__('Zip/Postal Code') ?>" 
												id="shipping:postcode" class="input-text required"
												maxlength="9" />
										</div>
										<span id="shipping:load-end" class="shipping-load" style="display: none;">
											<img src="<?php echo $this->getSkinUrl('onestic/checkout/images/opc-ajax-loader.gif');?>" />
										</span>
									</div>
									<div class="col-xs-6">
										<label>&nbsp;</label>
										<div class="input-box">
											<a class="nao-sei-cep" href="#" 
												onclick="popWin('http://m.correios.com.br/movel/buscaCep.do', 'I forgot my zipcode', 'width=360,height=370,left=200,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;">
												<?php echo $this->__('What is my postcode?') ?>
											</a>
										</div>	
									</div>
								</li>

								<li class="fields">
									<label for="shipping:street1" class="required">
										<?php echo $this->__( 'Distrito' ) ?><em>*</em>
									</label>
									<div class="input-box">
										<input type="text" title="<?php echo $this->__( 'Distrito' ) ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet(1) ) ?>" class="input-text required" />
									</div>
								</li>

								<li class="fields">
									<div class="number">
										<label for="shipping:street2" class="required">Complemento do Distrito<em>*</em></label>
										<div class="input-box">
											<input type="text" title="Complemento do Distrito" name="shipping[street][]" id="shipping:street2" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 2 ) ) ?>" class="input-text required" />
										</div>
									</div>
									<div class="complement">
										<label for="shipping:street3">Conjunto residencial ou edifício + bloco + apato</label>
										<div class="input-box">
											<input type="text" title="Conjunto residencial ou edifício + bloco + apato" name="shipping[street][]" id="shipping:street3" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 3 ) ) ?>" class="input-text" />
										</div>
									</div>
								</li>

								<li class="wide">
									<label for="shipping:street4" class="required">Complemento</label>
									<div class="input-box">
										<input type="text" title="Complemento" name="shipping[street][]" id="shipping:street4" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 4 ) ) ?>" class="input-text required" />
									</div>
                                    <p>
                                        Se Província/Cidade/Distrito estão corretos, deixe este campo em branco, se há divergência, registre o correto.
                                    </p>
								</li>

								<li class="fields row">
									<div class="col-md-6 field city">
										<label for="shipping:city" class="required"><?php echo $this->__( 'City' ) ?><em>*</em></label>
										<div class="input-box">
											<input type="text" title="<?php echo $this->__( 'City' ) ?>" name="shipping[city]" value="<?php echo $this->htmlEscape( $this->getAddress()->getCity() ) ?>" class="input-text required" id="shipping:city" />
										</div>
									</div>
									<div class="col-md-6 field state">
										<label for="shipping:region_id" class="required"><?php echo $this->__( 'State/Province' ) ?><em>*</em></label>
										<div class="input-box">
											<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__( 'State/Province' ) ?>" class="validate-select required" style="display:none;">
												<option value=""><?php echo $this->__( 'Please select region, state or province' ) ?></option>
											</select>
											<script type="text/javascript">
												//<![CDATA[
												setTimeout(function(){
													jQuery(jq('shipping:region_id')).val("<?php echo $this->getAddress()->getRegionId(); ?>");
												},500);
												//]]>
											</script>
											<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape( $this->getAddress()->getRegion() ) ?>" title="<?php echo $this->__( 'State/Province' ) ?>" class="input-text required" style="display:none;" />
										</div>
									</div>
								</li>
								
								<li class="hidden">
									<div class="country">
										<label for="shipping:country_id" class="required">
											<?php echo $this->__( 'Country' ) ?><em>*</em>
										</label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect( 'shipping' ); ?>
										</div>
									</div>
								</li>

								<?php if ( $this->isCustomerLoggedIn() && $this->customerHasAddresses() ): ?>
									<li class="control">
										<input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__( 'Salvar endere&ccedil;o' ) ?>" id="shipping:save_in_address_book"<?php if ( $this->getAddress()->getSaveInAddressBook() ): ?> checked="checked"<?php endif; ?> 
											class="checkbox" />
											<label for="shipping:save_in_address_book">
												<?php echo $this->__( 'Salvar endere&ccedil;o' ) ?>
											</label>
									</li>
								<?php else: ?>
									<li class="no-display">
										<input type="hidden" name="shipping[save_in_address_book]" value="1" />
									</li>
								<?php endif; ?>
							</ul>
						</fieldset>
					</div>
				</div>
			</div>
		</li>
	</ul>
	<?php if ( $separate_shipping_method_step ): ?>
	<footer id="shipping-buttons-container">
		<input type="submit" class="button btn btn-success" 
			title="<?php echo $this->__( 'Proceed to Shipping Method' ) ?>" 
			onclick="shipping.triggerShippingSave = 1; shipping.save();return false;" 
			value="<?php echo $this->__( 'Proceed to Shipping Method &rarr;' ) ?>"/>
			<span id="shipping-please-wait" class="please-wait" style="display:none;">
			<img src="<?php echo $this->getSkinUrl( 'onestic/checkout/images/opc-ajax-loader.gif' ) ?>" 
				alt="<?php echo $this->__( 'Loading next step...' ) ?>" 
				title="<?php echo $this->__( 'Loading next step...' ) ?>" 
				class="v-middle" />
				<?php echo $this->__( 'Loading next step...' ) ?>
		</span>

		<p class="required">
			<?php echo $this->__( '* Campos obrigatórios' ) ?>
		</p>
	</footer>
	<?php endif; ?>
</form>
<script type="text/javascript">
	//<![CDATA[
	if(!BASE_URL) var BASE_URL = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
	
	var billing = new Billing({
		form: '#co-payment-form', // billing form is just fields inside the payment <form>
		getAddressUrl: '<?php echo $this->getUrl( 'onestic_checkout/onepage/getAddress' ) ?>'
	});
	var shipping = new Shipping({
		form: '#co-shipping-form',
		getAddressUrl: '<?php echo $this->getUrl( 'onestic_checkout/onepage/getAddress' ) ?>',
		loadingMessage: '<?php echo $this->__( 'Calculando frete...' ) ?>',
		oldLoadingMessage: '<?php echo $this->__( 'Prosseguir ' ) ?>',
		savingMessage: '<?php echo $this->__( 'Salvando frete...' ) ?>',
		oldSavingMessage: '<?php echo $this->__( 'Selecionar Frete ' ) ?>'
	});

	if ($('shipping:postcode')) {
		$('shipping:postcode').addClassName('validate-zip-br');
		$('shipping:postcode').observe('keypress', function() {
			formata_cep(this);
		});
		$('shipping:postcode').observe('blur', function() {
			getAddress('shipping');
		});
	}

	if ($('shipping:telephone')) {
		$('shipping:telephone').observe('keypress', function() {
			formata_telefone(this);
		});
	}

	if ($('shipping:fax')) {
		$('shipping:fax').observe('keypress', function() {
			formata_telefone(this);
		});
	}

	var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
	//]]>
</script>
<?php if ( !$separate_shipping_method_step ): ?>
	<?php echo $this->getChildHtml( 'shipping_method' ); ?>
<?php endif; ?>
