<?php

/**
 *
 * @category   Onestic
 * @package    Onestic_Checkout
 * @author     Suporte <suporte@onestic.com>
 */

?>
<?php
	$value = $this->getRgie();
?>
<div id="rgie_container">
	<label for="rgie" id="label_rgie">RG (Opcional)</label>
	<div class="input-box">
		<input type="text" name="rgie" id="rgie" 
			value="<?php echo $value ?>" 
			title="RG/IE" 
			class="form-control" />
	</div>
</div>