<?php

/**
 *
 * @category   Onestic
 * @package    Onestic_Checkout
 * @author     Suporte <suporte@onestic.com>
 */
?>
<label for="<?php echo $this->getFieldId('taxvat')?>"<?php if ($this->isRequired()) echo ' class="required"' ?> id="label_cpf">
	Número do CPF <?php if (!$this->isRequired()) echo '(Opcional)' ?>
</label>
<div class="input-box" id="billing_cpf">
    <input type="text" maxlength="14" id="<?php echo $this->getFieldId('taxvat')?>" 
    	name="<?php echo $this->getFieldName('taxvat')?>" 
    	value="<?php echo $this->htmlEscape($this->getTaxvat()) ?>" 
    	title="Número do Documento" 
    	class="form-control <?php if ($this->isRequired()){echo 'required-entry';} ?>" 
    	<?php echo $this->getFieldParams() ?> />
</div>
