<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<div id="onestepcheckout-address-billing">
    <ul class="form-list">
        <?php if ($this->customerHasAddresses()): ?>
            <li class="wide">
                <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                <div class="input-box">
                    <?php echo $this->getAddressesHtmlSelect('billing') ?>
                </div>
            </li>
        <?php endif; ?>
        <li>
            <ul id="onestepcheckout-billing-address-list"<?php if ($this->customerHasAddresses()): ?> style="overflow: hidden;height: 0px;display:none"<?php endif; ?>>
                <?php if (!$this->isCustomerLoggedIn()) : ?>    
                    <li>
                        <p id="login-call">
                            Já é cadastrado? <a href="#open-onestepcheckout-authentification" id="open-onestepcheckout-authentification"><?php echo $this->__('Faça Login') ?></a>
                        </p>
                    </li>
                
                    <?php $_tipopessoa = $this->getLayout()->createBlock('onestepcheckout/widget_tipopessoa') ?>
                    <?php if ($_tipopessoa->isEnabled()): ?>
                        <li class="control fields tipopessoa">
                            <div class="field">
                                <input type="radio" name="billing[radio_tipopessoa]" value="Física" id="billing:fisica" class="radio" title="CPF" <?php if ($this->getDataFromSession('radio_tipopessoa') == 'Física'): ?> checked="checked"<?php endif; ?>/><label for="billing:fisica"><?php echo $this->__('Pessoa Física') ?></label>
                            </div>
                            <div class="field">
                                <input type="radio" name="billing[radio_tipopessoa]" value="Jurídica" id="billing:juridica" class="radio" title="CNPJ" <?php if ($this->getDataFromSession('radio_tipopessoa') == 'Jurídica'): ?> checked="checked"<?php endif; ?>/><label for="billing:juridica"><?php echo $this->__('Pessoa Jurídica') ?></label>
                            </div>
                        </li>
                        <li class="wide hidden">
                            <?php echo $_tipopessoa->setTipopessoa($this->getDataFromSession('tipopessoa'))->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </li>
                    <?php endif ?>
                <?php endif ?>
                <?php if (!$this->isCustomerLoggedIn()) : ?>
                    <li class="wide">
                        <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" title="<?php echo $this->__('Email') ?>" class="input-text validate-email validate-email-exist required-entry" value="<?php echo $this->getDataFromSession('email'); ?>" />
                        </div>
                    </li>
                    <li>
                        <ul id="osc-billing-password-area" style="overflow: hidden;<?php if (!$this->getDataFromSession('create_account') && $this->customerMustBeRegistered()): ?>height: 0px;display:none<?php endif; ?>">
                            <li class="fields">
                                <div class="field">
                                    <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <?php if ($this->customerMustBeRegistered()): ?>
                        <li class="control">
                            <input type="checkbox" name="billing[create_account]" value="1" title="<?php echo $this->__('Create Account') ?>" id="billing:create_account" class="checkbox"<?php if ($this->getDataFromSession('create_account')): ?> checked="checked"<?php endif; ?>/><label for="billing:create_account"><?php echo $this->__('Create Account') ?></label>
                        </li>
                    <?php else: ?>
                        <input type="hidden" name="billing[create_account]" value="1" id="billing:create_account" />
                    <?php endif ?>
                    
                    <?php if (!$this->isCustomerLoggedIn()): ?>
                        <?php if ($this->isTaxvatEnabled()): ?>
                            <li class="wide">
                                <?php echo $this->getTaxvatHtml() ?>
                            </li>
                        <?php endif; ?>
                        <li>
                            <ul id="osc-billing-tipopessoa-area"  style="overflow: hidden;display:block;">
                                <li class="wide">
                                    <?php $_dateOfBirthWidget = $this->getCustomerWidgetDateOfBirth(); ?>
                                    <?php if ($_dateOfBirthWidget->isEnabled()): ?>
                                        <?php echo $_dateOfBirthWidget->toHtml() ?>
                                    <?php endif; ?>
                                </li>
                                <li class="wide">
                                    <?php $_genderWidget = $this->getCustomerWidgetGender(); ?>
                                    <?php if ($_genderWidget->isEnabled()): ?>
                                        <?php echo $_genderWidget->toHtml() ?>
                                    <?php endif ?>                                    
                                </li>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->getConfig()->isCompany()): ?>
                        <li class="wide">
                            <label for="billing:company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:company" name="billing[company]" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->getAttributeValidationClass('company') ?>" value="<?php echo $this->getDataFromSession('company'); ?>" />
                            </div>
                        </li>
                    <?php endif; ?>
                <?php endif ?>
                <li class="fields">
                    <?php echo $this->getCustomerWidgetName()->toHtml(); ?>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text validate-phone-br <?php echo $this->getAttributeValidationClass('telephone') ?>" id="billing:telephone" value="<?php echo $this->getDataFromSession('telephone'); ?>" />
                        </div>
                    </div>
                     <?php if ($this->getConfig()->isFax()): ?>
                        <div class="field">
                            <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="billing[fax]" title="<?php echo $this->__('Fax') ?>" class="input-text validate-phone-br <?php echo $this->getAttributeValidationClass('fax') ?>" id="billing:fax" value="<?php echo $this->getDataFromSession('fax'); ?>" />
                            </div>
                        </div>
                    <?php endif ?>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" class="input-text validate-number <?php echo $this->getAttributeValidationClass('postcode') ?>" value="<?php echo $this->getDataFromSession('postcode') ?>" maxlength="8" onblur="checkCepJapao(this.value, 'billing:')" />
                        </div>
                    </div>
                    <div class="field"></div>
                </li>

                <li class="fields">
                    <div class="field">
                        <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->getDataFromSession('region') ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text required-entry <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                        </div>
                    </div>

                    <div class="field">
                        <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="input-text <?php echo $this->getAttributeValidationClass('city') ?>" id="billing:city" value="<?php echo $this->getDataFromSession('city') ?>" />
                        </div>
                    </div>
                </li>

                <?php $_streetValidationClass = $this->getAttributeValidationClass('street'); ?>
                <?php $streetValues = $this->getDataFromSession('street'); ?>
                <li class="wide">
                    <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" class="input-text <?php echo $_streetValidationClass ?>" value="<?php echo (isset($streetValues[0])) ? $streetValues[0] : ''; ?>" autocomplete="off"/>
                    </div>
                </li>
                
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

                <li class="wide">
                    <label for="billing:street2" class="required"><em>*</em> <?php echo $this->__('Street Address 2') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address 2') ?>" name="billing[street][2]" id="billing:street2" class="input-text required-entry" value="<?php echo $streetValues[2]; ?>" autocomplete="off"/>
                    </div>
                </li>

                <li class="wide">
                    <label for="billing:street4"><?php echo $this->__('Street Address 4') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address 4') ?>" name="billing[street][4]" id="billing:street4" class="input-text" value="<?php echo $streetValues[4]; ?>" autocomplete="off"/>
                    </div>
                </li>

                <li class="wide">
                    <label for="billing:street3"><?php echo $this->__('Street Address 3') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address 3') ?>" name="billing[street][3]" id="billing:street3" class="input-text" value="<?php echo $streetValues[3]; ?>" autocomplete="off"/>
                    </div>
                    <p>Se Província/Cidade/Distrito estão corretos, deixe este campo em branco, se há divergência, registre o correto.</p>
                </li>
                
                <?php if ($this->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:vat_id" name="billing[vat_id]" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->getAttributeValidationClass('vat_id'); ?>" value="<?php echo $this->getDataFromSession('vat_id'); ?>" />
                        </div>
                    </li>
                <?php endif; ?>
                
                <li class="wide hidden">
                    <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect('billing') ?>
                    </div>
                </li>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                    <li class="control">
                        <label for="billing:save_in_address_book"><input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getDataFromSession('save_in_address_book')): ?> checked="checked"<?php endif; ?> class="checkbox" /><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else: ?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
            </ul>
        </li>    
        <?php if (!$this->isUseBillingAsShipping() && $this->canShip()): ?>
            <li class="control">
                <label for="billing:use_for_shipping"> <input type="checkbox" name="billing[use_for_shipping]" value="1" title="<?php echo $this->__('Ship to same address') ?>" id="billing:use_for_shipping" <?php if ($this->isUseBillingAsShippingChecked()): ?> checked="checked"<?php endif; ?> class="checkbox" /><?php echo $this->__('Ship to same address') ?></label>
            </li>
        <?php else : ?>
            <li class="no-display"><input type="hidden" name="billing[use_for_shipping]" value="1" /></li>
        <?php endif; ?>
    </ul>
    <?php echo $this->getChildHtml('extra'); ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    // var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    <?php if (!$this->isCustomerLoggedIn()) : ?>
        $$("[name*=billing[radio_tipopessoa]]").invoke('on', 'click',function(){
            var sel = $('billing:tipopessoa');
            setTipopessoaArea(this.value);
            for(var i=0; i<sel.options.length; i++){
                if(sel.options[i].text == this.value){
                    sel.options[i].selected=true;
                }
            }
            
        });
        function setTipopessoaArea(arg){
            if(arg=='Jurídica') {
                if ($('billing:taxvat')) {
                    $$('label[for="billing:taxvat"]').first().update('<em>*</em>CNPJ');
                    $('billing:taxvat').maxLength=18;
                    $$('label[for="billing:firstname"]').first().update('<em>*</em>Razão social');
                    $$('label[for="billing:lastname"]').first().update('<em>*</em>Nome Fantansia');
                    $('osc-billing-tipopessoa-area').hide();
                }
            }else{
                if ($('billing:taxvat')) {
                    $('billing:taxvat').maxLength=14;
                    $$('label[for="billing:taxvat"]').first().update('<em>*</em>CPF');
                    $$('label[for="billing:taxvat"]').first().update('<em>*</em>CPF');
                    $$('label[for="billing:firstname"]').first().update('<em>*</em>Nome');
                    $$('label[for="billing:lastname"]').first().update('<em>*</em>Sobrenome');
                    $('osc-billing-tipopessoa-area').show();
                }
            }
        }
        <?php if (is_null($this->getDataFromSession('radio_tipopessoa'))): ?>
            $$('[name*=billing[radio_tipopessoa]]')[0].click();
        <?php else: ?>
            if ($('billing:tipopessoa')) {
                setTipopessoaArea('<?php echo $this->getDataFromSession('radio_tipopessoa') ?>');
            }
        <?php endif; ?>
    Validation.add('validate-email-exist', '<?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?>', function(value) {
        if (checkMail(value)) {
            var ok = false;
            var url = '/onestepcheckout/ajax/check_email/';
            new Ajax.Request(url, {
                method: 'post',
                asynchronous: false,
                parameters: 'email=' + encodeURIComponent(value),
                onSuccess: function(transport) {
                    var obj = response = eval('(' + transport.responseText + ')');
                    validateTrueEmailMsg = obj.status_desc;
                        if (obj.result !== 'clean') {
                            Validation.get('validate-email-exist').error = 'Email já cadastrado';
                                ok = false;
                        } else {
                                ok = true;
                        }
                    },
                    onComplete: function() {
                        if ($('advice-validate-email-exist-billing:email')) {
                          $('advice-validate-email-exist-billing:email').remove();
                        }
                    }
                });
            return ok;
        }else{
            Validation.get('validate-email').error = '<?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?>';
        }
    });
    Validation.add('validate-taxvat', '<?php echo $this->__('This is a required field.') ?>', function(value) {
        if (validaCPF(value,0)) {
            var ok = false;
            var url = '/onestepcheckout/ajax/check_taxvat/';
            new Ajax.Request(url, {
                method: 'post',
                asynchronous: false,
                parameters: 'taxvat=' + encodeURIComponent(value),
                onSuccess: function(transport) {
                    var obj = response = eval('(' + transport.responseText + ')');
                    validateTrueEmailMsg = obj.status_desc;
                    if (obj.result !== 'clean') {
                        Validation.get('validate-taxvat').error = 'CPF/CNPJ já cadastrado';
                            ok = false;
                    } else {
                            ok = true;
                    }
                },
                onComplete: function() {
                    if ($('advice-validate-taxvat-billing:taxvat')) {
                        $('advice-validate-taxvat-billing:taxvat').remove();
                    }
                }
            });
            return ok;
         }else{
                 Validation.get('validate-taxvat').error = 'O CPF/CNPJ informado \xE9 inválido';
         }
    });
    <?php endif; ?>    
    if ($('billing:taxvat')) {
        $('billing:taxvat').addClassName('validate-taxvat');
        $('billing:taxvat').observe('keypress', function(event) {
            mascara(this, mdocumento);
        });
    }
    if ($('billing:day')) {
        $('billing:day').observe('keypress', function(event) {
            this.maxLength = 2;
            mascara(this, sonumeros);
        });
        $('billing:month').observe('keypress', function(event) {
            this.maxLength = 2;
            mascara(this, sonumeros);
        });
        $('billing:year').observe('keypress', function(event) {
            this.maxLength = 4;
            mascara(this, sonumeros);

        });
    }
    //]]>

    jQuery(function(){
        jQuery('#open-onestepcheckout-authentification').click(function(){
            jQuery('.onestepcheckout-authentification-overlay,#onestepcheckout-authentification').show();
            return false;
        });
    });
                    
</script>
