<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE.txt
 *
 * @category   Magpleasure
 * @package    Magpleasure_Adminlogger
 * @copyright  Copyright (c) 2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE.txt
 */
?>
<?php if ($this->getDetails()->getSize()): ?>
    <table class="data">
        <thead>
            <tr class="headings">
                <th><span class="nobr"><?php echo $this->__('Attribute Code') ?></span></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->getDetails() as $detail): ?>
            <tr>
                <td><span><?php echo $this->escapeHtml($detail->getAttributeCode()); ?></span></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>