<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE.txt
 *
 * @category   Magpleasure
 * @package    Magpleasure_Adminlogger
 * @copyright  Copyright (c) 2012 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE.txt
 */
?>
<div class="mp-al-summary">
    <ul>
        <li><strong><?php echo $this->__("Section: "); ?></strong><?php echo $this->getSectionName(); ?></li>
    </ul>
</div>
<?php if (count($this->getSectionDetails())): ?>
<table class="data">
    <thead>
        <tr class="headings">
            <th><span class="nobr"><?php echo $this->__('Config Path') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('From') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('To') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->getSectionDetails() as $detail): ?>
        <?php $htmlEscape = !$detail->getDiffRequired(); ?>
        <tr>
            <td><span><?php echo $this->escapeHtml($detail->getAttributeCode()); ?></span></td>
            <td><span><?php echo $htmlEscape ? $this->escapeHtml($detail->getFrom()) : $detail->getFrom(true); ?></span></td>
            <td><span><?php echo $htmlEscape ? $this->escapeHtml($detail->getTo()) : $detail->getTo(true); ?></span></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>