<div class="footer">
    <div class="menu-inferior">
        <div class="formas-pagamento">
            <h5>Formas de pagamento</h5>
            <ul class="selo-seguro">
                <li>
                    <img alt="visa" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/visa.png'); ?>"/>
                </li>
                <li class="itemRight">
                    <img alt="amex" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/amex.png'); ?>"/>
                </li>
                <li>
                    <img alt="mastercard" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/mastercard.png'); ?>"/>
                </li>
                <li class="itemRight">
                    <img alt="boleto" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/boleto.png'); ?>"/>
                </li>
                <li>
                    <img alt="elo" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/elo.png'); ?>"/>
                </li>
                <li class="itemRight">
                    <img alt="paypal" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/paypal.png'); ?>">
                </li>
                <li>
                    <img alt="diners" src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/diners.png'); ?>"/>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="col-menu">
            <div class="menu-footer">
                <h4>Institucional <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
                <ul class="institucional">
                    <li><a href="<?php echo $this->getUrl('quemsomos') ?>" rel="nofollow">Quem Somos</a></li>
                    <li><a href="<?php echo $this->getUrl('institucional_localizacao') ?>">Localiza&ccedil;&atilde;o</a></li>
                </ul>
            </div>
            <div class="menu-footer">
                <h4>Políticas <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
                <ul class="politicas">
                    <li><a href="<?php echo $this->getUrl('politica_de_troca_devolucao_arrependimento') ?>">Pol&iacute;tica de Troca, Devolu&ccedil;&atilde;o e Arrependimento</a></li>
                    <li><a href="<?php echo $this->getUrl('politica_de_envio') ?>">Pol&iacute;tica de Envio</a></li>
                    <li><a href="<?php echo $this->getUrl('politica_de_pagamento') ?>">Pol&iacute;tica de Pagamento</a></li>
                    <li><a href="<?php echo $this->getUrl('politica_de_privacidade') ?>">Pol&iacute;tica de Privacidade</a></li>
                    <li><a href="<?php echo $this->getUrl('politica_de_seguranca') ?>">Pol&iacute;tica de Seguran&ccedil;a</a></li>
                </ul>
            </div>
            <div class="menu-footer">
                <h4>Navegaçao <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
                <ul class="navegacao">
                    <li><a href="<?php echo $this->getUrl('catalog/seo_sitemap/category') ?>">Mapa do site</a></li>
                </ul>
            </div>
            <div class="menu-footer">
                <h4>Redes Sociais <i class="icon-font icon-ic_more_horiz_black_24px"></i></h4>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('redes-mobile')->toHtml(); ?>
            </div>
        </div>
    </div>
</div>
<div id="footer-store-info">
    <div class="store-contact">
        <p><i class="icon-font icon-ic_mail_black_24px"></i> <a href="mailto:sac@farmadelivery.com.br">sac@farmadelivery.com.br</a></p>
        <p><i class="icon-font icon-ic_local_phone_black"></i> Televendas: (11) 4972-8277</p>
        <p><i class="icon-font icon-ic_local_phone_black"></i> Whatsapp: (11) 99333-0810</p>
        <p><i class="icon-font icon-ic_shopping_cart_black_24px"></i> <a href="<?php echo Mage::getUrl('customer/account/') ?>"><?php echo $this->__('My Orders') ?></a></p>
        <p><i class="icon-font icon-ic_home_black_24px"></i> <a href="<?php echo Mage::getUrl('sales/order/history/') ?>"><?php echo $this->__('Registered Customers') ?></a></p>
    </div>

    <div class="seguranca">
        <ul>
            <li><a onclick="javascript:window.open('https://www.paypal.com/br/cgi-bin/webscr?cmd=xpt/Marketing/popup/OLCWhatIsPayPal-outside','olcwhatispaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=400, height=350');" href="#"><img src="<?php echo $this->getSkinUrl('images/compraSeguraPayPal.png'); ?>" alt="" /></a></li>
            <li><a href="https://www.ebit.com.br/farma-delivery" target="_blank"><img style="width:90px;" src="<?php echo $this->getSkinUrl('images/medalha_ouro_otima.png'); ?>" alt="" /></a></li>
            <li><a href="https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.farmadelivery.com.br%2F"><img style="width: 150px;" src="<?php echo $this->getSkinUrl('images/feedback_logo.png'); ?>" alt="" /></a></li>
            <li><a href="https://www.feedbackcompany.com/nl-nl/reviews/farmadelivery" target="_blank"><img style="width: 150px;" src="<?php echo $this->getSkinUrl('images/selo_google_sb.png'); ?>" alt="" /></a></li>
        </ul>
    </div>

    <div class="selo-interno">
        <dl>
            <dd class="selosonestic" style="margin-bottom:10px;">
                <a href="https://onestic.com/" title="Onestic - Lojas Virtuais para E-commerce" rel="external">
                    <img src="<?php echo $this->getSkinUrl('images/poweredby.png') ?>" alt="Onestic - Lojas Virtuais para E-commerce" title="Onestic - Lojas Virtuais para E-commerce" />
                </a><br />
            </dd>
        </dl>
    </div>

    <div class="copyright">
        <p>© Copyright 2018 - Solufarma - Todos os Direitos Reservados.</p>
    </div>
</div>
<?php echo $this->getChildHtml('track-scripts'); ?>