<?php
$isenabled = Mage::getStoreConfig('edrone/base/enable');
if (!$isenabled) {
    return;
}
/* @var $this Edrone_Base_Block_Product */
$helper = $this->getConfigHelper();
$helper2 =  Mage::helper('edrone');
$productData = $this->getProductData();
?>

<script type="text/javascript">
    (function (srcjs) {
        window._edrone = window._edrone || {};
        _edrone.app_id = '<?php echo $helper->getAppId() ?>';
        _edrone.version = '1.1.37';
        _edrone.platform = 'magento';
        _edrone.product_skus = '<?php echo urlencode($productData['sku']) ?>';
        _edrone.product_titles = '<?php echo urlencode($productData['title']); ?>';
        _edrone.product_images = '<?php echo urlencode($productData['image']); ?>';
        _edrone.product_urls   = '<?php echo urlencode($productData['product_url']); ?>';
        _edrone.product_category_ids = '<?php echo urlencode($productData['product_category_ids']); ?>';
        _edrone.product_category_names = '<?php echo urlencode($productData['product_category_names']); ?>';
        _edrone.action_type = 'product_view';
        _edrone.utc_time = '<?php echo $helper2->utcNow() ?>';

        var doc = document.createElement('script');
        doc.type = 'text/javascript';
        doc.async = true;
        doc.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + srcjs;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(doc, s);

        window.isBasketForm = function (find, txt) {
            if (typeof txt === 'string' || txt instanceof String) {
                txt = txt.split("?")[0];
            } else {
                return false;
            }
            return txt.substr(txt.length - find.length) == find;
        };

        (function() {
            var origOpen = XMLHttpRequest.prototype.open;
            XMLHttpRequest.prototype.open = function() {
            this.addEventListener('load', function() {
                if (isBasketForm('ajaxcart/cart/add/', this.responseURL)) {
                    _edrone.action_type = "add_to_cart";
                    _edrone.init();
                }
            });
            origOpen.apply(this, arguments);
            };
        })();


    })("<?php echo $helper->getExternalScriptUrl() ?>");
    !(function(){
      window._edrone = window._edrone || {};
      window._edrone_send_handler = function() {
        _edrone.first_run = false;
        var request = new XMLHttpRequest();
        request.open('GET', window.location.origin + '/edrone/user/sessionData', true);
        request.onreadystatechange = function() {
          if (this.readyState === 4) {
            if (this.status >= 200 && this.status < 400) {
              var customer = JSON.parse(this.responseText);
              window._edrone.email = customer.email;
              window._edrone.first_name = customer.first_name;
              window._edrone.last_name = customer.last_name;
              window._edrone.phone = customer.phone;
              window._edrone.city = customer.city;
              window._edrone.country = customer.country;
              window._edrone.subscriber_status = customer.subscriber_status;
              window._edrone.init();
            }
          }
        };
        request.send();
        request = null;
      }
    })();
</script>
