<?php
$isenabled = Mage::getStoreConfig('edrone/base/enable');
if (!$isenabled) {
    return;
}
/* @var $this Edrone_Base_Block_Order */
$helper = $this->getConfigHelper();
$helper2 =  Mage::helper('edrone');
$customerData = $this->getCustomerData();
$orderData = $this->getOrderData();
$this->sendDataToServer($orderData, $customerData);
?>

<?php if(!empty($orderData)): ?>
    <script type="text/javascript">
        (function (srcjs) {
            window._edrone = window._edrone || {};
            _edrone.app_id = '<?php echo $helper->getAppId() ?>';
            _edrone.version = '1.1.28';
            _edrone.platform = 'Magento';
            _edrone.platform_version = '<?php echo Mage::getVersion(); ?>';
            _edrone.trace_url = '<?php echo $helper->getCollectorUrl() ?>';
            _edrone.is_logged_in = '<?php echo $customerData['is_logged_in'] ?>';
            _edrone.email = '<?php echo $customerData['email'] ?>';
            _edrone.phone = '<?php echo $customerData['phone'] ?>';
            _edrone.first_name = '<?php echo urlencode($customerData['first_name']); ?>';
            _edrone.last_name = '<?php echo urlencode($customerData['last_name']); ?>';
            _edrone.product_skus = '<?php echo $orderData['sku'] ?>';
            _edrone.product_ids = '';
            _edrone.product_titles = '<?php echo urlencode($orderData['title']); ?>';
            _edrone.product_images = '<?php echo urlencode($orderData['image']); ?>';
            _edrone.product_category_ids = '<?php echo $orderData['product_category_ids'] ?>';
            _edrone.product_category_names = '<?php echo urlencode($orderData['product_category_names']); ?>';
            _edrone.order_id = '<?php echo $orderData['order_id'] ?>';
            _edrone.order_payment_value = '<?php echo $orderData['order_payment_value'] ?>';
            _edrone.base_payment_value = '<?php echo $orderData['base_payment_value'] ?>';
            _edrone.base_currency = '<?php echo $orderData['base_currency'] ?>';
            _edrone.order_currency = '<?php echo $orderData['order_currency'] ?>';
            _edrone.coupon = '<?php echo $orderData['coupon'] ?>';
            _edrone.action_type = 'order';
            _edrone.country = '<?php echo $customerData['country'] ?>';
            _edrone.city = '<?php echo urlencode($customerData['city']); ?>';
            _edrone.subscriber_status = '<?php echo $customerData['subscriber_status'] ?>';
            _edrone.utc_time = '<?php echo $helper2->utcNow() ?>';
            _edrone.product_counts = '<?php echo $orderData['product_counts']?>';


            var doc = document.createElement('script');
            doc.type = 'text/javascript';
            doc.async = true;
            doc.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + srcjs;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(doc, s);

        })("<?php echo $helper->getExternalScriptUrl() ?>");
    </script>
<?php endif; ?>