<div class="header-container bauer">
    <div class="header">
        <div class="linha-1">
            <div class="linha-1-interna">
            <?/*php echo $this->getChildHtml('topLinks') */?>
            <?php echo $this->getChildHtml('logo') ?>
            <div class="acesso-rapido">
                <div class="link-acesso">
                    <span class="saudacao">Seja Bem-vindo </span><span>Fa&ccedil;a seu </span><a href="/customer/account/login">login </a><span>ou </span><a href="/customer/account/">Cadastre-se</a>
                </div>
                <div class="botao-carrinho">
                    <?php echo $this->getChildHtml('mini_cart_top') ?>
                </div>
                <div class="botao-pedidos">
                    <a href="/"><img alt="" src="<?php echo $this->getSkinUrl('images/bt_pedidos.png') ?>"/></a>
                </div>
            </div>
            </div>
        </div>
        <div class="linha-2">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
        <div class="linha-3">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
    </div>
</div>
<div class="banner-home">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-sub-menu')->toHtml(); ?>
</div>
<div class="toggle-genericos">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('farma-genericos')->toHtml(); ?>
</div>