<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <table>
        <tbody>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <tr>
                <th><?php echo $this->escapeHtml($_label)?>:</th>
            </tr>
            <tr>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif;?>