<?php 
$pbms = $this->getPbm();
?>
<?php if ($pbms): ?>
<div class="block block-smartpbm-check" style="clear: both">
	<div class="block-title">
		<strong>Verifique seu Desconto</strong>
	</div>
    <div class="block-content">
        <ul class="smartpbm-check-form" id="smartpbm-check-form">
            <?php if (count($pbms) == 1): ?>
            <input type="hidden" name="pbm" id="smartpbm_pbm" value="<?php echo $pbms[0]; ?>" />
            <?php else: ?>
            <li class="item">
                <div class="input-box">
                    <label for="smartpbm_pbm" class="pbm_label">Selecione seu Programa</label>
                    <span class="input-text-right">
                    	<select id="smartpbm_pbm" name="pbm" <?php if($this->hasVidalink()): ?>onchange="checkConvenios(this.value);"<?php endif; ?>>
            <?php 
                foreach ($pbms as $pbm):
                    $pbmName = Mage::getModel('smartpbm/pbms_' . $pbm)->getName();
            ?>
                            <option value="<?php echo $pbm; ?>"><?php echo $pbmName; ?></option>
            <?php endforeach; ?>
                        </select>
                    </span>
                </div>
            </li>
            <?php endif; ?>
            <li class="item">
                <div class="input-box">
                	<label for="smartpbm_profissional" id="profissional_label">Nome do Médico</label>
                    <span class="input-text-right">
                    	<input class="input-text" type="text" id="smartpbm_profissional" name="profissional" placeholder="Nome do Médico" />
                    </span>
                </div>
            </li>     
            <li class="item">
                <div class="input-box">
                	<label for="smartpbm_crm" id="cpf_label">Número do CRM</label>
                    <span class="input-text-right">
                    	<input class="input-text" type="text" id="smartpbm_crm" name="crm" placeholder="Número do CRM" />
                    </span>
                </div>
            </li>     
            <li class="item">
                <div class="input-box">
                	<label for="smartpbm_uf" id="uf_label">Estado</label>
                    <span class="input-text-right">
                    	<select id="smartpbm_uf" name="uf">
                    	   <option value=''>Selecione...</option>
                    	   <option value='AC'>AC</option>
                    	   <option value='AL'>AL</option>
                    	   <option value='AM'>AM</option>
                    	   <option value='AP'>AP</option>
                    	   <option value='BA'>BA</option>
                    	   <option value='CE'>CE</option>
                    	   <option value='DF'>DF</option>
                    	   <option value='ES'>ES</option>
                    	   <option value='GO'>GO</option>
                    	   <option value='MA'>MA</option>
                    	   <option value='MG'>MG</option>
                    	   <option value='MS'>MS</option>
                    	   <option value='MT'>MT</option>
                    	   <option value='PA'>PA</option>
                    	   <option value='PB'>PB</option>
                    	   <option value='PE'>PE</option>
                    	   <option value='PI'>PI</option>
                    	   <option value='PR'>PR</option>
                    	   <option value='RJ'>RJ</option>
                    	   <option value='RN'>RN</option>
                    	   <option value='RO'>RO</option>
                    	   <option value='RR'>RR</option>
                    	   <option value='RS'>RS</option>
                    	   <option value='SC'>SC</option>
                    	   <option value='SE'>SE</option>
                    	   <option value='SP'>SP</option>
                    	   <option value='TO'>TO</option>
                    	</select>
                    </span>
                </div>
            </li>     
            <?php if($this->hasVidalink()): ?>
            <li class="item" id="conv_container" style="display: none">
                <div class="input-box">
                    <label for="smartpbm_conv" class="conv_label">Selecione seu Convênio</label>
                    <span class="input-text-right">
                    	<select id="smartpbm_conv" name="conv" onchange="changeConv(this.value);">
                    	   <option value="">Selecione...</option>
            <?php 
                $jsConvs = "";
                foreach ($this->getConvenios() as $convenio):
                    if ($jsConvs) $jsConvs .= ', ';
                    $jsConvs .= $convenio->cod_convenio . ":{label:'" . strtolower(str_replace('Nº do ', '', utf8_decode($convenio->titulo_cartao))) . "', max:" . $convenio->qtd_digitos_cartao . "}";
            ?>
                           <option value="<?php echo $convenio->cod_convenio; ?>"><?php echo $convenio->nome_convenio; ?></option>
            <?php endforeach; ?>
                        </select>
                    </span>
                </div>
            </li>
            <script type="text/javascript">
            var convenios = {<?php echo $jsConvs; ?>};
            function changeConv(code) {
                $('smartpbm_card').setAttribute('maxlength', convenios[code].max);
                $('card_label').update('Informe o número do seu ' + convenios[code].label);
            }
            function checkConvenios(conv) {
                if(conv == 'vidalink') {
                    $('conv_container').show();
                } else {
                	$('conv_container').hide();
                	$('smartpbm_card').setAttribute('maxlength', 50);
                }
            } 
            </script>
            <?php endif; ?>
            <?php if($this->hasSevenpdv()): ?>
            <li class="item">
                <div class="input-box">
                	<label for="smartpbm_cpf" id="cpf_label">Informe o número do seu CPF</label>
                    <span class="input-text-right">
                    	<input class="input-text" type="text" id="smartpbm_cpf" name="cpf" placeholder="Número do CPF" />
                    </span>
                </div>
            </li>            
            <?php endif; ?>
            <li class="item">
                <div class="input-box">
                	<label for="smartpbm_card" id="card_label">Informe o número do seu cartão</label>
                    <span class="input-text-right">
                    	<input class="input-text" type="text" id="smartpbm_card" name="card" placeholder="Número do Cartão" />
                    </span>
                    <button type="button" title="Ativar" onclick="checkCard()" class="button"><span><span>Ativar</span></span></button>
                </div>
            </li>
        </ul>
        <script type="text/javascript">decorateList('shipping-estimation-form');</script>
        <div class="actions">
            <span class="please-wait f-left" id="smartpbm-loading-message" style="display:none;">
                Verificando seu desconto...
            </span>
        </div>
    </div>
</div>

<div id="smartpbm-check-results" style="display:none" align="center">
</div>



<script type="text/javascript">
//<![CDATA[
function checkCard()
{
    var checkUrl = '<?php echo $this->getCheckUrl();?>';
    var items = $$(['.smartpbm-check-form input',
                    '.smartpbm-check-form select',
                    '#product_addtocart_form input',
                    '#product_addtocart_form select']);

    var validationResult = true;

    // Check the valid input
    if (!items.map(Validation.validate).all()) {
        return;
    }

    var parameters = Form.serializeElements(items, true);
    $('smartpbm-loading-message').show();
    $('smartpbm-check-results').hide();
    new Ajax.Updater('smartpbm-check-results', checkUrl, {
        parameters: parameters,
        onComplete: function() {
            $('smartpbm-loading-message').hide();
            $('smartpbm-check-results').show();
        }
    });

}
//]]>
</script>
<?php endif;?>