<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
/** @var Amasty_Promo_Block_Items $this */
$products = $this->getItems();
$mode = $this->getModeName();
?>
<script type="text/javascript">
    Object.extend(Product.Config.prototype, {
        reloadOptionLabels: function(){},
        changeSelection: function(){},
        reloadPrice: function(){}
    });
</script>

<div id="ampromo-overlay" class="mode-<?php echo $mode ?>" <?php echo $mode == 'popup' ? 'style="display: none;"' : ''?>>
    <div id="ampromo-items" class="<?php echo $this->useCarousel() ? 'amcarousel' : '' ?>">
        <h4 class="title-ampromo-header">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('icone-brinde-carrinho')->toHtml(); ?>
            <?php echo $this->getPopupHeader()?>
        </h4>

        <a href="javascript:" class="close"></a>

        <?php echo $this->getOptionsJs() ?>
        <?php echo $this->getCalendarJs() ?>

        <a href="javascript:" class="ampromo-carousel-control prev" rel="prev">Previous slide</a>
        <div id="ampromo-carousel-wrapper">
            <div id="ampromo-carousel-content">
                <?php foreach ($products as $product): ?>
                    <div class="ampromo-slide">
                        <?php echo $this->renderItem($product) ?>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
        <a href="javascript:" class="ampromo-carousel-control next" rel="next">Next slide</a>
    </div>
</div>

<?php if ($mode == 'inline'): ?>
    <script type="text/javascript">
        var jQuery=jQuery.noConflict();
        if (jQuery('.ampromo-slide').length >= 5){
            ampromo_init();
            var slider=jQuery("#ampromo-carousel-content");
            slider.slick({
                initialSlide:1,
                slidesToShow:4,
                slidesToScroll:4,
                autoplay:true,
                infinite:true
            });
        }else{
            ampromo_init();
        } 
    </script>
<?php endif; ?>
