<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php $blockNumber = $this->getBlockNumber(); ?>
<?php $blockNumberClass = (!is_null($blockNumber)) ? "onestepcheckout-number-{$blockNumber}" : ""; ?>
<?php if(Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?><div class="step-title"><span class="number onestepcheckout-number <?php echo $blockNumberClass; ?>"><?php echo $blockNumber; ?></span><h2><?php echo $this->__('Payment Method'); ?></h2></div><?php endif; ?>
<div class="step a-item">
    <div id="onestepcheckout-payment-method" class="onestepcheckout-add-loader-into-this-block">
        <?php echo $this->getEnterpriseRewardHtml(); ?>
        <dl class="sp-methods" id="checkout-payment-method-load">
            <?php $methods = $this->getMethods(); ?>
            <?php $oneMethod = count($methods) <= 1; ?>
            <?php foreach ($methods as $_method): ?>
                <?php $_code = $_method->getCode(); ?>
                <dt id="paymentcontrol-<?php echo $_code ?>" rel="<?php echo $_code ?>">
                <?php if (!$oneMethod): ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?> class="radio" />
                <?php else: ?>
                    <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                    <?php $oneMethod = $_code; ?>
                <?php endif; ?>
                <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
                </dt>
                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                    <dd>
                        <?php echo $html; ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
        <div class="validation-advice" style="display: none;"></div>

        <div class="card-highlight">
            <p class="visa-card-highlight">
                <img src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/visa.png', array('_secure'=>true)) ?>"> <em>Até 3x sem juros</em>
            </p>
            <p class="advice-card-highlight">Pagando com Visa você tem até 3x sem juros*. *Parcela mínima 50,00.</p>
            <div class="other-card-highlight">
                <img src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/mastercard.png', array('_secure'=>true)) ?>" />
                <img src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/elo.png', array('_secure'=>true)) ?>" />
                <img src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/diners.png', array('_secure'=>true)) ?>" />
                <img src="<?php echo $this->getSkinUrl('images/_cards/parcelamento/amex.png', array('_secure'=>true)) ?>" />
            </div>
        </div>

        <div id="segurancacartao">
            <div class="blindado">
                <!-- Selo Site Blindado - Todas as Paginas HTTPS -->
                <a href="https://selo.siteblindado.com.br/verificar?url=www.farmadelivery.com.br" title="Visualizou o selo site Blindado? Navegue tranquilamente, esse site está PROTEGIDO CONTRA HACKERS. Realizamos diariamente milhares de testes para garantir sua navegação segura. Clique no selo e confira nossa certificação." target="_blank"><img src="https://a248.e.akamai.net/f/248/76110/1h/selo.siteblindado.com.br/selos/www.farmadelivery.com.br/siteblindado_pr.gif " alt="Site Blindado" oncontextmenu="alert('Cópia Proibida por Lei - Site Blindado® é marca registrada da Site Blindado S.A.'); return false;" style="width:115px;height:32px;border:none;"/></a>
                <!-- Selo Site Blindado - Todas as Paginas HTTPS -->
            </div>
            <div class="ebit-cartao">
                <a onclick="redir(this.href);" target="_blank" href="https://www.ebit.com.br/farma-delivery" id="seloEbit" >
                    <img src="https://a248.e.akamai.net/f/248/52872/0s/img.ebit.com.br/ebitBR/selo/img_6449.png" />
                </a>
            </div>
            <div class="geotrust">
                <!--  GeoTrust QuickSSL [tm] Smart Icon tag. Do not edit. -->
                <img src="<?php echo $this->getSkinUrl('images/RapidSSL_SEAL-90x50.gif'); ?>" />
                <!-- end  GeoTrust Smart Icon tag -->
            </div>
            <div class="clearfix"></div>
        </div>

        <?php echo $this->getChildChildHtml('additional'); ?>
        <div class="tool-tip" id="payment-tool-tip" style="display:none;">
            <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
            <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
        </div>
        <script type="text/javascript">
            var OSCPayment = new OnestepcheckoutPayment({
                containerSelector: "#onestepcheckout-payment-method",
                wrapContainerSelector: "#onestepcheckout-payment-method-wrapper",
                switchMethodInputsSelector: "input[name='payment[method]']",
                enterpriseRewardsSelector: 'use_reward_points',
                methodAdditionalContainerIdPrefix: "payment_form_",
                cvv: {
                    tooltipSelector: "#payment-tool-tip",
                    closeElSelector: "#payment-tool-tip-close",
                    triggerElsSelector: ".cvv-what-is-this"
                },
                savePaymentUrl: <?php echo Zend_Json::encode($this->getSavePaymentUrl()); ?>
            });
        </script>
        <?php echo $this->getChildHtml('extra'); ?>
    </div>
</div>
