<script language="JavaScript">

    actualQty = 1;
    function addToQty( intQty )
    {
        actualQty += intQty;
        actualQty = (actualQty <= 1 ) ? 1 : actualQty;
        document.getElementById("qty").value=actualQty;
    }

</script>

<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <fieldset class="add-to-cart">
        <div class="add-to-box">
            <?php if (!$_product->isGrouped()): ?>
                <label for="qty">Qde.</label>
                <div class="input-cart">
                    <input type="text" class="input-text qty" name="qty" id="qty" maxlength="12" value="1" />
                    <i class="icon-font icon-ic_chevron_left_black_24px rotateUp" onclick="javascript:addToQty(1)"></i>
                    <i class="icon-font icon-ic_chevron_right_black_24px rotateDown" onclick="javascript:addToQty(-1)"></i>
                </div>
            <?php endif; ?>
            <button class="button button-cart" onclick="productAddToCartForm.submit()">
                <span><span><i class="icon-font icon-ic_shopping_cart_black_24px"></i> COMPRAR</span></span>
            </button>
        </div>
    </fieldset>
<?php endif; ?>