<?php if (Mage::getStoreConfig("easy_navigation/left/visibility")): ?>
<?php 
$type = Mage::getStoreConfig("easy_navigation/left/type"); 
$id = current(explode('.', 'left')) . '-nav';
?>
<div class="block">
    <div class="block-title">
        <img alt="" src="<?php echo $this->getSkinUrl('images/tit_departamentos.png') ?>"/>
    </div>
    <div class="block-content">
        <ul id="<?php echo $id ?>" class="easynavigation nav-<?php echo $type ?>">
        <?php foreach ($this->getStoreCategories() as $_category): ?>
            <?php echo $this->drawItem($_category) ?>
        <?php endforeach ?>
        </ul>
    </div>
</div>
<?php if ($type == 'accordionjs'): ?>
<script type="text/javascript">
new accordion('<?php echo $id ?>');
</script>
<?php endif ?>
<?php endif ?>