<script language="JavaScript">

    actualQty = 1;
    function addToQty( intQty )
    {
        actualQty += intQty;
        actualQty = (actualQty <= 1 ) ? 1 : actualQty;
        document.getElementById("qty").value=actualQty;
    }

</script>

<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <fieldset class="add-to-cart">
        <div class="add-to-box">
            <?php if (!$_product->isGrouped()): ?>
                <label for="qty">Qde.</label>
                <div class="input-cart">
                    <input type="button" value="-" id="minus1" class="minus" onclick="javascript:addToQty(-1)">
                    <input type="text" class="input-text qty" name="qty" id="qty" maxlength="12" value="1" />
                    <input type="button" value="+" id="add1" class="plus" onclick="javascript:addToQty(1)">
                </div>
            <?php endif; ?>
            <div class="actions">
                <button class="button button-cart loading" onclick="productAddToCartForm.submit()">
                    <span><span><i class="icon-font icon-ic_shopping_cart_black_24px"></i> COMPRAR</span></span>
                </button>
                <?php if($_product->getAssinatura1Meses()): ?>
                    <br>
                    <button type="button" title="Assinar" id="product-signtocart-button" class="button btn-cart btn-sign" onclick="openModalSignature();">
                        <span><span><i class="icon-font icon-ic_shopping_cart_black_24px"></i> ASSINAR</span></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>
    </fieldset>
<?php endif; ?>