<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<div class="bula_manual_description">
    <?php if($_product->getManual()!='') : ?>
        <div class="manual-description">
            <?php /*<h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> Manual</h2>*/ ?>
            <iframe src="https://docs.google.com/viewer?url=https://www.farmadelivery.com.br/media/upload/pdf/Manuais/<?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getManual()), 'manual')?>&amp;embedded=true" style="width:100%; height:300px;" frameborder="0"></iframe>
        </div>
    <?php endif;?>
</div>