<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Onestic
 * @package    Onestic_FreteProduto
 * @copyright  Copyright (c) 2017 Ecommerce Developer Blog (http://www.onestic.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Estimate shipping form
 *
 */
/* @var $this Onestic_FreteProduto_Block_Estimate_Form */
?>
<?php if ($this->isEnabled()): ?>
  <div class="block product-shipping-estimate text-center">
      Calcular frete e prazo de entrega
    <ul class="shipping-estimation-form" id="shipping-estimation-form">
      <input type="hidden" id="estimate_country" name="estimate[country_id]" value="<?php echo $this->htmlEscape($this->getConfig()->getDefaultCountry())?>" />
      <?php if ($this->isFieldVisible('postcode')): ?>
        <li class="item">
          <div class="form-inline">
            <label for="estimate_postcode" class="frete_label">
              <!-- <a class="nao-sei-cep" href="#" onclick="popWin('http://m.correios.com.br/movel/buscaCep.do', 'I forgot my zipcode', 'width=360,height=370,left=200,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><?php echo $this->__('Não sei meu cep') ?> -->
              </a>
            </label>
            <input class="input-text form-control validate-postcode" type="text" id="estimate_postcode" 
              name="estimate[postcode]" 
              value="<?php echo $this->htmlEscape($this->getFieldValue('postcode')) ?>" 
              placeholder="Informe seu CEP" onkeypress="javascript: formata_cep(this);" maxlength="8" minlength="8" />
            <button type="button" class="btn btn-estimate"
              title="<?php echo Mage::helper('onestic_freteproduto')->__('Get a Quote') ?>"
              onclick="estimateProductShipping()">
              <span>
                <span>
                  <?php echo Mage::helper('onestic_freteproduto')->__('Get a Quote') ?>
                </span>
              </span>
            </button>                            
          </div>
        </li>
      <?php endif; ?>
      <input id="estimate_cart_yes" type="hidden" name="estimate[cart]" value="1" />
    </ul>
    <div class="please-wait f-left" id="shipping-estimate-loading-message" style="display:none;">
      <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>">
      <?php echo Mage::helper('onestic_freteproduto')->__('Calculando Frete...') ?>
    </div>
  </div>

  <div id="shipping-estimate-results" style="display:none">
  </div>

  <script type="text/javascript">
    //<![CDATA[
    function estimateProductShipping()
    {
      var estimationUrl = '<?php echo $this->jsQuoteEscape($this->getEstimateUrl());?>';
      var items = $$(['.shipping-estimation-form input',
        '.shipping-estimation-form select',
        '#product_addtocart_form input',
        '#product_addtocart_form select']);

      var validationResult = true;

      // Check the valid input
      if (!items.map(Validation.validate).all()) {
        return;
      }

      var parameters = Form.serializeElements(items, true);
      $('shipping-estimate-loading-message').show();
      $('shipping-estimate-results').hide();
      new Ajax.Updater('shipping-estimate-results', estimationUrl, {
        parameters: parameters,
        onComplete: function() {
          $('shipping-estimate-loading-message').hide();
          $('shipping-estimate-results').show();
        }
      });
    }

    function formata_cep(obj){
      val = obj.value;
      val = val.replace(/\D/g,"");
      obj.value = val;
    }
    //]]>
  </script>
<?php endif;?>
