<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?><?php if ($this->getTotals()): ?>
    <tfoot>
    <?php $_colspan = (Mage::helper('onestepcheckout/config')->getIsCartEditable()?3:2); ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    </tfoot>
<?php endif; ?>
