<?php
/**
 * Novapc Integracommerce
 * 
 * @category     Novapc
 * @package      Novapc_Integracommerce
 * @copyright    Copyright (c) 2016 Novapc (http://www.novapc.com.br/)
 * @author       Novapc 
 * @version      Release: 1.0.0 
 */
?>
<?php 
    list($integraOrder, $mageCustomer, $mageOrder) = $this->viewOrder();

    $orderedItems = $mageOrder->getAllVisibleItems();

    $productIds = array();
    foreach ($orderedItems as $key => $item) {
        $productIds[] = $item->getId();
    }

    $productCollection = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('entity_id', array('in' => $productIds))
        ->addAttributeToSelect('*');
?>

<div class="content-header">
    <h3 class="icon-head head-sales-order">Visualização de Pedido</h3>
</div>


<div class="entry-edit" id="sales_order_view">
    <div id="sales_order_view_tabs_order_info_content">
        <div>
            <div id="order-messages"></div>
            <div class="box-left">
            <!--Order Information-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-account">Integracommerce</h4>
                    </div>
                    <div class="fieldset">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                Código
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value">
                                        <?php echo $this->escapeHtml($integraOrder->getIntegraId());?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Status"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value">
                                        <?php echo $this->escapeHtml($integraOrder->getOrderStatus());?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Loja"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value"><?php
                                        $storeName = $integraOrder->getStoreName();
                                        if (empty($storeName)) {
                                            echo $this->escapeHtml("");
                                        } else {
                                            echo $this->escapeHtml($integraOrder->getStoreName());
                                        }
                                    ?></td>
                                </tr>   
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Marketplace"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value"><?php
                                        $marketplaceName = $integraOrder->getMarketplaceName();
                                        if (empty($marketplaceName)) {
                                            echo $this->escapeHtml("");
                                        } else {
                                            echo $this->escapeHtml($integraOrder->getMarketplaceName());
                                        }
                                    ?></td>
                                </tr>  
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Frete"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value">
                                        <?php
                                        echo $this->escapeHtml(
                                            Mage::helper('core')->currency(
                                                $integraOrder->getTotalFreight(),
                                                true,
                                                false
                                            )
                                        );
                                        ?>
                                    </td>
                                </tr>   
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Grand Total"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value">
                                        <?php
                                        echo $this->escapeHtml(
                                            Mage::helper('core')->currency(
                                                $integraOrder->getTotalAmount(),
                                                true,
                                                false
                                            )
                                        );
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Transportadora"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value"><?php
                                        $shippedCarrierName = $integraOrder->getShippedCarrierName();
                                        if (empty($shippedCarrierName)) {
                                            echo $this->escapeHtml("");
                                        } else {
                                            echo $this->escapeHtml($integraOrder->getShippedCarrierName());
                                        }
                                    ?></td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("URL de Rastreio"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value"><?php
                                        $shippingTrakingUrl = $integraOrder->getShippingTrackingUrl();
                                        if (empty($shippingTrakingUrl)) {
                                            echo $this->escapeHtml("");
                                        } else {
                                            echo $this->escapeHtml($integraOrder->getShippingTrackingUrl());
                                        }
                                    ?></td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label>
                                            <strong>
                                                <?php echo $this->escapeHtml("Erros:"); ?>
                                            </strong>
                                        </label>
                                    </td>
                                    <td class="value">
                                        <textarea name="error" class="textarea" rows="2" cols="15"
                                                  style="width: 333px; height: 115px;" >
                                            <?php echo $this->escapeHtml($integraOrder->getIntegraError()); ?>
                                        </textarea>
                                    <td class="value">
                                </tr>
                             </tbody>
                         </table>
                    </div>
                </div>
            </div>
            <div class="box-right">
                <!--Account Information-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-account">
                            <?php echo $this->escapeHtml("Magento"); ?>
                        </h4>
                        <div class="tools"></div>
                    </div>
                    <div class="fieldset">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                    <tr>
                                        <td class="label">
                                            <label>
                                                <strong>
                                                    <?php echo $this->escapeHtml("Código"); ?>
                                                </strong>
                                            </label>
                                        </td>
                                        <td class="value">
                                            <?php echo $this->escapeHtml($mageOrder->getIncrementId());?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label>
                                                <strong>
                                                    <?php echo $this->escapeHtml("Cliente"); ?>
                                                </strong>
                                            </label>
                                        </td>
                                        <td class="value">
                                            <?php echo $this->escapeHtml($mageOrder->getCustomerFirstname()) .
                                                ' ' . $this->escapeHtml($mageOrder->getCustomerLastname());?>
                                        </td>
                                    </tr>   
                                    <tr>
                                        <td class="label">
                                            <label>
                                                <strong>
                                                    <?php echo $this->escapeHtml("E-mail"); ?>
                                                </strong>
                                            </label>
                                        </td>
                                        <td class="value">
                                            <?php echo $this->escapeHtml($mageOrder->getCustomerEmail());?>
                                        </td>
                                    </tr>                                        
                                    <tr>
                                        <td class="label">
                                            <label>
                                                <strong>
                                                    <?php echo $this->escapeHtml("Status"); ?>
                                                </strong>
                                            </label>
                                        </td>
                                        <td class="value">
                                            <?php echo $this->escapeHtml($mageOrder->getStatusLabel());?>
                                        </td>
                                    </tr>     
                                    <tr>
                                        <td class="label">
                                            <label>
                                                <strong>
                                                    <?php echo $this->escapeHtml("Produtos"); ?>
                                                </strong>
                                            </label>
                                        </td>
                                        <?php foreach ($productCollection as $key => $product): ?>
                                        <td class="value">
                                            <?php echo $this->escapeHtml($product->getName());?>
                                        </td>
                                        <?php endforeach; ?>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label>
                                                <strong>
                                                    <?php echo $this->escapeHtml("Erros"); ?>
                                                </strong>
                                            </label></td>
                                        <td class="value">
                                            <textarea name="error" class="textarea" rows="2" cols="15"
                                                      style="width: 333px; height: 115px;" >
                                                <?php echo $this->escapeHtml($integraOrder->getMageError()); ?>
                                            </textarea>
                                        <td class="value">
                                    </tr>
                                 </tbody>
                             </table>
                        </div>
                    </div>
                </div>
            </div>
<div class="clear"></div>
    </div>
</div>  
