<title><?php echo $this->getTitle() ?></title>
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="expires" content = "-1" />
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<!-- <meta http-equiv="X-UA-Compatible" content="IE=9" > -->
<!-- <meta http-equiv="pragma" content="no-cache" /> -->
<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
<?php
$actionName = $this->getAction()->getFullActionName();
//if product view
if($actionName == 'catalog_product_view') {
    $_product = Mage::registry('current_product');
    if ($_product) {
        $keyProduct = $_product->getUrlKey();
    }
    $currentLink = 'https://www.farmadelivery.com.br/'. $keyProduct;
    if ($currentLink) echo '<link rel="canonical" href="' . $currentLink . '" />';
}
?>
<link href="//fonts.googleapis.com/css?family=Dosis" rel="stylesheet" type="text/css">

<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
    var slidePrevText = '<?php echo $this->__('Previous') ?>';
    var slideNextText = '<?php echo $this->__('Next') ?>';
    var viewAll       = '<?php echo $this->__('View All') ?>';
//]]>
</script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script type="text/javascript">
    var $j = jQuery.noConflict(); 

    $j(document).ready(function(){
        $j("#test").css("padding","10px");
    });
</script>