<?php
$_order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
$total = $_order->getGrandTotal();
$total_data = $_order->getData();
$productsCart = '';
$productsCartIds = '';
$allItens = $_order->getAllItems();
$sizeOfItens = sizeof($allItens);
$indexItens = 1;
foreach ($allItens as $item) {
    $product_Sku = $item->getProduct()->getSku();
    $productsCartIds = $productsCartIds . $product_Sku;
    ?>

    <?php

    $currentCatIds = $item->getProduct()->getCategoryIds();
    $categoryCollection = Mage::getResourceModel('catalog/category_collection')
    ->addAttributeToSelect('name')
    ->addAttributeToSelect('url')
    ->addAttributeToFilter('entity_id', $currentCatIds)
    ->addIsActiveFilter();

    $categoriesNames = '';
    $sizeOfCategories = sizeof($categoryCollection);
    $indexCategories = 1;
    foreach($categoryCollection as $categorie){
      $categoriesNames = $categoriesNames . $categorie->getName();
      if ($indexCategories < $sizeOfCategories){
        $categoriesNames = $categoriesNames . ',';
    }
    $indexCategories++;
}


$productsCart = $productsCart . '{';
$productsCart = $productsCart . 'productId: "' . $item->getProduct()->getSku() . '",';
$productsCart = $productsCart . 'sku: "' . $item->getProduct()->getSku() . '",';
$productsCart = $productsCart . 'quantity: "' . $item->getQtyOrdered() . '",';
$productsCart = $productsCart . 'productName: "' . $item->getProduct()->getName() . '",';
$productsCart = $productsCart . 'name: "' . $item->getProduct()->getName() . '",';
$productsCart = $productsCart . 'productPrice: "' . number_format($item->getProduct()->getFinalPrice(), 2, '.', '') . '",';
$productsCart = $productsCart . 'price: "' . number_format($item->getProduct()->getFinalPrice(), 2, '.', '') . '",';
$productsCart = $productsCart . 'productDepartment: "",';
$productsCart = $productsCart . 'productCategory: "' .  $categoriesNames . '",';
$productsCart = $productsCart . 'category: "' .  $categoriesNames . '",';
$productsCart = $productsCart . 'productSubCategory: "",';
$productsCart = $productsCart . 'productBrand: "' . $item->getProduct()->getAttributeText('manufacturer') . '"';
$productsCart = $productsCart . '}'
?>

<?php
if ($indexItens < $sizeOfItens){
    $productsCart = $productsCart . ',';
    $productsCartIds = $productsCartIds . ',';
}
?>
<?php $indexItens++; ?>
<?php } ?>


<?php
$amount = number_format($_order->getGrandTotal(),2);
$shipping_number = preg_replace('/[^0-9]/', '', $total_data['shipping_description']);
$shipping_aux = $shipping_number + 2;
$shipping_estimate = date('Y-m-d', strtotime("+$shipping_aux days"));
$email = $_order->getCustomerEmail();
$dob = $_order->getCustomerDob();
$dob = explode(' ', $dob);
$dob2 = explode('-', $dob[0]);
$dobYear = $dob2[0];
$dobMonth = $dob2[1];
$dobDay = $dob2[2];
$aniversario = $dobDay.'-'.$dobMonth.'-'.$dobYear;
/*$primaryAddress = Mage::getSingleton('customer/session')->getCustomer()
->getPrimaryShippingAddress();
$zip = $primaryAddress->getPostcode();*/
/** PATCH CORREÇÃO DE ERRO PEGO PELO NEWRELIC **/
$zip = $_order->getShippingAddress()->getPostcode();
/** FIM PATCH **/
$shippingTax = number_format($_order->getShippingAmount(),2);
$total = $_order->getGrandTotal();
$_orderid = $_order->getIncrementId();
if (count($_order->getAllVisibleItems())>1){
    $items = $_order->getAllVisibleItems();
    $value = "";
    $qty = "";
    $name = "";
    $sku = "";
    $ean = "";
    foreach($items as $i):
      $value1 = $i->getPrice() - $i->getDiscountAmount();
  $value = $value.number_format($value1,2).'|';
  $qty = $qty.number_format($i['qty_ordered'],0).'|';
  $name = $name.str_replace('"', '',$i->getName()).'|';
  $sku = $sku.$i->getSku().'|';
  $ean = $ean.$i->getProduct()->getData('codigo_barras').'|';
  endforeach;
}else{
    $item = $_order->getAllVisibleItems();
    $value = $item[0]->getPrice() - $item[0]->getDiscountAmount();
    $value = number_format($value,2);
    $qty = number_format($item[0]['qty_ordered'],0);
    $name = str_replace('"', '',$item[0]->getName());
    $sku = $item[0]->getSku();
    $ean = $item[0]->getProduct()->getData('codigo_barras');
}
?>

<script type="text/javascript">
    var transactionProducts = [];

    transactionProducts.push(<?php echo $productsCart; ?>);

    dataLayer = [{
        pageName: "transaction",
        customerDOB: "<?php echo $aniversario; ?>",
        customerZip: "<?php echo $zip; ?>",
        clientEmail: "<?php if($email): ?><?php echo $email; ?><?php endif; ?>",
        deliveryTax: "<?php echo $shippingTax; ?>",
        deliveryEstimate: "<?php echo $shipping_estimate; ?>",
        totalSpent: "<?php echo $amount; ?>",
        productsValue: "<?php echo $value; ?>",
        productsQuantity: "<?php echo $qty; ?>",
        productsName: "<?php echo $name; ?>",
        productsSku: "<?php echo $sku; ?>",
        productsEan: "<?php echo $ean; ?>",
        transactionId: "<?php echo $this->getOrderId(); ?>",
        transactionAffiliation: "Bom Para Todos",
        transactionTotal: '<?php echo $total; ?>',
        transactionShipping: '<?php echo $_order->getShippingAmount(); ?>',
        orderAmount: '<?php echo $_order->getSubtotal(); ?>',
        orderAmount2: '<?php echo str_replace(".", "", number_format($_order->getSubtotal(), 2, '.', '')); ?>',
        customerId: '<?php echo $_order->getCustomerId(); ?>',
        transactionProductsIds: '<?php echo $productsCartIds; ?>',
        transactionProducts: transactionProducts,
        event: "isSuccess"
    }];
</script>