<?php $order = $this->getQuote()->getData();
$subtotal = $order['subtotal'];
$discount = $order['subtotal'] - $order['subtotal_with_discount'];
$total =$order['grand_total'];?>

<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('My Cart ') ?></h1>
        <div class="buttons-container">
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
                <?php //echo $this->getChildHtml('top_methods') ?>
            </ul>
            <?php endif; ?>
            <div class="clearfix"></div>
        </div>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" id="cart_form">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col width="1" />
                <col />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                <col width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            
            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    
    <div class="cart-collaterals">
        <!--div class="col-1">
            <?/*php echo $this->getChildHtml('crosssell') */?>
        </div-->
        <div class="cep">
            <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
        </div>
        <div class="coupon">
            <?php echo $this->getChildHtml('coupon') ?>
		    <strong class="desconto"><em>Add/Desc</em> <small><?=$this->helper('checkout')->formatPrice($discount); ?></small><span class="clearfix"></span></strong>
        </div>
    </div>
    
    <div class="valores">
		<strong class="total"><em>Valor total da compra</em> <small><?=$this->helper('checkout')->formatPrice($total); ?></small><span class="clearfix"></span></strong>
    </div>
    
    <div class="continuar-compra">
        <?php if ($this->getContinueShoppingUrl()): ?>
            <a onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?></span></a>
        <?php endif; ?>
        <a href="#" onclick="setLocation( '<?php echo $this->getUrl('emptyCart/index/index') ?>' )"><span><?php echo $this->__( 'Empty Shopping Cart' ) ?></span></a>
        <div class="clearfix"></div>
    </div>
    <div class="fechar-compra">
    	<?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
            <?php //echo $this->getChildHtml('methods') ?>
        </ul>
        <?php endif; ?>
    </div>
</div>
