<?php

if ($crumbs && is_array($crumbs)):
    $categories = $this->getCategories($this->getId());
?>
    <?php if (!empty($categories)): ?>
        <?php
        $category = Mage::getModel('catalog/category')->load($categories[0]);
        $background = $category->getData('promocategory_color_bg');
        $background2 = $category->getData('promocategory_color_bg2');
        ?>
        <div class="breadcrumbs" style="background:<?php echo $background; ?>;">
            <div class="promocategory-imgbreadcrumbs"><img src="<?php echo Mage::getBaseUrl() . 'media/catalog/category/' . $category->getData('promocategory_img_top'); ?>" height="30" /></div>
            <ul>
                <?php foreach ($crumbs as $_crumbName => $_crumbInfo): ?>
                    <li class="<?php echo $_crumbName ?>">
                        <?php if ($_crumbInfo['link']): ?>
                            <a href="<?php echo $_crumbInfo['link'] ?>"
                               title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>">
                               <?php  
                                    if(trim($this->htmlEscape($_crumbInfo['label'])) == 'Home' || trim($this->htmlEscape($_crumbInfo['label'])) == 'Início') {
                                        echo '<i class="icon-font icon-ic_home_black_24px"></i>';
                                    } else {
                                        echo $this->htmlEscape($_crumbInfo['label']);
                                    } 
                               ?>
                            </a> 
                        <?php elseif ($_crumbInfo['last']): ?> 
                            <strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong> 
                        <?php else: ?> 
                            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
                        <?php endif; ?> 
                        <?php if (!$_crumbInfo['last']): ?> <span>/ </span> <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php else: ?>
        <div class="breadcrumbs">
            <ul>
                <?php foreach ($crumbs as $_crumbName => $_crumbInfo): ?>
                    <li class="<?php echo $_crumbName ?>">
                        <?php if ($_crumbInfo['link']): ?>
                            <a href="<?php echo $_crumbInfo['link'] ?>"
                               title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>">
                               <?php  
                                    if(trim($this->htmlEscape($_crumbInfo['label'])) == 'Home' || trim($this->htmlEscape($_crumbInfo['label'])) == 'Início') {
                                        echo '<i class="icon-font icon-ic_home_black_24px"></i>';
                                    } else {
                                        echo $this->htmlEscape($_crumbInfo['label']);
                                    } 
                               ?>
                            </a> 
                        <?php elseif ($_crumbInfo['last']): ?> 
                            <strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong> 
                        <?php else: ?> 
                            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
                        <?php endif; ?> 
                        <?php if (!$_crumbInfo['last']): ?> <span>/ </span> <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endif; ?>
