<?php $product = Mage::registry('product'); ?>
<?php if(is_object($product)): ?>
    <?php $o_av = Mage::getModel('avisverifies/reviews'); ?>
    <?php $o_av->idProduct = $product->getId(); ?>
    <?php $o_av->skuProduct = $product->getSku(); ?>
    <?php $statsProduct = $o_av->getStatsProduct(); ?>
    <?php $countReviews = $statsProduct->getData('nb_reviews'); ?>
    <?php $getNote = $o_av->formatNote($statsProduct->getData('rate')); ?>
	<?php // either we have a link to the reviews page , or we have scroll to link?>
    <?php $href = (Mage::getStoreConfig('avisverifies/extra/add_review_to_product_page'))? "javascript:window.avisVerifies.scrollTo()" : $this->getReviewsUrl(TRUE); ?>
    <?php $_product = $this->getProduct(); ?>
    <?php $price = Mage::getModel('directory/currency')->format($_product->getFinalPrice(),array('display'=>Zend_Currency::NO_SYMBOL),false); ?>
	<?php if($countReviews): ?>
		<div itemscope itemtype="http://schema.org/Product">
            <meta itemprop="name" content="<?php echo $_product->getName(); ?>">
            <meta itemprop="description" content="<?php echo strip_tags($_product->getDescription()); ?>">
            <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <meta itemprop="priceCurrency" content="<?php echo  Mage::app()->getStore()->getCurrentCurrencyCode(); ?>">
                <meta itemprop="price" content="<?php echo str_replace( "," , ".", $price ); ?>">
            </div>
			<?php if(!Mage::getStoreConfig('avisverifies/extra/product_light_widget')): ?>
				<div id="av_product_award" itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating">
                <meta itemprop="ratingValue" content="<?php echo $getNote ?>">
                <meta itemprop="reviewCount" content="<?php echo $countReviews ?>">
					<div id="top">
						<div class="ratingWrapper">
							<div class="ratingInner" style="width:<?php echo ($getNote*20)."%" ?>;"></div>
						</div>
						<?php if($countReviews == 1): ?>
							<b><?php echo $this->__('%d Review', $countReviews) ?></b>
						<?php else: ?>
							<b><?php echo $this->__('%d Reviews', $countReviews) ?></b>
						<?php endif; ?>
					</div>
					<div id="bottom">
						<a href="<?php echo $href ?>" id="AV_button"><?php echo $this->__('See the review(s)')?></a>
					</div>
					<img id="sceau" src="<?php echo $this->getSkinUrl('images/avisverifies/Sceau_100'.Mage::app()->getLocale()->getLocaleCode().'.png') ?>" />
				</div>
			<?php else : ?>
				<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating">
					<meta itemprop="ratingValue" content="<?php echo $getNote ?>">
					<meta itemprop="reviewCount" content="<?php echo $countReviews ?>">
					<div class="rating-box">
						<div class="rating" style="width:<?php echo ($getNote*20)."%" ?>"></div>
					</div>
					<p class="rating-link">
						<a href="<?php echo $href ?>" id="AV_button">
							<?php if($countReviews == 1): ?>
								<?php echo $this->__('%d Review', $countReviews) ?>
							<?php else: ?>
								<?php echo $this->__('%d Reviews', $countReviews) ?>
							<?php endif; ?>
						</a>
					</p>
				</div>
			<?php endif; ?>
		</div>	
    <?php endif; ?>
<?php endif; ?>