<label for="<?php echo $this->getFieldId('month')?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?> style="width: 100%">
	<?php
        echo $this->__('Date of Birth') ?> <?php if (!$this->isRequired()) echo '(Opcional)' 
    ?>
</label>
<div class="row input-box customer-dob">
    <div class="col-sm-4 dob-day">
        <select name="<?php echo $this->getFieldName('day'); ?>" id="<?php echo $this->getFieldId('day'); ?>">
            <option value=""><?php echo $this->__('Dia'); ?></option>
            <?php for ($i = 1; $i <= 31; $i++): ?>
                <?php $day = (strlen($i) == 1) ? "0" . $i : $i; ?>
                <option value="<?php echo $day; ?>" <?php echo ($i==$this->getDay()) ? "selected" : ""; ?>>
                    <?php echo $day; ?>
                </option>
            <?php endfor; ?>
        </select>
        <label for="<?php echo $this->getFieldId('day'); ?>"><?php echo $this->__('Dia'); ?></label>
    </div>
    <div class="col-sm-4 dob-month">
        <select name="<?php echo $this->getFieldName('month'); ?>" 
            id="<?php echo $this->getFieldId('month'); ?>">
            <option value=""><?php echo $this->__('Mês'); ?></option>
            <?php for ($i = 1; $i <= 12; $i++): ?>
                <?php $month = (strlen($i) == 1) ? "0".$i : $i; ?>
                <option value="<?php echo $month; ?>" <?php echo ($i==$this->getMonth()) ? "selected" : ""; ?>>
                    <?php echo $month; ?>
                </option>
            <?php endfor; ?>
        </select>
        <label for="<?php echo $this->getFieldId('month'); ?>"><?php echo $this->__('Mês'); ?></label>
    </div>
    <div class="col-sm-4 dob-year">
        <?php $currentYear = intval(date("Y")); ?>
        <select name="<?php echo $this->getFieldName('year'); ?>" 
            id="<?php echo $this->getFieldId('year'); ?>">
            <option value=""><?php echo $this->__('Ano'); ?></option>
            <?php for ($i = $currentYear; $i >= $currentYear - 100; $i--): ?>
                <option value="<?php echo $i; ?>" <?php echo ($i==$this->getYear()) ? "selected" : ""; ?>>
                    <?php echo $i; ?>
                </option>
            <?php endfor; ?>
        </select>
        <label for="<?php echo $this->getFieldId('year'); ?>"><?php echo $this->__('Ano'); ?></label>
    </div>
    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div class="validation-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Onestic.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
