<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Islider
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>

<?php $helper = Mage::helper('awislider') ?>
<?php if($this->canDisplay() && $this->getSlides()->getSize()) : ?>
<div class="slider-container">
    <ul class="bx-slider-home">
        <?php $_i = 0 ?>
        <?php foreach($this->getSlides() as $slide) : ?>
        <li class="slider-item">
            <?php if($slide->getData('url')) : ?>
            <a href="<?php echo $helper->getUseDirectLinks() ? $slide->getData('url') : $this->getUrl('awislider/link/out', array('sid' => $slide->getData('id'))) ?>"<?php if($slide->getData('new_window')) : ?> target="_blank"<?php endif ?><?php if($slide->getData('nofollow')) : ?> rel="nofollow"<?php endif ?>>
            <?php endif ?>
                <div class="slider-background" style="background: transparent url('<?php echo ($slide->getUriLocation()) ?>') no-repeat center center; background-size: cover;"></div>
            <?php if($slide->getData('url')) : ?>
            </a>
            <?php endif ?>
        </li>
        <?php $_i++ ?>
        <?php endforeach ?>
    </ul>
    <div class="clearfix"></div>
</div>
<?php endif ?>
