<?php
/**
 * Product:     Advanced Permissions v2.3.11
 * Package:     Aitoc_Aitpermissions_2.3.11_2.0.3_370675
 * Purchase ID: O5ZL8CWb0tcKjILyP9IWZaAGWN8456REB9XZsTJqaT
 * Generated:   2012-09-27 17:36:51
 * File path:   app/design/frontend/default/default/template/aitpermissions/lfooter.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php
/**
 * @copyright  Copyright (c) 2009 AITOC, Inc. 
 */
?>
<!-- juxwnexavlwcxgmtutvxblvtbbgudjts -->