<h1>form</h1>


<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width: 50%;"><h3 class="icon-head head-sales-shipment"><?php echo $this->_headerText; ?></h3></td>
            <td class="form-buttons">
                <button onclick="addNewFileInput();" class="scalable" type="button" id="id_e02ab14980c62054dc3344b49e98bf18"><span>Adicionar Outro Arquivo</span></button>
                <button onclick="submitFiles();" class="scalable" type="button" id="id_e02ab14980c62054dc3344b49e98bf19"><span>Enviar Arquivo</span></button>
            </td>
        </tr>
    </tbody></table>
</div>
<style type="text/css">
label{
    width: 150px;
    display: block;
    border-bottom: 1px dashed #eee;
    float: left;
}
</style>
<form id="upload_form" enctype="multipart/form-data" action="<?php echo $this->getUrl('*/*/post'); ?>" method="post">
  <fieldset>
    <legend style="display: none">Upload</legend>
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div id="<?php echo $this->getHtmlId() ?>" class="uploader">
      <div id="<?php echo $this->getHtmlId() ?>-container">
      <label for="file_0">Arquivo 1</label><input type="file" name="fileupload[]" id="file_0" size="30" /><br/>
      </div>
    </div>
  </fieldset>
</form>

<script type="text/javascript">
//<![CDATA[
var upload_form     = new varienForm('upload_form');
var file_count      = 0;
var addNewFileInput = function()
{
    if (4 == file_count) {
        alert('Você pode enviar no máximo 5 arquivos por requisição.');
        return false;
    }

    ++file_count;
    var label = new Element('label', {'for': 'file_' + file_count}).update('Arquivo ' + (file_count + 1));
    var input = new Element('input', {type: 'file',id: 'file_' + file_count, name: 'fileupload[]', size:30});
    var br    = new Element('br');

    var div = $("<?php echo $this->getHtmlId() ?>-container");
    div.insert(label);
    div.insert(input);
    div.insert(br);

    $($('id_e02ab14980c62054dc3344b49e98bf19').childNodes[0]).update('Enviar Arquivos');
}
var submitFiles = function()
{
    $('loading-mask').show();
    upload_form.submit();
}

//]]>
</script>
