<div class="discount">
    <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
    <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
        <fieldset>
            <ul class="form-list">
                <li style="display: none;">
                    <input type="hidden" name="remove" id="remove-coupone" value="0" />
                </li>
                <?php if(!strlen($this->getCouponCode())): ?>
                    <li>
                        <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
                    </li>
                    </ul>
                    <button class="button button-cep" onclick="discountForm.submit(false)" type="button" value="<?php echo $this->__('Apply Coupon') ?>">
                        <span><span><?php echo $this->__('Use coupon') ?></span></span>
                    </button>
                <?php else: ?>
                    <li>
                        <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
                    </li>
                    </ul>
                    <button  type="button" class="button button-cancel" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>">
                        <span><span><?php echo $this->__('Cancel Coupon') ?></span></span>
                    </button>
                <?php endif;?>
        </fieldset>
    </form>
    <script type="text/javascript">
    //<![CDATA[
    var discountForm = new VarienForm('discount-coupon-form');
    discountForm.submit = function (isRemove) {
        if (isRemove) {
            $('coupon_code').removeClassName('required-entry');
            $('remove-coupone').value = "1";
        } else {
            $('coupon_code').addClassName('required-entry');
            $('remove-coupone').value = "0";
        }
        return VarienForm.prototype.submit.bind(discountForm)();
    }
    //]]>
    </script>
</div>