<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <p class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Mostrando <a style="display:none">%s</a> %s &iacute;tens de %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>
    
    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <?php if( $this->isEnabledViewSwitcher() ): ?>
		<p class="view-mode">
		    <?php $_modes = $this->getModes(); ?>
			<?php if($_modes && count($_modes)>1): ?>
			<?php foreach ($this->getModes() as $_code=>$_label): ?>
				<?php if($this->isModeActive($_code)): ?>
					<img src="<?php echo $this->getSkinUrl('images/icon_' . $_code . '_inactive.gif') ?>">
				<?php else: ?>
					<a href="<?php echo $this->getModeUrl($_code) ?>" ><img src="<?php echo $this->getSkinUrl('images/icon_' . $_code . '_active.gif') ?>"></a>&nbsp;
				<?php endif; ?>
			<?php endforeach; ?>
			<?php endif; ?>
		</p>    
		<?php endif; ?>
        <div class="sort-by">
            <label><?php echo $this->__('Sort by ') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $_order ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">
                    <i class="icon-font icon-ic_arrow_forward_black_24px ascending"></i>
                </a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">
                    <i class="icon-font icon-ic_arrow_forward_black_24px descending"></i>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
        <div class="pager">
    	<?php echo $this->getPagerHtml() ?>
        <div class="limiter">
            <label></label>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select> <?php echo $this->__('per page') ?>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<?php endif ?>