<div class="mais-procurados">
	<table>
		<tr>
			<td class="tit-procurados">
				<a href="/catalogsearch/term/popular"><img alt="mais procurados" src="<?php echo $this->getSkinUrl('images/mais_procurados.png')?>"/></a>
			</td>
		</tr>
		<tr>
			<td class="itens-procurados">
				<ul>
					<li><a href="http://www.farmadelivery.com.br/suplementos/sundownvitaminas" style="font-size:<?php echo rand(100, 200); ?>%;">Sundown Vitaminas </a></li>
					<li><a href="http://www.farmadelivery.com.br/meia-calca-anticelulite-sculptor-sigvaris" style="font-size:<?php echo rand(100, 200); ?>%;">Meia Sigvaris Anticelulite </a></li>
					<li><a href="http://www.farmadelivery.com.br/colchao-antiescaras-pneumatico-compressor-bio-air-salvape" style="font-size:<?php echo rand(100, 200); ?>%;">Colchão Antiescaras </a></li>
					<li><a href="http://www.farmadelivery.com.br/qiar-abridor-nasal-e-levantador-de-ponta-nasal" style="font-size:<?php echo rand(100, 200); ?>%;">Qiar </a></li>
					<li><a href="http://www.farmadelivery.com.br/cicatricure-creme-rugas-60g" style="font-size:<?php echo rand(100, 200); ?>%;">Cicatricure Rugas </a></li>
					<li><a href="http://www.farmadelivery.com.br/cicatricure-gel-cicatrizante-30g" style="font-size:<?php echo rand(100, 200); ?>%;">Cicatricure Cicatrizes </a></li>
					<li><a href="http://www.farmadelivery.com.br/goicoechea-creme-p-as-pernas-ultranutritivo-400g" style="font-size:<?php echo rand(100, 200); ?>%;">Goicoechea Ultranutritivo </a></li>
					<li><a href="http://www.farmadelivery.com.br/escova-dental-adulto-curaprox-sensitive-ultra-soft" style="font-size:<?php echo rand(100, 200); ?>%;">Escova Curaprox 5460 </a></li>
					<li><a href="http://www.farmadelivery.com.br/lipomax-c-60-capsulas-gratis-40-capsulas-de-d-modere" style="font-size:<?php echo rand(100, 200); ?>%;">Lipomax </a></li>
					<li><a href="http://www.farmadelivery.com.br/nutrilipo-com-colageno-600mg-c-60-capsulas" style="font-size:<?php echo rand(100, 200); ?>%;">Nutrilipo </a></li>
					<li><a href="http://www.farmadelivery.com.br/imedeen-radiant-complexion-c-60-comprimidos" style="font-size:<?php echo rand(100, 200); ?>%;">Imedeen Radiant </a></li>
					<li><a href="http://www.farmadelivery.com.br/accutrend-plus-aparelho-monitor" style="font-size:<?php echo rand(100, 200); ?>%;">Accutrend Plus </a></li>
					<li><a href="http://www.farmadelivery.com.br/coaguchek-xs-kit-monitor" style="font-size:<?php echo rand(100, 200); ?>%;">Coaguchek XS </a></li>
					<li><a href="http://www.farmadelivery.com.br/diabetes/accu-chek?cat=726" style="font-size:<?php echo rand(100, 200); ?>%;">Accu-Chek Performa </a></li>
					<li><a href="http://www.farmadelivery.com.br/diabetes/accu-chek?cat=721" style="font-size:<?php echo rand(100, 200); ?>%;">Accu-Chek Active </a></li>
					<li><a href="http://www.farmadelivery.com.br/fiber-mais-flora-nestle-nutrition-6-saches-fibra" style="font-size:<?php echo rand(100, 200); ?>%;">Fiber Mais Flora </a></li>
					<li><a href="http://www.farmadelivery.com.br/alfare-formula-infantil-com-ferro-para-lactentes-c-400g-sem-sacarose-sem-adic-o-de-lactose" style="font-size:<?php echo rand(100, 200); ?>%;">Alfaré </a></li>
					<li><a href="http://www.farmadelivery.com.br/modulen-ibd-400g-crohn-modulem" style="font-size:<?php echo rand(100, 200); ?>%;">Modulen </a></li>

					<li><a href="http://www.farmadelivery.com.br/diabetes/tiras-para-teste" style="font-size:<?php echo rand(100, 200); ?>%;">tiras para teste</a></li>
					<li><a href="http://www.farmadelivery.com.br/aparelhos-e-testes/aparelhos-de-pressao" style="font-size:<?php echo rand(100, 200); ?>%;">aparelho de pressao</a></li>
					<li><a href="http://www.accuchekdelivery.com.br/coaguchek-xs-kit-monitor-com-estojo-lancetador-softclix-20-lancetas-e-manual.html" style="font-size:<?php echo rand(100, 200); ?>%;">CoaguChek</a></li>
					<li><a href="http://www.farmadelivery.com.br/diabetes/accu-chek" style="font-size:<?php echo rand(100, 200); ?>%;">	accu chek</a></li>
					<li><a href="http://www.farmadelivery.com.br/diabetes/accu-chek" style="font-size:<?php echo rand(100, 200); ?>%;">accuchek</a></li>
					<li><a href="http://www.farmadelivery.com.br/viatop-am-gel-intimo-10g-viatop-am.html" style="font-size:<?php echo rand(100, 200); ?>%;">via top am</a></li>
					<li><a href="http://www.farmadelivery.com.br/catalogsearch/result/?q=tiras+glicemia&x=0&y=0" style="font-size:<?php echo rand(100, 200); ?>%;">tiras para medir glicemia</a></li>
					<li><a href="http://www.farmadelivery.com.br/catalogsearch/result/?q=tiras+glicemia&x=0&y=0" style="font-size:<?php echo rand(100, 200); ?>%;">TIRAS PARA MEDIR GLICOSE</a></li>

					<li><a href="http://www.farmadelivery.com.br/suplementos" style="font-size:<?php echo rand(100, 200); ?>%;">suplementos</a></li>
					<li><a href="http://www.farmadelivery.com.br/acessorios/dr-scholls" style="font-size:<?php echo rand(100, 200); ?>%;">dr scholls</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/monitor-cardiaco" style="font-size:<?php echo rand(100, 200); ?>%;">monitor cardiaco</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/monitor-cardiaco" style="font-size:<?php echo rand(100, 200); ?>%;">monitor cardiaco polar</a></li>
					<li><a href="http://www.accuchekdelivery.com.br/" style="font-size:<?php echo rand(100, 200); ?>%;">accu-chek</a></li>
					<li><a href="http://www.accuchekdelivery.com.br/" style="font-size:<?php echo rand(100, 200); ?>%;">tiras accu-chek</a></li>
					<li><a href="http://www.farmadelivery.com.br/aparelhos-e-testes/teste-de-gravidez" style="font-size:<?php echo rand(100, 200); ?>%;">teste de gravidez</a></li>
					<li><a href="http://www.farmadelivery.com.br/perfumaria/maquiagem-e-beleza" style="font-size:<?php echo rand(100, 200); ?>%;">maquiagem</a></li>
					<li><a href="http://www.farmadelivery.com.br/aparelhos-e-testes/aparelhos-de-pressao" style="font-size:<?php echo rand(100, 200); ?>%;">Aparelho de Pressão</a></li>
					<li><a href="http://www.farmadelivery.com.br/diabetes/aparelhos-para-glicemia" style="font-size:<?php echo rand(100, 200); ?>%;">Aparelho para glicemia</a></li>
					<li><a href="http://www.farmadelivery.com.br/asepxia-sabonete-natural-extra-secante-facial-e-corporal-c-85g-para-peles-com-imperfeicoes-causadas-por-cravos-e-espinhas-remove-a-oleosidade-desobstrui-os-poros.html" style="font-size:<?php echo rand(100, 200); ?>%;">Asepxia</a></li>
					<li><a href="http://www.farmadelivery.com.br/catalogsearch/result/?q=centrum" style="font-size:<?php echo rand(100, 200); ?>%;">centrum</a></li>
					<li><a href="http://www.farmadelivery.com.br/cicatricure-gel-hidratante-e-umectante-30g-formulado-para-hidratar-e-melhorar-a-pele-com-cicatrizes.html" style="font-size:<?php echo rand(100, 200); ?>%;">cicatricure</a></li>
					<li><a href="http://www.farmadelivery.com.br/perfumaria/higiene-bucal/escova-dental/" style="font-size:<?php echo rand(100, 200); ?>%;">escova dental</a></li>
					<li><a href="http://www.farmadelivery.com.br/eurofarma/" style="font-size:<?php echo rand(100, 200); ?>%;">eurofarma</a></li>
					<li><a href="http://www.farmadelivery.com.br/medley" style="font-size:<?php echo rand(100, 200); ?>%;">medley</a></li>
					<li><a href="http://www.farmadelivery.com.br/produtos-g-tech" style="font-size:<?php echo rand(100, 200); ?>%;">g-tech</a></li>
					<li><a href="http://www.farmadelivery.com.br/nestle" style="font-size:<?php echo rand(100, 200); ?>%;">nutrition</a></li>
					<li><a href="http://www.farmadelivery.com.br/bayer" style="font-size:<?php echo rand(100, 200); ?>%;">bayer</a></li>
					<li><a href="http://www.farmadelivery.com.br/germed" style="font-size:<?php echo rand(100, 200); ?>%;">germed</a></li>
					<li><a href="http://www.farmadelivery.com.br/mantecorp" style="font-size:<?php echo rand(100, 200); ?>%;">mantecorp</a></li>
					<li><a href="http://www.farmadelivery.com.br/germed" style="font-size:<?php echo rand(100, 200); ?>%;">germed</a></li>
					<li><a href="http://www.farmadelivery.com.br/pfizer" style="font-size:<?php echo rand(100, 200); ?>%;">pfizer</a></li>
					<li><a href="http://www.farmadelivery.com.br/roche" style="font-size:<?php echo rand(100, 200); ?>%;">roche</a></li>
					<li><a href="http://www.farmadelivery.com.br/lipomax-c-60-capsulas-nutrilipo-c-40-capsulas-gratis-controla-o-apetite-e-auxilia-na-reduc-o-da-absorc-o-de-gordura-e-colesterol.html" style="font-size:<?php echo rand(100, 200); ?>%;">lipomax</a></li>
					<li><a href="http://www.farmadelivery.com.br/hipoglos-pomada-45g-retinol-colecalciferol-oxido-de-zinco.html" style="font-size:<?php echo rand(100, 200); ?>%;">Hipoglós</a></li>
					<li><a href="http://www.farmadelivery.com.br/mucilon-frutas-sortidas-235ml.html" style="font-size:<?php echo rand(100, 200); ?>%;">Mucilon</a></li>
					<li><a href="http://www.farmadelivery.com.br/sonrisal-efervescente-2cpr.html" style="font-size:<?php echo rand(100, 200); ?>%;">sonrisal</a></li>
					<li><a href="http://www.farmadelivery.com.br/accu-chek-active-50-tiras-controle-dia-betes.html" style="font-size:<?php echo rand(100, 200); ?>%;">tiras accu-chek</a></li>
					<li><a href="http://www.farmadelivery.com.br/kit-pilexil-locao-capilar-125ml-pilexil-shampoo-150ml-pilexyl-pylexil.html" style="font-size:<?php echo rand(100, 200); ?>%;">pilexil</a></li>
					<li><a href="http://www.farmadelivery.com.br/derma-nail-base-fortalecedor-de-unhas-10ml-30ml-de-removedor-dermanail.html" style="font-size:<?php echo rand(100, 200); ?>%;">derma nail</a></li>
					<!-- -->
					<li><a href="http://www.farmadelivery.com.br/catalogsearch/result/?q=Nicorette&x=0&y=0" style="font-size:<?php echo rand(100, 200); ?>%;">Nicorette</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/respire-melhor" style="font-size:<?php echo rand(100, 200); ?>%;">respire melhor</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/respire-melhor" style="font-size:<?php echo rand(100, 200); ?>%;">dilatadores nasais</a></li>
					<li><a href="http://www.farmadelivery.com.br/medicamentos/genericos/genericos-merck" style="font-size:<?php echo rand(100, 200); ?>%;">Genéricos Merck</a></li>
					<li><a href="http://www.farmadelivery.com.br/aparelhos-e-testes/inaladores-e-nebulizadores" style="font-size:<?php echo rand(100, 200); ?>%;">nebulizadores</a></li>
					<li><a href="http://www.farmadelivery.com.br/catalogsearch/result/?q=Niquitin&x=20&y=10" style="font-size:<?php echo rand(100, 200); ?>%;">Niquitin</a></li>
					<li><a href="http://www.farmadelivery.com.br/medicamentos/pare-de-fumar" style="font-size:<?php echo rand(100, 200); ?>%;">pare de fumar</a></li>
					<li><a href="http://www.farmadelivery.com.br/medicamentos/pare-de-fumar" style="font-size:<?php echo rand(100, 200); ?>%;">como parar fumar</a></li>
					<li><a href="http://www.farmadelivery.com.br/medicamentos/pare-de-fumar" style="font-size:<?php echo rand(100, 200); ?>%;">deixar fumar</a></li>
					<li><a href="http://www.farmadelivery.com.br/aparelhos-e-testes/inaladores-e-nebulizadores" style="font-size:<?php echo rand(100, 200); ?>%;">inaladores</a></li>
					<li><a href="http://www.farmadelivery.com.br/suplementos/emagrecimento" style="font-size:<?php echo rand(100, 200); ?>%;">alimentos para dieta</a></li>
					<li><a href="http://www.farmadelivery.com.br/suplementos/emagrecimento" style="font-size:<?php echo rand(100, 200); ?>%;">alimentação para dieta</a></li>
					<li><a href="http://www.farmadelivery.com.br/suplementos/emagrecimento" style="font-size:<?php echo rand(100, 200); ?>%;">dieta emagrecimento</a></li>
					<li><a href="http://www.farmadelivery.com.br/suplementos/emagrecimento" style="font-size:<?php echo rand(100, 200); ?>%;">emagrecimento rápido</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/monitor-cardiaco" style="font-size:<?php echo rand(100, 200); ?>%;">monitor beurer</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/monitor-cardiaco" style="font-size:<?php echo rand(100, 200); ?>%;">monitor cardíaco beurer</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/monitor-cardiaco" style="font-size:<?php echo rand(100, 200); ?>%;">beurer monitor cardiaco</a></li>
					<li><a href="http://www.farmadelivery.com.br/infantil/chupetas-mamadeiras-e-mordedores/chupetas" style="font-size:<?php echo rand(100, 200); ?>%;">chupetas</a></li>
					<li><a href="http://www.farmadelivery.com.br/infantil/chupetas-mamadeiras-e-mordedores/mamadeiras" style="font-size:<?php echo rand(100, 200); ?>%;">mamadeiras</a></li>
					<li><a href="http://www.farmadelivery.com.br/infantil/chupetas-mamadeiras-e-mordedores/mordedores" style="font-size:<?php echo rand(100, 200); ?>%;">mordedores</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/pilates" style="font-size:<?php echo rand(100, 200); ?>%;">Bola Suiça</a></li>
					<li><a href="http://www.farmadelivery.com.br/fitness/monitor-cardiaco/monitor-cardiaco-de-pulso-preto-e-prata-pm25-beurer-monitora-o-volume-diario-de-exercicio-o-ritmo-cardiaco-medio-e-maximo-durante-o-periodo-alem-de-verificar-o-gasto-de-calorias-e-gorduras.html" style="font-size:<?php echo rand(100, 200); ?>%;">beurer pm25</a></li>
					<?/*
					$qtd_permitida = 70;
					$i = 0;
					?>
					<?php foreach ($this->getTerms() as $_term): ?>
					<?php if ($i < $qtd_permitida) { ?>
							<li><a href="<?php echo $this->getSearchUrl($_term) ?>" style="font-size:<?php echo $_term->getRatio() * 70 + 100 ?>%;"><?php echo $this->htmlEscape($_term->getName()) ?></a></li>
					<?php
							$i++;
						}?>
	<?php endforeach; */?>
				</ul>
			</td>
		</tr>
	</table>
</div>