<?php

/** @var Algolia_Algoliasearch_Helper_Config $config */
$config = Mage::helper('algoliasearch/config');

/** @var Mage_Customer_Model_Session $session */
$session = Mage::getSingleton('customer/session');
$customerGroupId = $session->getCustomerGroupId();

$storeId = Mage::app()->getStore()->getStoreId();
$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();

$priceKey = '.'.$currencyCode.'.default';
if ($config->isCustomerGroupsEnabled($storeId)) {
    $priceKey = '.'.$currencyCode.'.group_'.$customerGroupId;
}

?>

        <div class="col-md-4 col-sm-6">
            <div class="result-wrapper">
                <a href="{{url}}" class="result algolia-clearfix" data-objectid="{{objectID}}" data-position="{{__position}}" category-ids="{{category_ids}}" frete-gratis="{{frete_gratis_dropdown}}" pague-leve="{{pague_leve}}" before-special="{{price<?php echo $priceKey; ?>_original_formated}}" after-special="{{price<?php echo $priceKey; ?>_formated}}">
                    <div class="frete_gratis_icon page_leve" id="algolia_pague_leve" style="background-color:#fff;">{{pague_leve}}</div>
                    <div class="frete_gratis_icon" id="algolia_frete_gratis" style="background-color:#fff;">{{frete_gratis_dropdown}}</div>
                    <div class="desconto_icon" id="algolia_percent_discount" style="background-color:#fff;">0</div>
                    <div class="image-promotion" id="algolia_image_promotions">{{image_promotion}}</div>
                    <div class="result-content">
                        <div class="result-thumbnail">
                            {{#image_url}}<img src="{{{ image_url }}}"/>{{/image_url}}
                            {{^image_url}}<span class="no-image"></span>{{/image_url}}
                            <div class="image-promotion" id="algolia_image_promotions">{{image_promotion}}</div>
                        </div>
                        <div class="result-sub-content">
                            <h3 class="result-title text-ellipsis">
                                {{{ _highlightResult.name.value }}}
                            </h3>
                            <div class="product-sku" style="color: #868a8e; line-height: 1; padding-top: 4px;">SKU: {{sku}}</div>
                            <div class="ratings">
                                <div class="ratings-wrapper">
                                    <div class="ratings-sub-content">
                                        <div class="rating-box">
                                            <div class="rating" style="width:{{rating_summary}}%" width="148" height="148"></div>
                                        </div>
                                    </div>
                                    <div class="price">
                                        <div class="price-wrapper">
                                            <div>
                                                <span class="before_special">
                                                    {{price<?php echo $priceKey; ?>_original_formated}}
                                                </span>
                                                <span class="after_special {{#price<?php echo $priceKey; ?>_original_formated}}promotion{{/price<?php echo $priceKey; ?>_original_formated}}">
                                                    {{price<?php echo $priceKey; ?>_formated}}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="result-description text-ellipsis">{{{ _highlightResult.description.value }}}</div>
                            {{#isAddToCartEnabled}}
                                <button type="button" title="<?php echo $this->quoteEscape($this->__('COMPRAR')) ?>" class="button btn-cart"><span><span><?php echo $this->__('COMPRAR') ?></span></span></button>
                            {{/isAddToCartEnabled}}
                        </div>
                    </div>
                </a>
            </div>
        </div>