<!-- Google reCAPTCHA widget -->
<div id="<?php echo $this->getCaptchaId().'-'.rand(); ?>" class="g-recaptcha"
     data-sitekey="<?php echo $this->getSiteKey(); ?>"
     data-callback="av5RecaptchaCallback"
     style="display: none; <?php echo $this->getCaptchaCss(); ?>">
</div>
<script type="text/javascript">

    var av5RecaptchaCallback;
    var elWhere = "<?php echo $this->getLocationId(); ?>";//"div.privacy-policy";
    var elWhereType = "<?php echo $this->getLocationType(); ?>";
    var errorValidationStyle = "<?php echo $this->getValidationCss(); ?>";
    var errorValidationText = "<?php echo $this->__('This is a required field.'); ?>";

</script>
<?php if (!empty($this->getExtraStyle())) { ?>
<style>
    <?php echo $this->getExtraStyle(); ?>
</style>
<?php } ?>
<!-- end Google reCAPTCHA widget -->
