<?php

/**
 *
 * @category   Onestic
 * @package    Onestic_Checkout
 * @author     Suporte <suporte@onestic.com>
 */
?>
<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<?php if($this->getTitle()): ?>
  <div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
  </div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
  <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
    <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
    <ul class="form-list">        
      <li class="row fields">
        <?php //echo $this->getNameBlockHtml() ?>
        <?php echo $this->getLayout()->createBlock('onestic_checkout/widget_name')->setObject($this->getCustomer())->toHtml() ?>
      </li>

      <li class="row fields">
        <div class="field col-md-6">
          <label for="telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
          <div class="input-box">
            <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text validate-length minimum-length-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone"
                   onkeypress="formata_telefone(this);" onfocusout="formata_telefone(this);"/>
          </div>
        </div>
        <div class="field col-md-6">
          <label for="fax" class="required"><?php echo $this->__('Celular') ?><em>*</em>></label>
          <div class="input-box">
            <input type="text" name="fax" id="fax" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text validate-length minimum-length-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
              onkeypress="formata_telefone(this);" onfocusout="formata_telefone(this);" />
          </div>
        </div>
      </li>
    </ul>
  </div>
  <div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Address') ?></h2>
    <ul class="form-list">
      <li class="row fields">
        <div class="field col-md-6">
          <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
          <div class="input-box">
            <?php echo $this->getCountryHtmlSelect() ?>
          </div>
        </div>
        <div class="field col-md-6">
          <label for="postcode" class="required"><em>*</em>
            <?php echo $this->__('Zip/Postal Code') ?>
          </label>
          <div class="input-box">
            <input type="text" name="postcode" 
              value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" 
              title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" 
              id="postcode" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" maxlength="9" />
              <span id="load-end" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('onestic/checkout/images/opc-ajax-loader.gif');?>" />
              </span>
          </div>
          <a class="nao-sei-cep" href="#" 
            onclick="popWin('http://m.correios.com.br/movel/buscaCep.do', 'I forgot my zipcode', 'width=360,height=370,left=200,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;">
            <?php echo $this->__('What is my postcode?') ?>
          </a>
        </div>
      </li>

      <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
      <li class="row fields">
        <div class="field col-md-6">
          <label for="street_1" class="required"><em>*</em>
            <?php //echo $this->__('Street Address') ?>
            <?php echo $this->__('Rua') ?>
          </label>
          <div class="input-box">
            <input type="text" name="street[]" id="street_1" 
              value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" 
              title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
              class="input-text <?php echo $_streetValidationClass ?>" />
          </div>
        </div>
        <div class="field col-md-6">
          <label for="street_2" class="required">
            N&uacute;mero
          </label>
          <div class="input-box">
            <input type="text" name="street[]" id="street_2" 
              value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(2)) ?>" 
              title="Número" 
              class="input-text <?php echo $_streetValidationClass ?>" />
          </div>
        </div>
      </li>     

      <li class="row fields">
        <div class="field col-md-6">
          <label for="street_2">
            Complemento (Opcional)
          </label>
          <div class="input-box">
            <input type="text" name="street[]" id="street_3" 
              value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(3)) ?>" 
              title="Complemento" class="input-text" />
          </div>
        </div>

        <div class="field col-md-6">
          <label for="street_4" class="required">
            Bairro
          </label>
          <div class="input-box">
            <input type="text" name="street[]" id="street_4" 
              value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(4)) ?>" 
              title="Bairro"
              class="form-control <?php echo $_streetValidationClass ?>" />
          </div>
        </div>
      </li>
      
      <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
        <li class="wide">
          <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
          <div class="input-box">
            <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
          </div>
        </li>
      <?php endif; ?>

      <li class="row fields">
        <div class="field col-md-6">
          <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
          <div class="input-box">
            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
          </div>
        </div>
        <div class="field col-md-6">
          <label for="region_id" class="required"><em>*</em>
            <?php //echo $this->__('State/Province') ?>
            <?php echo $this->__('State') ?>
          </label>
          <div class="input-box">
            <select id="region_id" name="region_id" 
              title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
              class="validate-select">
              <option value="">
                <?php //echo $this->__('Please select region, state or province') ?>
                <?php echo $this->__('Por favor, selecione seu estado') ?>
              </option>
            </select>
            <script type="text/javascript">
            //<![CDATA[
              $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
            //]]>
            </script>
            <input type="text" id="region" name="region" 
              value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  
              title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" 
              class="input-text 
              <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
          </div>
        </div>
      </li>

      <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
        <?php if($this->isDefaultBilling()): ?>
          <strong><?php echo $this->__('Default Billing Address') ?></strong>
        <?php elseif($this->canSetAsDefaultBilling()): ?>
          <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
        <?php else: ?>
          <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>
      </li>
      <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
        <?php if($this->isDefaultShipping()): ?>
          <strong><?php echo $this->__('Default Shipping Address') ?></strong>
        <?php elseif($this->canSetAsDefaultShipping()): ?>
          <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
        <?php else: ?>
          <input type="hidden" name="default_shipping" value="1" />
        <?php endif; ?>
      </li>
    </ul>
  </div>
  <div class="buttons-set">
    <!-- <p class="required"><?php //echo $this->__('* Required Fields') ?></p> -->
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
  </div>
</form>
<script type="text/javascript">
//<![CDATA[
  var dataForm = new VarienForm('form-validate', true);
  new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');


  if ($('postcode')) {
    $('postcode').addClassName('validate-zip-br');
    $('postcode').observe('keypress', function() {
      formata_cep(this);
    });
    $('postcode').observe('blur', function() {
      buscar_end();
    });
  }

if ($('telephone')) {
    $('telephone').observe('keypress', function() {
        formata_telefone(this);
    });
    $('telephone').observe('onfocusout', function() {
        formata_telefone(this);
    });
}
if ($('fax')) {
    $('fax').observe('keypress', function() {
        formata_telefone(this);
    });
    $('fax').observe('onfocusout', function() {
        formata_telefone(this);
    });
}
//]]>
</script>

<script type="text/javascript">
  if(!BASE_URL) var BASE_URL = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
</script>
