<div class="shipping">
    <label class="rotulo-cep"><?php echo $this->__('Digite seu cep para calcular o valor do frete') ?></label>
    <form action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post" id="shipping-zip-form">
        <fieldset>
            <ul class="form-list">
                <li style="display:none;">
                    <label for="country"><?php echo $this->__('Country') ?></label><br />
                    <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
                </li>
	            <?php //if($this->getStateActive()): ?>
	                <li style="display:none;">
	                    <label for="region_id"><?php echo $this->__('State/Province') ?><?php if ($this->isStateProvinceRequired()):?> <span class="required">*</span><?php endif;?></label><br />
	                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
	                        <!--<option value=""><?php echo $this->__('Please select region, state or province') ?></option>-->
	                    </select>
	                   <script type="text/javascript">
	                   //<![CDATA[
	                   //]]>
	                   </script>
	                   <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getEstimateRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
	                </li>
	            <?php //endif; ?>
	            <?php if($this->getCityActive()): ?>
	                <li>
	                    <label for="city"><?php echo $this->__('City') ?><?php if ($this->isCityRequired()):?> <span class="required">*</span><?php endif;?></label><br />
	                    <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->htmlEscape($this->getEstimateCity()) ?>" />
	                </li>
	            <?php endif; ?>
                <li>
                    <!--label for="postcode"><?/*php echo $this->__('Zip/Postal Code') ?><?php if ($this->isZipCodeRequired()):?> <span class="required">*</span><?php endif;*/?></label><br /-->
                    <input class="input-text validate-digits<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?> validate-postcode" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->htmlEscape($this->getEstimatePostcode()) ?>" />
                </li>
            </ul>
            <button type="button" onclick="coShippingMethodForm.submit()" class="button-cep"><img alt="" src="<?php echo $this->getSkinUrl('images/bt_calcular_cep.png') ?>"/><!--span><?/*php echo $this->__('Get a Quote') */?></span--></button>
        </fieldset>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    //]]>
    </script>
</div>

<?php $order = $this->getQuote()->getData();
$shipping = $order['grand_total'] - $order['subtotal_with_discount'];?>
<!-- valor do frete -->
<strong class="frete"><em>Frete</em> <small><?=Mage::helper('core')->currency(($shipping),true,false) ?></small></strong>
<!-- valor do frete -->


<?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
<form id="co-shipping-method-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>">
    <fieldset class="metodos-envio">
        <dl class="sp-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt><?php echo $this->getCarrierName($code) ?></dt>
                <dd>
                    <ul>
                    <?php foreach ($_rates as $_rate): ?>
                        <?php if ($_rate->getErrorMessage()) echo ' class="error-msg"';?>
                           <?php if ($_rate->getErrorMessage()): ?>
                                <?php echo $_rate->getErrorMessage() ?>
                           <?php else: ?>
                                <input name="estimate_method" type="radio" onclick="this.form.submit();" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
                                <label for="s_method_<?php echo $_rate->getCode() ?>">
                                	
                                	<?php echo ($_rate->getPrice() == 0 && preg_match('/^Frete/', $_rate->getMethodTitle()) == false)? '<span class="tagfretegratis">Frete grátis</span>': null;?>
                                	<?php 
                                		if(preg_match('/^Frete/', $_rate->getMethodTitle()) == false){
                                			echo '<strong>' . preg_replace('/[ ]/',' </strong>',$_rate->getMethodTitle(),1);
                                		}else{
                                			echo preg_replace('/Frete grátis/','<span class="tagfretegratis">Frete grátis</span>',$_rate->getMethodTitle(),1);
                                		} 
                                	?>
                                	
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                
                                <?php
                                    	if($_rate->getPrice() == 0){ 
                                    		echo str_replace('price','price0',$_excl);
                                    	}else{
                                    		echo $_excl;
                                    	} 
                                ?>
                                
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                                </label>
                           <?php endif ?>
                           &nbsp;&nbsp;<?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
        </dl>
    </fieldset>
</form>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    var coShippingMethodForm = new VarienForm('shipping-zip-form');
    Validation.addAllThese(
    [
           ['validate-postcode', 'Insira um CEP válido.', function(v) {
                var element = $('postcode');
                if (element && ('' != element.value)) {
					var regCep = /(^\d{5}-\d{3}|^\d{2}.\d{3}-\d{3}|\d{8}$)/;
					if (!regCep.test(element.value)) {
                        return false;
                    }
                }
                return true;
           }]
    ]
    );
//]]>
</script>