<?php

function formatMoney( $valor )
{
    $valor = (float) str_replace(',', '.', $valor);
    if ( (int) $valor != $valor )
    {
        list($inteiro, $decimal) = explode('.', $valor);
        $valor = $inteiro . "." . str_pad( substr($decimal,0,2), 2, "0", STR_PAD_RIGHT);
    }
    else
    {
        $valor = number_format($valor, 2, '.', ',');
    }
    
    return $valor;
}

$t = $this->getTotals();

$gt = $t['grand_total'];
$d = $gt->getData();
$grand_total = $d['value'];

?><tr>
    <td class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		<?php echo Mage::helper('weee')->__('Juros'); ?>
    </td>
    <td class="a-right">
		<?php echo $this->helper( "checkout" )->formatPrice( formatMoney($this->getTotalParcelamento())-$grand_total ); ?>
    </td>
</tr>
<tr>
    <td class="a-right" colspan="<?php echo $this->getColspan(); ?>">
		<strong><?php echo Mage::helper('weee')->__('Total') . ' (' . $this->getParcelas() . ' x ' . $this->helper( "checkout" )->formatPrice( formatMoney($this->getValorParcela()) ) . ')'; ?></strong>
    </td>
    <td class="a-right">
		<strong><?php echo $this->helper( "checkout" )->formatPrice( formatMoney($this->getTotalParcelamento()) ); ?></strong>
    </td>
</tr>
