<?php 
$_code = $this->getMethodCode(); 
$_bandeiras = $this->getBandeiras();
?>

<script type="text/javascript">

function onclickRadio(o){
	if(o.checked){
		$('parcelas').value = o.value;
	}
}

function changeBandeira(o){
	$('cc_type').value = o.value;
	$$('.li_parcelas').each(Element.hide);
	$$('.li_parcelas').each(function(s){ s.checked = false; });
	$(o.value + '_parcelas').setStyle({display: 'block'});
	$(o.value + '_rd_parcela_1').checked = true;
	$('parcelas').value = 1;
}

</script>

<fieldset class="form-list">
	
	<ul id="payment_form_<?php echo $_code; ?>" style="display: none;">
		<li>
			<?php echo $this->__('* Preencher todos os campos '); ?>
		</li>
		<li>
			<strong>Bandeira</strong> <br />
			<select name="payment[bandeira]" id="bandeira" onchange="javascript:changeBandeira(this);" >
				<option value=""> -- Seleciona uma Bandeira -- </option>
				<?php foreach($_bandeiras as $bandeira){ ?>
					<option value="<?php echo $bandeira ?>"><?php echo ucfirst($bandeira); ?></option>
				<?php } ?>
			</select>
			<input type="hidden" id="cc_type" name="payment[cc_type]" class="required-entry">   
		</li>
		<li>
			<strong>Nome no cartão de Crédito</strong> <br />
			<input type="text" name="payment[cc_nmcartao]" style="width: 250px;" /> &nbsp;
			<img src="<?php echo $this->getSkinUrl("images/_cards/parcelamento/01.jpg") ?>">
		</li>
		<li>
			<strong>Número do cartão do Crédito</strong> <br />
			<input type="text" name="payment[cc_number]" style="width: 250px;" /> &nbsp;
			<img src="<?php echo $this->getSkinUrl("images/_cards/parcelamento/02.jpg") ?>">
		</li>
		<li>
			<strong>Data de Expiração</strong> &nbsp;
			<img src="<?php echo $this->getSkinUrl("images/_cards/parcelamento/03.jpg") ?>"> <br />
			
			<select name="payment[cc_expmes]" style="width: 100px;">
				<option> -- Selecione -- </option>
				<option value="05"> 05 </option>
				<option value="06"> 06 </option>
			</select>
			
			&nbsp;/&nbsp;
			
			<select name="payment[cc_expano]" style="width: 150px;">
				<option> -- Selecione -- </option>
				<option value="2012"> 2012 </option>
				<option value="2013"> 2013 </option>
			</select>
		</li>
		<li>
			<strong>Código de verificação</strong> <br />
			<input type="text" name="payment[cc_codver]" style="width: 100px;" /> &nbsp;
			<img src="<?php echo $this->getSkinUrl("images/_cards/parcelamento/04.jpg") ?>">
		</li>
		<li>
			<img src="<?php echo $this->getSkinUrl("images/_cards/parcelamento/cartao_generico.jpg") ?>">
		</li>
	
		<!-- Parcelas dos Cartões de Crédito -->
		<input type="hidden" name="payment[parcelas]" id="parcelas" />		
		<?php foreach($_bandeiras as $bandeira){ ?>
			
			<li id="<?php echo $bandeira;?>_parcelas" class="li_parcelas" style="display:none;">
				
				<div style="width: 300px; background: #eee; float:left;" >
					<div style="padding:5px; width:140px; float:left;"><b>Parcelas</b></div>
					<div style="padding:5px; width:140px; float:left;"><b>Valor da Parcela</b></div>
					
				<?php foreach($this->getDadosParcelas($bandeira) as $parcela): ?>
					
					<div style="padding:5px; width:140px; float:left; color:#069;">
						
						<label>
						<input type="radio" name="<?php echo $bandeira?>_rd_parcela"  class="rd_parcela" value="<?php echo $parcela['parcela'];?>" 
							id="<?php echo $bandeira;?>_rd_parcela_<?php echo $parcela['parcela']?>" onclick="javascript:onclickRadio(this)"/>
						
						<?php echo $parcela['parcela'] . ' X ' . $parcela['juros'];?>
						</label>
						
					</div>
					
					<div style="padding:5px; width:140px; float:left; color:#069;"><?php echo Mage::Helper('core')->currency($parcela['valor'],true,false); ?></div>
				
				<?php endforeach;?>
				
				</div>
			</li>
			
		<?php }?>
		
	</ul>
	
</fieldset>
