<?php $order = $this->getQuote()->getData();
$subtotal = $order['subtotal'];
$discount = $order['subtotal'] - $order['subtotal_with_discount'];
$total =$order['grand_total'];
$_helperCheckout = Mage::helper('fd_linkcheckout');
?>

<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('My Cart ') ?></h1>
        <?php $storeId = Mage::app()->getStore()->getStoreId(); ?> 
        <?php if ($storeId == 1): ?>
            <div class="buttons-container">
                <ul class="checkout-types bottom">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <p class="method-dsc"><a href='<?php echo $_helperCheckout->getCheckoutLink(); ?>' title="Fechar Pedido" class="dsc-checkout"><span><span>FINALIZAR</span></span></a></p>
                            <span style="line-height: 50px;cursor:pointer; color: #1abc9c; font-size: 15px;text-transform: none;" type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" class="btn-continue" onclick="setLocation('<?php echo Mage::getBaseUrl() ?>')"><span><span><?php echo $this->__('Comprar mais produtos <i style="font-size: 10px; color: #1abc9c;vertical-align: middle;">&#9658</i>') ?></span></span></span>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <div class="clearfix"></div>
            </div>
        <?php else: ?>
            <div class="buttons-container">
                <?php if(!$this->hasError()): ?>
                    <?php echo $this->getChildHtml('top_methods') ?>
                <?php endif; ?>
                <div class="clearfix"></div>
            </div>
        <?php endif; ?>
    </div>
    <?php echo $this->getChildHtml('form_before') ?>
    <!-- <?php// echo $this->getMessagesBlock()->getGroupedHtml() ?> -->
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" id="cart_form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col width="1" />
                <col />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                <col width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            
            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    
	<div class="totals">
		  <strong><em>Total em produtos</em> <small><?=Mage::helper('core')->currency(($subtotal),true,false) ?></small></strong>
    </div>
    <div class="cart-collaterals">
        <!--div class="col-1">
            <?/*php echo $this->getChildHtml('crosssell') */?>
        </div-->
        <div class="cep">
            <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
        </div>
        <div class="coupon">
            <?php echo $this->getChildHtml('coupon') ?>
		    <strong class="desconto"><em>Add/Desc</em> <small><?=Mage::helper('core')->currency(($discount),true,false) ?></small><span class="clearfix"></span></strong>
        </div>
    </div>
    
    <div class="valores">
		<strong class="total"><em>Valor total da compra</em> <small><?=Mage::helper('core')->currency(($total),true,false) ?></small><span class="clearfix"></span></strong>
		<?php // echo $this->getChildHtml('totals'); ?>
    </div>
    
    <?php $storeId = Mage::app()->getStore()->getStoreId(); ?> 
    <?php if ($storeId == 1): ?>
        <div class="fechar-compra">
            <ul class="checkout-types bottom">
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <p class="method-dsc"><a href='<?php echo $_helperCheckout->getCheckoutLink(); ?>' title="Fechar Pedido" class="dsc-checkout"><span><span>FINALIZAR</span></span></a></p>
                        <span style="line-height: 50px;cursor:pointer; color: #1abc9c; font-size: 15px;text-transform: none;" type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" class="btn-continue" onclick="setLocation('<?php echo Mage::getBaseUrl() ?>')"><span><span><?php echo $this->__('Comprar mais produtos <i style="font-size: 10px; color: #1abc9c;vertical-align: middle;">&#9658</i>') ?></span></span></span>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php else: ?>
        <div class="fechar-compra">
            <?php if(!$this->hasError()): ?>
            <?php echo $this->getChildHtml('methods') ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <div class="continuar-compra">
        <?php if ($this->getContinueShoppingUrl()): ?>
            <a onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?></span></a>
        <?php endif; ?>
        <a href="#" onclick="setLocation( '<?php echo $this->getUrl('emptyCart/index/index') ?>' )"><span><?php echo $this->__( 'Empty Shopping Cart' ) ?></span></a>
        <div class="clearfix"></div>
    </div>
</div>
