<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Searchautocomplete
 * @copyright  Copyright (c) 2003-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>

    <table>
        <tr class="aw_hidden" id="aw_hidden"><td></td></tr>
            <?php foreach ($this->getItems() as $item): ?>
                <?php if ((int) Mage::getStoreConfig('searchautocomplete/interface/open_in_new_window')): ?>
                        <tr><td onClick="window.open('<?php echo $item['url'] ?>', '_blank')">
                            <input type="hidden" name="url" value="setLocation('<?php echo $item['url'] ?>')"></td></tr>
                 <?php else: ?>
                        <tr><td onClick="setLocation('<?php echo $item['url'] ?>')">
                            <input type="hidden" name="url" value="setLocation('<?php echo $item['url'] ?>')">
                 <?php endif; ?>
                 <?php echo $item['content'] ?>
                        </td></tr>
            <?php endforeach; ?>
    </table>
