<?php
$data = $this->getInfo()->getData('additional_information');
?>
    <p><?php echo $this->__('Método de pagamento: %s', $this->htmlEscape($data['method'])) ?></p>
<?php if (isset($data['response']->charges[0]->last_transaction->gateway_id)): ?>
    <p><?php echo $this->__('Chave do pedido: %s', $this->htmlEscape($data['response']->charges[0]->last_transaction->gateway_id)) ?></p>
<?php endif; ?>

<?php if (isset($data['response']->charges[0]->last_transaction->nosso_numero)): ?>
    <p><?php echo $this->__('Nosso Número: %s', $this->htmlEscape($data['response']->charges[0]->last_transaction->nosso_numero)) ?></p>
<?php endif; ?>

<?php if (isset($data['response']->charges[0]->last_transaction->line)): ?>
    <p><?php echo $this->__('Código de Barras: %s', $this->htmlEscape($data['response']->charges[0]->last_transaction->line)) ?></p>
<?php endif; ?>

<?php if (isset($data['cc_owner'])): ?>
    <p><?php echo $this->__('Nome no Cartão: %s', $this->htmlEscape($data['cc_owner'])) ?></p>
<?php endif; ?>
<?php if (isset($data['cc_type'])): ?>
    <p><?php echo $this->__('Bandeira: %s', $this->htmlEscape($data['cc_type'])) ?></p>
<?php endif; ?>
<?php if (isset($data['cc_number'])): ?>
    <p><?php echo $this->__('Número do Cartão: xxxx-%s', $this->htmlEscape($data['cc_number'])) ?></p>
<?php endif; ?>
<?php if (isset($data['cc_exp_month'])): ?>
    <p><?php echo $this->__('Data de Expiração: %s/%s', $this->htmlEscape($data['cc_exp_month']), $this->htmlEscape($data['cc_exp_year'])) ?></p>
<?php endif; ?>
<?php if (isset($data['cc_installments'])): ?>
    <p><?php echo $this->__('Número de Parcelas: %s', $this->htmlEscape($data['cc_installments'])) ?></p>
<?php endif; ?>
<?php if (isset($data['link'])): ?>
    <p><?php echo $this->__('<a href="%s" target="_blank">Imprimir Boleto</a>', $this->htmlEscape($data['link'])) ?></p>
<?php endif; ?>
<?php if (isset($data['response']->charges[0]->last_transaction->url)): ?>
    <p><?php echo $this->__('<a href="%s" target="_blank">Imprimir Boleto</a>', $this->htmlEscape($data['response']->charges[0]->last_transaction->url)) ?></p>
<?php endif; ?>
