<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Islider
 * @version    1.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>

<div id="awis_imageformcontainer">
    <iframe name="awis_loader" id="awis_loader" style="display: none;"></iframe>
    <form enctype="multipart/form-data" method="post" action="<?php echo $this->getUrl('awislider_admin/adminhtml_image/saveimage', array('id' => $this->getData('image_id'))) ?>" id="awis_imageform" target="awis_loader">
        <?php echo ($this->getFormKeyHtml()) ?>
        <div class="content-header" style="margin-top: 6px;">
            <table cellspacing="0">
                <tr>
                    <td style="width:50%;"><h3 class="icon-head head-products"><?php echo $this->getHeaderText() ?></h3></td>
                    <td class="a-right">
                        <?php if(Mage::getSingleton('admin/session')->isAllowed('cms/awislider/new')) : ?>
                        <?php echo $this->getButtonsHtml() ?>
                        <?php endif ?>
                    </td>
                </tr>
            </table>
        </div>
        <div id="awis_image_error"></div>
        <?php echo $this->getChildHtml('form') ?>
    </form>
</div>
