<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();

$_categoryIds = $_product->getCategoryIds();
?>
<?php $_helperLinkMarca = $this->helper('fd_linkmarca'); ?>
<?php $urlLinkMarca = $_helperLinkMarca->getLinkMarca($_product); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);



</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <fieldset class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
                <input type="hidden" name="is_recurring" id="is_recurring" value="0" />
                <input type="hidden" name="recurring_plan" id="recurring_plan" value="0" />
            </fieldset>

            <div id="modal-frete" class="simple-modal">
                <div class="simple-modal-overlay"></div>
                <div class="simple-modal-content">
                    <a href="#modal-frete" class="simple-modal-close">Fechar</a>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('frete')->toHtml(); ?>
                </div>
            </div>

            <div class="product-img-box" style="position:relative">
                <?php if($_product->getPagueLeve()): ?>
                    <div class="frete_gratis_icon page_leve">
                        <?php echo $_product->getAttributeText('pague_leve'); ?>
                    </div>
                <?php endif; ?>

                <?php if($_product->getPromo1()): ?>
                    <div class="selo_promo">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promo1')->toHtml(); ?>
                    </div>
                <?php endif; ?>

                <?php if($_product->getPromo2()): ?>
                    <div class="selo_promo">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promo2')->toHtml(); ?>
                    </div>
                <?php endif; ?>

                <?php if($_product->getPromo3()): ?>
                    <div class="selo_promo">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promo3')->toHtml(); ?>
                    </div>
                <?php endif; ?>

                <?php if($_product->getFreteGratisDropdown()): ?>
                    <div class="frete_gratis_icon">
                        <a href="#frete-gratis-condicoes" class="open-modal">
                            <?php echo $_product->getAttributeText('frete_gratis_dropdown'); ?>
                        </a>
                    </div>
                <?php endif; ?>

                <?php if (in_array(26, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem-controlados')->toHtml(); ?>
                <?php elseif(in_array(295, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem-antimicrobianos')->toHtml(); ?>
                <?php elseif(in_array(14, $_categoryIds) && in_array(28, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem-genericos')->toHtml(); ?>
                <?php elseif(in_array(28, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem')->toHtml(); ?>
                <?php else: ?>
                    <?php echo $this->getChildHtml('media') ?>
                <?php endif; ?>
                
                <div class="image-promotion">
                    <?php echo $_product->getData("image_promotion"); ?>
                </div>
            </div>

            <div class="product-shop">
                <div class="product-shop-inner">

                    <?php if($_product->getAttributeText('manufacturer')): ?>
                        <?php if ($urlLinkMarca): ?>
                            <a class="marca-link" href="<?php echo $urlLinkMarca; ?>">
                        <?php endif; ?>
                        <span class="marca"><?php echo "" . $_product->getAttributeText('manufacturer'); ?></span>
                        <?php if ($urlLinkMarca): ?>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>

                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?></h1>
                    </div>

                    <?php if($_product->getPagueLeve()): ?>
                        <div class="frete_gratis_icon pague_leve">
                            <?php echo $_product->getAttributeText('pague_leve'); ?>
                        </div>
                    <?php endif; ?>

                    <?php if (!in_array(13, $_categoryIds)): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                    <?php endif; ?>

                    <?php if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds)): ?>
                        <div id="vendaproibida">
                            <p><strong>Venda proibida via internet. Mais informações ligue: (11) 4972-8277.</strong></p>
                        </div>
                    <?php endif; ?>

                    <?php if ($this->hasOptions()): ?>
                        <?php if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds)) { ?>
                            <?php // echo $this->getChildHtml('tierprices'); ?>
                            <div class="box-comprar">
                                <?php echo $this->getChildHtml('product_type_data') ?>

                                <a id="duvidas" href="<?php echo $this->getUrl('faleconosco'); ?>"><?php echo $this->__('Doubts ?') ?></a>

                                <div style="clear:both;"></div>
                            </div>
                        <?php } else { ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true); ?>
                        <?php } ?>

                    <?php else: ?>

                        <?php // echo $this->getChildHtml('tierprices') ?>
                        <div class="box-comprar">
                            <?php echo $this->getChildHtml('product_type_data') ?>
                            <div class="add-to-box">

                                <?php
                                if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds)) {
                                    // Do Nothing
                                } else {
                                    echo $this->getChildHtml('addtocart');
                                }
                                ?>
                            </div>
                            <?php if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds)): ?>
                            <?php else: ?>
                                <?php if (!$_product->isSaleable()): ?>
                                <?php endif; ?>
                                <?php echo $this->getChildHtml('alert_urls') ?>
                            <?php endif; ?>

                            <a id="duvidas" href="<?php echo $this->getUrl('faleconosco'); ?>"><?php echo $this->__('Doubts ?') ?></a>

                            <div style="clear:both;"></div>
                        </div>
                    <?php endif; ?>

                    <div id="parcelamento">
                        <?php
                        $sku = $_product->getSku();
                        $rule = Mage::getModel('salesrule/rule')->load(7964);  
                        if (in_array(2826, $_categoryIds)) {
                            $boleto_price = Mage::helper('core')->currency(($_product->final_price * 0.9), true, false);
                        }elseif ($rule->getIsActive() && $sku == '3X27970636' || $rule->getIsActive() && $sku == '3X27970639' || $rule->getIsActive() && $sku == '6X27970636' || $rule->getIsActive() && $sku == '6X27970639' || $rule->getIsActive() && $sku == '12X27970636' || $rule->getIsActive() && $sku == '12X27970639'){
                            $vista = $_product->getfinalPrice() - $_product->getfinalPrice() * 0.05;
                            $boleto_price = Mage::helper('core')->currency($vista, true, false);
                        }else{
                            $boleto_price = Mage::helper('core')->currency(($_product->final_price), true, false);
                        }
                        ?>
                        <!-- Boleto precisa ser tratado sozinho -->

                        <div id="parc_boleto">
                            
                            <img src="<?php print $this->getSkinUrl('images/_cards/parcelamento/cred.png'); ?>" alt="Cartão de crédito" />
                            <em class="parcelamento-info">Até 3x sem juros no cartão</em>
                            <p class="parcela-min">*Parcela mínima de R$ 45,00</p>
                        </div>

                        <?php
                        if (in_array(2826, $_categoryIds)) {
                            ?>
                            <style>
                                .product-essential .special-price, .product-essential .special-price .price {font-weight: normal;color: #333 !important;font-size:24px;}
                                #parc_boleto em {line-height: 31px;font-size: 22px;float: left;padding-left: 5px !important;font-weight: bold;}
                                .no-boleto {color:#df3626;padding-left:5px; font-size: 11px;}
                                #parc_boleto .parcelamento-info {color:#333;}
                            </style>
                            <?php
                        }else{ ?>

                            <?php
                        }

                        ?>

                        <!-- BEGIN Parcelamento -->
                        <div class="listCards">
                            <strong class="cartao-info">Clique sobre a bandeira do Cartão para informações de parcelamento</strong>

                            <div class="cards-block first">
                                <a title="Visa" href="#parcelamento" rel="parc_visa">
                                    <img src="<?php print $this->getSkinUrl('images/_cards/parcelamento/visa.png'); ?>" alt="Visa" />
                                    <span>Visa</span>
                                    <i class="icon-font icon-ic_chevron_left_black_24px rotateDown"></i>
                                </a>
                                <div class="parcelas c1" id="parc_visa">
                                    <p>
                                        Parcelamento com o <strong>Visa</strong>
                                        <a title="Fechar" class="fechar">Fechar</a>
                                    </p>
                                    <?php
                                    $result = Mage::helper('adyen/installments')->getInstallmentForCreditCardForProduct('VI',$_product->final_price);
                                    echo $result;
                                    ?>
                                </div>
                            </div>
                            <div class="cards-block">
                                <a title="Mastercard" href="#parcelamento" rel="parc_master">
                                    <img src="<?php print $this->getSkinUrl('images/_cards/parcelamento/mastercard.png'); ?>" alt="Mastercard" />
                                    <span>Mastercard</span>
                                    <i class="icon-font icon-ic_chevron_left_black_24px rotateDown"></i>
                                </a>
                                <div class="parcelas c2" id="parc_master">
                                    <p>
                                        Parcelamento com o <strong>MasterCard</strong>
                                        <a title="Fechar" class="fechar">Fechar</a>
                                    </p>
                                    <?php
                                    $result = Mage::helper('adyen/installments')->getInstallmentForCreditCardForProduct('MC',$_product->final_price);
                                    echo $result;
                                    ?>
                                </div>
                            </div>
                            
                        </div>

                    </div>

                    <?php echo $this->getChildHtml('other'); ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif; ?>

                    <div class="link-set">
                        <?php if (!$this->hasOptions()): ?>
                            <div class="add-to-box">
                                <?php echo $this->getChildHtml('addto') ?>
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="boxes">
                        <div class="link-set2">
                            <i class="font-icon icon-ic_share_black_18px"></i>
                            <span><?php echo $this->__('Compartilhar') ?></span>
                            <ul class="share-buttons">
                                <li><a href="https://www.facebook.com/sharer/sharer.php?u=&t=" title="Share on Facebook" target="_blank" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(document.URL) + '&t=' + encodeURIComponent(document.URL)); return false;"><img alt="Share on Facebook" src="<?php echo $this->getSkinUrl('images/Facebook.svg'); ?>" /></a></li>
                                <li><a href="https://twitter.com/intent/tweet?source=&text=:%20" target="_blank" title="Tweet" onclick="window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title) + ':%20'  + encodeURIComponent(document.URL)); return false;"><img alt="Tweet" src="<?php echo $this->getSkinUrl('images/Twitter.svg'); ?>" /></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="clearer"></div>

                </div>
            </div>

        </form>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(){
                if (this.validator.validate()) {
                    this.form.submit();
                }
            }.bind(productAddToCartForm);
            //]]>

            if(jQuery('#messages_product_view span').text() == "Avisaremos por email quando retornar ao estoque"){
                jQuery("#messages_product_view .messages span").css({ 'color': '#fff', 'font-weight': 'bold', 'font-size': '13px' });
                jQuery(".error-msg").css({ 'border-color': 'blue', 'background-color': 'blue' });
                jQuery(".error-msg").addClass("blue-icon");
            }

        </script>
    </div>

    <div id="container-extra" class="grupo">
        <?php if (($_product->getManual()) || ($_product->getBula() && !in_array(28, $_categoryIds) && !in_array(16, $_categoryIds) && !in_array(295, $_categoryIds) && !in_array(26, $_categoryIds))): ?>
            <div id="acessos-extras">
                <ul>
                    <?php if ($_product->getManual()): ?>
                        <li><a href="/media/upload/pdf/Manuais/<?php echo $_product->getManual(); ?>" target="_blank" class="pdf">Baixar manual do produto em PDF</a></li>
                    <?php endif; ?>

                    <?php if ($_product->getBula() && !in_array(28, $_categoryIds) && !in_array(16, $_categoryIds) && !in_array(295, $_categoryIds) && !in_array(26, $_categoryIds)): ?>
                        <li><a href="/media/upload/pdf/BULAS/<?php echo $_product->getBula(); ?>" target="_blank" class="pdf">Baixar bula do produto em PDF</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if($_product->isSaleable()): ?>
            <?php echo $this->getChildHtml('Multikomerce_Freteproduto_cep') ?>
        <?php endif; ?>
    </div>

    <div class="product-collateral">
        <!-- SCRIPT SYNDIGO -->
        <script src="https://scontent.webcollage.net/api/v2/product-content"></script>
        <script>
            // load Mosaic content
            //Webcollage.loadProductContent('farmadelivery-br-pt', '<?php echo $sku = $_product->getSku() ?>', {"mosaic-board": {containerSelector: "div.product-img-box"}});
            // load Power Page content
            Webcollage.loadProductContent('farmadelivery-br-pt', '<?php echo $sku = $_product->getSku() ?>', {"power-page": {autoPlayAndStop: true}});
         </script>
        <!-- DIV SYNDIGO -->
            <div id="wc-power-page"></div>

        <?php echo $this->getChildHtml('info_tabs'); ?>
        <div class="clearer"></div>
        <?php if($_product->getBula()!='') : ?>
            <?php echo $this->getChildHtml('bula_tabs'); ?>
            <div class="clearer"></div>
        <?php endif; ?>
        <?php if($_product->getManual()!='') : ?>
            <?php echo $this->getChildHtml('manual_tabs'); ?>
            <div class="clearer"></div>
            <?php endif; ?>
        <?php echo $this->getChildHtml('additional_tabs'); ?>
        <div class="clearer"></div>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <div class="clearer"></div>
        <?php echo $this->getChildHtml('product_additional_data') ?>
        <div class="clearer"></div>
    </div>



</div>
<script>
    function sendSignature(plan, button) {
        jQuery('#is_recurring').val('1');
        jQuery('#recurring_plan').val(plan);
        productAddToCartForm.submit(button);
    }

    function openModalSignature() {
        jQuery('#modalSignaturePlans').show();
    }

    function closeModalSignature() {
        jQuery('#modalSignaturePlans').hide();
    }
</script>
<div id="modalSignaturePlans" class="modal-signature-background">
    <div class="modal-signature-modal">
        <a href="javascript: closeModalSignature();" class="modal-signature-close">x</a>
        <div class="modal-signature-title">
            Escolha seu plano de assinatura
        </div>
        <div class="modal-signature-content">
            <div class="options">
                <ul class="products-grid">
                    <?php
                    for($i=1;$i<=3;$i++):
                        if (!$_product->getData('assinatura' . $i . '_meses')) continue;
                        $_discountPercentage = $_product->getData('assinatura' . $i . '_desconto');
                        $_planValue = $_product->getData('assinatura' . $i . '_valorfixo');
                        ?>
                        <li style="position:relative;" class="item <?php echo ($i == 1) ? 'first' : (($i == 3) ? 'last' : ''); ?>" id="product-signature-plan<?php echo $i; ?>" onclick="sendSignature(<?php echo $i; ?>, this);">
                            <?php $_categoryIds = $_product->getCategoryIds(); ?>
                            <?php /*if($_discountPercentage > 0){  ?>
                                <div class="desconto_icon">DESCONTO DE <?php echo '' . $_discountPercentage . '%' ?></div>
                            <?php }else{ ?>
                                <div style="background-color:#fff;font-size:0;" class="desconto_icon">DESCONTO DE <?php echo '-' . $_discountPercentage . '%' ?></div>
                            <?php }*/ ?>

                            <!-- FIM SELOS -->

                            <h2 class="product-name">Assinar por <?php echo $_product->getData('assinatura' . $i . '_meses'); ?> meses</h2>

                            <?php
                                //$calcDiscount = $_product->getPrice() - (($_product->getPrice() * $_discountPercentage) / 100);
                            ?>

                            <?php echo Mage::helper('core')->currency($_planValue); ?>

                            <p><i>* cada caixa</i></p>

                            <div class="actions">
                                <button type="button" title="Assinar" class="button btn-cart" id="product-signature-plan<?php echo $i; ?>" onclick="sendSignature(<?php echo $i; ?>, this);"><span><span>Assinar</span></span></button>
                            </div>
                        </li>
                    <?php endfor; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<style>
    .modal-signature-background {
        position: fixed;
        top: 0;
        bottom: 0;
        width: 100%;
        background: rgba(0,0,0,.7);
        text-align: center;
        z-index: 10000;
        display: none;
        left: 0;
    }
    .modal-signature-modal {
        width: 95%;
        display: inline-block;
        height: 477px;
        background: #fff;
        border: 1px solid #e6e6e6;
        position: relative;
        top: 55px;
        border-radius: 10px;
    }
    .modal-signature-title {
        text-align: center;
        text-transform: uppercase;
        font-size: 12px;
        color: #444;
        padding: 7px;
        font-weight: bold;
    }
    .modal-signature-close {
        border-radius: 50%;
        background: #FF7F0B;
        color: #fff;
        font-size: 14px;
        line-height: 25px;
        position: absolute;
        right: -8px;
        top: -9px;
        width: 25px;
        text-decoration: none;
        text-align: center;
        text-transform: uppercase;
    }
    .modal-signature-content {
        overflow-y: scroll;
        padding: 5px 14px 5px;
        border-bottom-right-radius: 10px;
        margin: 10px 0 0;
    }
    .btn-sign {
        background-color: #FF7F0B !important;
        margin-top: 10px;
    }
    .modal-signature-content li.item {

    }
    .modal-signature-content li.item.first {
        margin-left: 0px;
    }
    .modal-signature-content li.item.last {
        margin-right: 0px;
    }
    .modal-signature-content ul.products-grid li {
        background: #f6f6f6;
        -webkit-box-shadow: 0px 4px 14px 6px #f6f6f6;
        -moz-box-shadow: 0px 4px 14px 6px #f6f6f6;
        box-shadow: 0px 0px 5px 2px #ddd;
        min-height: auto !important;
        padding: 10px !important;
        border-radius: 2px;
        margin-bottom: 13px;
    }
    .modal-signature-content .desconto_icon {
        width: 140px;
        background: #ff7f00;
        border-radius: 5px 0;
        color: #fff;
        padding: 5px;
        margin: 0px auto;
        font-weight: bold;
        font-size: 13px;
        display: block;
    }

    .modal-signature-content h2.product-name {
        padding: 5px 0;
        font-weight: bold;
        font-size: 14px;
    }

    .modal-signature-content .price {
        color: #ef4e3e;
        font-size: 20px;
    }

    .modal-signature-content .actions {
        margin-top: 5px;
    }

    .modal-signature-content .actions button {
        display: inline-block !important;
        border-radius: 5px 0;
        text-transform: uppercase;
        line-height: 32px;
        height: 30px;
    }

    .add-to-box .actions {
        float: left;
        margin-bottom: 35px;
        max-width: 139px;
    }
</style>