<?php
/**
 * Magmodules.eu - http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category      Magmodules
 * @package       Magmodules_Feedbackcompany
 * @author        Magmodules <info@magmodules.eu>
 * @copyright     Copyright (c) 2017 (http://www.magmodules.eu)
 * @license       http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$reviews = $this->getReviews();
$stats = $this->getStats();
$helper = Mage::helper('feedbackcompany');
?>
<div class="feedbackcompany" itemscope itemtype="http://schema.org/Organization">
    <div class="page-title">
        <div class="flexbox-container">
            <h1><?php echo $this->__('The Feedback Company'); ?></h1>
            <div class="header-floating-feedbackcompany">
                <!-- Desktop only -->
                <div class="total-feedbackcompany" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
                    <?php if ($stats->getVotes()) { ?>
                        <div class="total-block-stars-medium">
                            <span style="width: <?php echo $stats->getScore(); ?>%;"></span>
                        </div>
                        <div class="total-description">
                            <?php echo $this->__('%s/%s with %s reviews',
                                '<span itemprop="ratingValue">' . $stats->getScore() . '</span>',
                                '<span itemprop="bestRating">100</span>',
                                '<span itemprop="ratingCount">' . $stats->getVotes() . '</span>'); ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- END Desktop only -->
                <?php if ($review_url = $this->getReviewUrl()) { ?>
                    <button class="button" onclick="setLocation('<?php echo $review_url; ?>')">
                        <span><?php echo $this->__('Write review'); ?></span>
                    </button>
                <?php } ?>
            </div>
        </div>
    </div>

    <!-- Mobile only -->
    <div class="total-feedbackcompany total-feedbackcompany-mobile">
        <?php if ($stats->getVotes()) { ?>
            <?php echo $this->__('%s/%s with %s reviews', '<span>' . $stats->getScore() . '</span>', '<span>100</span>',
                '<span>' . $stats->getVotes() . '</span>'); ?>
            <div class="total-block-stars"><span style="width: <?php echo $stats->getScore(); ?>%"></span></div>
        <?php } ?>
    </div>
    <!-- END Mobile only -->

    <?php if ($reviews->getSize()) { ?>
        <div class="content-feedbackcompany">
            <div class="about-feedbackcompany">
                <?php echo $this->getPageIntro(); ?>
            </div>
        </div>
        <?php foreach ($reviews as $review): ?>
            <div class="review-list" itemprop="review" itemscope itemtype="http://schema.org/Review">
                <div class="review-header">
                    <?php if ($review->getScore()) { ?>
                        <ul class="overall">
                            <li>
                                <div class="total-block-stars-small" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                    <span style="width: <?php echo $review->getScore() * 20; ?>%"></span>
                                    <meta itemprop="worstRating" content="1"/>
                                    <meta itemprop="ratingValue" content="<?php echo $review->getScore(); ?>"/>
                                    <meta itemprop="bestRating" content="5"/>
                                </div>
                            </li>
                        </ul>
                    <?php } ?>
                    <h4>
                        <span itemprop="author">
                            <?php echo($review->getCustomerName() ?: $this->__('Anonymous')); ?>
                        </span>
                        -
                        <meta itemprop="datePublished" content="<?php echo $review->getDateCreated(); ?>">
                        <?php echo Mage::helper('core')->formatDate($review->getDateCreated(), 'long', false); ?>
                    </h4>
                </div>
                <div class="review-content">
                    <div class="experience">
                        <?php if ($review->getReviewText()) { ?>
                            <span itemprop="description">
                                <?php echo nl2br($review->getReviewText()); ?>
                            </span>
                        <?php } ?>
                        <?php if ($response = $review->getCompanyResponse()) { ?>
                            <div class="company_response top">
                                <?php echo $response; ?>
                            </div>
                        <?php } ?>
                    </div>

                    <div class="column">
                        <?php $questions = $helper->getQuestions($review->getQuestions(), true, 'open'); ?>
                        <?php foreach ($questions as $question) { ?>
                            <?php if(!empty($question['answer'])) { ?>
                                <dt class="title"><?php echo $question['Reviewtitle'] ?></dt>
                                <dd class="answer"><?php echo $question['answer'] ?></dd>
                            <?php } ?>
                        <?php } ?>
                    </div>

                    <dl class="dl-feedback">
                        <?php if ($buyOnline = $review->getBuyOnline()) { ?>
                            <dt><?php echo $this->__('Buy Online'); ?></dt>
                            <dd><?php echo ucfirst($buyOnline); ?></dd>
                        <?php } ?>
                        <?php if ($sex = $review->getCustomerSex()) { ?>
                            <dt><?php echo $this->__('Gender'); ?></dt>
                            <dd><?php echo ucfirst($sex); ?></dd>
                        <?php } ?>
                        <?php if ($city = $review->getCustomerCiy()) { ?>
                            <dt><?php echo $this->__('City'); ?></dt>
                            <dd><?php echo ucfirst($city); ?></dd>
                        <?php } ?>
                        <?php if ($country = $review->getCustomerCountry()) { ?>
                            <dt><?php echo $this->__('Country'); ?></dt>
                            <dd><?php echo ucfirst($country); ?></dd>
                        <?php } ?>
                        <?php if ($customer_recommend = $helper->getCustomerRecommend($review->getCustomerRecommend())) { ?>
                            <dt><?php echo $this->__('Recommend'); ?></dt>
                            <dd><?php echo ucfirst($customer_recommend); ?></dd>
                        <?php } ?>
                    </dl>
                    <dl class="summary-index">
                        <div class="column">
                            <?php
                            $questions = $helper->getQuestions($review->getQuestions(), true, 'score');
                            $half = ceil(count($questions) / 2);
                            $i = 0;
                            ?>
                            <?php foreach ($questions as $question) { ?>
                                <dt><?php echo $question['Reviewtitle'] ?></dt>
                                <dd>
                                    <div class="total-block-stars-grey">
                                        <span style="width: <?php echo($question['value'] * 20); ?>%"></span>
                                    </div>
                                </dd>
                                <?php if (++$i == $half) {
                                    echo '</div><div class="column">';
                                } ?>
                            <?php } ?>
                        </div>
                    </dl>
                </div>
            </div>
        <?php endforeach; ?>
        <?php echo $this->getPagerHtml(); ?>
    <?php } else { ?>
        <p class="note-msg">
            <?php echo $this->__('No reviews found...'); ?>
        </p>
    <?php } ?>
</div>