<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();

$_categoryIds = $_product->getCategoryIds();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    
   
    
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <fieldset class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </fieldset>

            <div id="modal-frete" class="simple-modal">
                <div class="simple-modal-overlay"></div>
                <div class="simple-modal-content">
                    <a href="#modal-frete" class="simple-modal-close">Fechar</a>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('frete')->toHtml(); ?>
                </div>
            </div>

            <div class="product-img-box" style="position:relative">
                <?php if (in_array(1590, $_categoryIds) || 
                in_array(1522, $_categoryIds) ||
                in_array(2307, $_categoryIds) ||
                in_array(1524, $_categoryIds) ||
                in_array(1526, $_categoryIds) ||
                in_array(1528, $_categoryIds) ||
                in_array(2282, $_categoryIds) ||
                in_array(1530, $_categoryIds) ||
                in_array(1532, $_categoryIds) ||
                in_array(1534, $_categoryIds) ||
                in_array(1502, $_categoryIds) ||
                in_array(1500, $_categoryIds) ||
                in_array(2276, $_categoryIds) ||
                in_array(1536, $_categoryIds) ||
                in_array(1538, $_categoryIds) ||
                in_array(1540, $_categoryIds) ||
                in_array(2114, $_categoryIds) ||
                in_array(1542, $_categoryIds) ||
                in_array(1546, $_categoryIds) ||
                in_array(1544, $_categoryIds) ||
                in_array(1548, $_categoryIds) ||
                in_array(2320, $_categoryIds) ||
                in_array(2321, $_categoryIds) ||
                in_array(2318, $_categoryIds)
                ): ?>
                <?php else: ?>
                <?php endif; ?>
                
                <?php if (in_array(26, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem-controlados')->toHtml(); ?>
                <?php elseif(in_array(295, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem-antimicrobianos')->toHtml(); ?>
                <?php elseif(in_array(14, $_categoryIds) && in_array(28, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem-genericos')->toHtml(); ?>
                <?php elseif(in_array(28, $_categoryIds)): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('medicamento-sem-imagem')->toHtml(); ?>
                <?php else: ?>
                    <?php echo $this->getChildHtml('media') ?>
                <?php endif; ?>
            </div>

            <div class="product-shop">
                <div class="product-shop-inner">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?></h1>
                    </div>
                    
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                    
                    <?php if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds) || in_array(1590, $_categoryIds)): ?>
                        <div id="vendaproibida">
                            <p><strong>Venda proibida via internet. Mais informações ligue: (11) 4972-8277.</strong></p>
                        </div>
                    <?php endif; ?>

                    <?php if ($this->hasOptions()): ?>
                        <?php if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds) || in_array(1590, $_categoryIds)) { ?>
                            <?php // echo $this->getChildHtml('tierprices'); ?>
                            <div class="box-comprar">
                                <?php echo $this->getChildHtml('product_type_data') ?>
                                
                                <a id="duvidas" href="<?php echo $this->getUrl('faleconosco'); ?>"><?php echo $this->__('Doubts ?') ?></a>
                                
                                <div style="clear:both;"></div>
                            </div>
                        <?php } else { ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true); ?>
                        <?php } ?>

                    <?php else: ?>

                        <?php // echo $this->getChildHtml('tierprices') ?>
                        <div class="box-comprar">
                            <?php echo $this->getChildHtml('product_type_data') ?>
                            <div class="add-to-box">

                                <?php
                                if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds) || in_array(1590, $_categoryIds)) {
                                    // Do Nothing
                                } else {
                                    echo $this->getChildHtml('addtocart');
                                }
                                ?>
                            </div>
                            <?php if (in_array(26, $_categoryIds) || in_array(295, $_categoryIds) || in_array(1590, $_categoryIds)): ?>
                            <?php else: ?>
                                <?php if (!$_product->isSaleable()): ?>
                                <?php endif; ?>
                                <?php echo $this->getChildHtml('alert_urls') ?>
                            <?php endif; ?>
                            
                            <a id="duvidas" href="<?php echo $this->getUrl('faleconosco'); ?>"><?php echo $this->__('Doubts ?') ?></a>

                            <div style="clear:both;"></div>
                        </div>
                    <?php endif; ?>

                    <?php echo $this->getChildHtml('other'); ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif; ?>
                    
                    <div class="link-set">
                        <?php if (!$this->hasOptions()): ?>
                            <div class="add-to-box">
                                <?php echo $this->getChildHtml('addto') ?>
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="boxes">
                        <div class="link-set2">
                            
                        </div>
                    </div>
                    <div class="clearer"></div>

                </div>
            </div>

        </form>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(){
                if (this.validator.validate()) {
                    this.form.submit();
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>

    <div id="container-extra" class="grupo">
        <div id="acessos-extras">
            <ul>
                <?php if ($_product->getManual()): ?>
                    <li><a href="/media/upload/pdf/Manuais/<?php echo $_product->getManual(); ?>" target="_blank" class="pdf">Baixar manual do produto em PDF</a></li>
                <?php endif; ?>
                    
                <?php if ($_product->getBula()): ?>
                    <li><a href="/media/upload/pdf/BULAS/<?php echo $_product->getBula(); ?>" target="_blank" class="pdf">Baixar bula do produto em PDF</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>

    <div class="product-collateral">
        <?php echo $this->getChildHtml('info_tabs'); ?>
        <div class="clearer"></div>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <div class="clearer"></div>
        <?php echo $this->getChildHtml('product_additional_data') ?>
        <div class="clearer"></div>
    </div>

</div>