<?php if (Mage::getStoreConfig('tm_ajaxsearch/general/enabled')) :?>
<?php if (Mage::getStoreConfig('tm_ajaxsearch/general/enableleft')) :?>
<div class="block mini-search-left">
    <div class="block-title">
        <strong><?php echo $this->__('Search') ?></strong>
    </div>
    <div class="block-content">
    <form id="search_mini_form-left" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
            <fieldset>
                <legend><?php echo $this->__('Search Site') ?></legend>
                <div class="mini-search-left">
                    <label for="search-left"><?php echo $this->__('Search entire store here') ?></label>
                    <?php
                        $searchFieldText = Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext');

                        $queryText = Mage::helper('catalogsearch')->getEscapedQueryText();
                        if (!empty($queryText)) {
                            $searchFieldText = $queryText;
                        }
                    ?>
                    <input id="search-left" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $searchFieldText; ?>" />
                    <div id="search-leftajaxico" class=""></div>
                    <button type="button" class="button">
                        <span><span><?php echo $this->__('Search') ?></span></span>
                    </button>
                    <a href="<?php echo $this->getUrl('catalogsearch/advanced/'); ?>"><?php echo $this->__('Advanced search') ?></a>
                </div>
            </fieldset>
    </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    <?php $_isSecure = $this->getRequest()->isSecure(); ?>
    function initAjaxsearchAutocomplete(){
        new AjaxsearchAutocomplete('search-left', {
            serviceUrl   : '<?php echo $this->getUrl('ajaxsearch', array('_secure' => $_isSecure)); ?>',
            enableloader : <?php echo (int)Mage::getStoreConfig('tm_ajaxsearch/general/enableloader') ? 'true' : 'false'; ?>,
            minChars     : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/minchars'); ?>,
            maxHeight    : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/maxheight'); ?>,
            width        : '<?php echo Mage::getStoreConfig('tm_ajaxsearch/general/width'); ?>',
            searchtext   : '<?php echo Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext'); ?>',
            onSelect     : function (value, data) {setLocation(value.url);}
        });
    }
    if (Prototype.Browser.IE) {
        Event.observe(window, 'load', initAjaxsearchAutocomplete);
    } else {
        document.observe("dom:loaded", initAjaxsearchAutocomplete);
    }
//]]>
</script>
<?php endif; ?>
<?php endif; ?>
