<?php if (Mage::getStoreConfig('tm_ajaxsearch/general/enabled')) :?>
<form id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
    <fieldset>
        <legend><?php echo $this->__('Search Site') ?></legend>
        <div class="mini-search form-search">
            <div id="searchajaxico" class=""></div>
            <?php if (Mage::getStoreConfigFlag('tm_ajaxsearch/general/show_category_filter')) : ?>
                <?php echo $this->getChildHtml('ajaxsearch_category_filter') ?>
            <?php endif; ?>
            <?php
                $searchFieldText = Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext');

                $queryText = Mage::helper('catalogsearch')->getEscapedQueryText();
            ?>
            <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $queryText; ?>" placeholder="<?php echo $searchFieldText; ?>" />
            <button type="button" title="<?php echo $this->__('Search') ?>" class="button">
                <span><span><?php echo $this->__('Buscar') ?></span></span>
            </button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    <?php $_isSecure = $this->getRequest()->isSecure(); ?>
    function initAjaxsearchAutocomplete(){
        new AjaxsearchAutocomplete('search', {
            serviceUrl   : '<?php echo $this->getUrl('ajaxsearch', array('_secure' => $_isSecure)); ?>',
            enableloader : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/enableloader') ? 'true' : 'false'; ?>,
            minChars     : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/minchars'); ?>,
            maxHeight    : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/maxheight'); ?>,
            width        : '<?php echo Mage::getStoreConfig('tm_ajaxsearch/general/width'); ?>',
            searchtext   : '<?php echo Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext'); ?>',
            onSelect     : function (value, data) {setLocation(value.url);}
        });
    }
    if (Prototype.Browser.IE) {
        Event.observe(window, 'load', initAjaxsearchAutocomplete);
    } else {
        document.observe("dom:loaded", initAjaxsearchAutocomplete);
    }
//]]>
</script>
<?php endif; ?>