<?php
$fields = $this->getFields();
if (count($fields)):
    $entityName = $this->getEntityName();
?>
    <?php
    if ($title = $this->getEntityTitle()):
    ?>
    <div class="entity_title">
        <?php echo $title; ?>
    </div>
    <?php endif; ?>
    <ul class="smartpbm-check-form">
    <?php foreach ($this->getFields() as $field): ?>
        <?php
            //if (!in_array($field->Exibicao, [1,3])) continue;

            $class = ($field->Exibicao == 3) ? 'required' : '';
            $fieldName = $entityName . '[' . $field->Campo . ']';
            $methods = '';
            $extras = '';
            if ($field->Campo == 'NumeroRegistroConselho') {
                $field->NomeExibicao = 'Número do CRM';
                $methods .= ' onblur="bindCrm(this)"';
            }

            if ($field->Campo == 'CEP') {
                //$methods .= ' onkeyup="formatZipcode(this)"';
                $extras .= ' maxlength="8"';
            }

            if ($field->Campo == 'Nascimento' || $field->Campo == 'receita') {
                $methods .= ' onkeyup="formatDate(this)"';
                $extras .= ' maxlength="10"';
            }

            if (strpos($field->Campo, 'Telefone') !== false) {
                $methods .= ' onkeyup="formatPhone(this)"';
                $extras .= ' maxlength="14"';
            }
        ?>
        <?php if ($field->Exibicao == 1): ?>
            <input type="hidden" id="spr_<?php echo $field->Campo; ?>" name="<?php echo $fieldName; ?>" value="<?php echo $field->ValorInicial; ?>" />
        <?php else: ?>
        <li class="item">
            <div class="input-box">
                <label for="spr_<?php echo $field->Campo; ?>"><?php echo $field->NomeExibicao; ?></label>
                <span class="input-text-right">
                <?php if (in_array($field->Tipo, [1,2,3,5])): //String, Inteiro, Decimal e DateTime ?>
                    <input type="text"
                           class="input-text"
                           id="spr_<?php echo $field->Campo; ?>"
                           name="<?php echo $fieldName; ?>"
                           placeholder="<?php echo $field->NomeExibicao; ?>"
                           <?php echo $methods; ?>
                           <?php echo $extras; ?>
                    />
                <?php endif; ?>

                <?php if ($field->Tipo == 4): //Boolean ?>
                    <select class="input-text" id="spr_<?php echo $field->Campo; ?>" name="<?php echo $fieldName; ?>">
                        <option value="">Selecione</option>
                        <option value="true">Sim</option>
                        <option value="false">Não</option>
                    </select>
                <?php endif; ?>

                <?php if ($field->Tipo == 6): //Select ?>
                    <select class="input-text" id="spr_<?php echo $field->Campo; ?>" name="<?php echo $fieldName; ?>">
                        <option value="">Selecione</option>
                        <?php foreach ($field->Opcoes as $option): ?>
                        <option value="<?php echo $option->Valor; ?>"><?php echo $option->Texto; ?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
                </span>
            </div>
        </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
<?php endif;