<?php
if (version_compare(Mage::getVersion(), '1.4.0.1', '>='))://fix cho magento 1.3
// neu customer dang login ($islogin)va co thong tin cho address ($had_address)
    $islogin = 0;
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {
        $islogin = 1; //dang login
    }
    ?>

    <script type="text/javascript">
        var senha_block = " \
        <li class=\"fields\" id=\"register-customer-password\" style=\"display:none;\"> \
            <div class=\"fieldhalf1\"> \
                <label for=\"billing:customer_password\" class=\"required\"><em>*</em> <?php echo $this->__('Senha') ?>: <small>(6 a 10 carac.)</small></label>  \
                <div class=\"input-box\"> \
                    <input type=\"password\" name=\"billing[customer_password]\" id=\"billing:customer_password\" title=\"<?php echo $this->__('Password') ?>\" class=\"input-text inputtext required-entry validate-password\" /> \
                </div> \
            </div> \
            <div class=\"fieldhalf2\"> \
                <label for=\"billing:confirm_password\" class=\"required\"><em>*</em> <?php echo $this->__('Confirmar Senha') ?>:</label> \
                <div class=\"input-box\"> \
                    <input type=\"password\" name=\"billing[confirm_password]\" title=\"<?php echo $this->__('Confirm Password') ?>\" id=\"billing:confirm_password\" class=\"input-text inputtext required-entry validate-cpassword\" /> \
                </div> \
            </div> \
        </li>";

		$j(function(){
			$j("#register-customer-password").remove();
			$j('#containernovaconta').append(senha_block);
		
			$j('#fisicajuridica .fisica').click(function(){
				$j('#nomeempresa').hide();
			});
			$j('#fisicajuridica .juridica').click(function(){
				$j('#nomeempresa').show();
			});
		
			$j('#quero_me_cadastrar').click(function(){
				$j('#register_new_account').attr('checked','checked').val(1); // Marca para criar nova conta
				$j('#containernovaconta').hide();
				$j("#register-customer-password").remove();
				$j('#form_field_email').addClass('ativo').after(senha_block);
				$j('#register-customer-password').show();
			});
		
			$j('#comprar_como_visitante').click(function(){
				$j('#containernovaconta').show();
				$j("#register-customer-password").remove();
				$j('#containernovaconta').append(senha_block);
				$j('#register_new_account').attr('checked','').val(0); // Desmarca criar nova conta
				$j('#form_field_email').removeClass('ativo')
			})
			
			// seta quero me cadastrar como default
			$j('#quero_me_cadastrar').click();

			$j('.validate-zip-international').keydown(function(event) {
		        // Allow: backspace, delete, tab, escape, and enter
		        if ( event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || event.keyCode == 13 || 
		             // Allow: Ctrl+A
		            (event.keyCode == 65 && event.ctrlKey === true) || 
		             // Allow: home, end, left, right
		            (event.keyCode >= 35 && event.keyCode <= 39)) {
		                 // let it happen, don't do anything
		                 return;
		        } else {
		            // Ensure that it is a number and stop the keypress
		            if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
		                event.preventDefault(); 
		            }   
		        }
		    }).blur(function(){
		    	var sizezip = $j(this).val().length;
		    	if (sizezip<7) {
		    		alert('O CEP deve ter 7 dígitos.');
		    		$j(this).val('');
		    	};
		    });

		});

		function checkCepJapao(cep, tipo) {
			//alert(cep);
		    new Ajax.Request('https://japan.farmadelivery.com.br/util/ajax/consultaCepJapao/?cep=' + cep + '&tipo=' + tipo, {
		        method: 'get',
		        evalJS: true,
		        onLoading: function() {
		            //$('load').innerHTML = "carregando...";
		        },
		        onSuccess: function(transport) {
		            //$('load').innerHTML = "";
		            //alert(transport.responseText);
		            if (transport.responseText != '') {
		                eval(transport.responseText)
		            }
		        }
		    });
		}
    </script>
    
    <li id="fisicajuridica" class="fields" style="display: none;" >
        <div class="fieldhalf1">
            <input type="radio" name="billing[fisica_juridica]" class="fisica" value="Fisica" checked="checked" id="billing:fisica_juridica_f"> <label for="billing:fisica_juridica_f">Pessoa Física</label>&nbsp;&nbsp;&nbsp;
        </div>
        <div class="fieldhalf2">
            <input type="radio" name="billing[fisica_juridica]" class="juridica" value="Juridica" id="billing:fisica_juridica_j"> <label for="billing:fisica_juridica_j">Pessoa Jurídica</label>
        </div>
    </li>
        
    <?php if (!$islogin): ?>
		<li id="opcaoidentificacao">
			<div>
				<?php /*?><div style="display:none;">
					<label><input type="radio" name="fazer_conta" id="quero_me_cadastrar" />Quero me cadastrar</label>
					<p class="descricao">Facilitar minhas próximas compras e acompanhar meu pedido pelo site</p>
		
					<label><input type="radio" name="fazer_conta" checked="checked" id="comprar_como_visitante" />Quero comprar como visitante</label>
					<p class="descricao">Sem precisar criar mais uma senha e acompanhar o status da minha compra apenas por e-mail</p>
				</div> 
				<p>Para prosseguir com sua compra você deve se indentificar. Faça login ou preencha o cadastro abaixo.</p>
	*/?>
				<?php if (Mage::getStoreConfig('onestepcheckout/config/enable_quicklogin')): ?>
					<p id="linktologin">Já é cadastrado? <a id="loginbox" href="#inline1" title="">Clique aqui para entrar.</a></p>
				<?php endif ?>
			</div>
		</li>
    <?php endif ?>  

    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setTemplate('mw_onestepcheckout/name.phtml')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>

    <?php if (!$this->isCustomerLoggedIn()): ?>
        <li class="fields" id="form_field_email">
            <div class="field">
                <label for="billing:email" class="required"><em>*</em> <?php echo $this->__('E-mail') ?>: <small>(você usará este e-mail para seu login)</small></label>
                <div class="input-box">
                    <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text inputtext validate-email required-entry" />
                </div>
            </div>
        </li>
    <?php endif ?>

    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>

    <?php if ($_taxvat->isEnabled()): ?>
        <li class="fields">
            <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
        </li>
    <?php endif ?>

    <li class="fields" id="documentoIeRg" style="display: none;">
    	<span id="documentoRg" style="display: none;" ><label for="billing:identidade_inscricao"><?php echo $this->__('Identidade (RG)') ?>:</label></span>
    	<span id="documentoIe" style="display: none;" ><label for="billing:identidade_inscricao"><?php echo $this->__('Inscrição Estadual') ?>:</label></span>
        <div class="input-box">
            <input type="text" name="billing[identidade_inscricao]" id="billing:identidade_inscricao" value="<?php echo $this->htmlEscape($this->getCustomer()->getIdentidadeInscricao()) ?>" class="input-text"/>
        </div>
        
    </li>
    
    <li id="nomeempresa" class="fields" style="display:none;">
        <div class="field">
            <label for="billing:company" class="required"><em>*</em> <?php echo $this->__('Empresa') ?>:</label>
            <div class="input-box">
                <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text inputtext" />
            </div>
        </div>
    </li>

    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>

    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

    <?php if ($_gender->isEnabled()): ?>
        <li class="fields">
            <?php if ($_gender->isEnabled()): ?>
                <div class="field">
                    <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </div>
            <?php endif ?>
        </li>
    <?php endif ?>

    <?php if ($_dob->isEnabled()): ?>
        <li class="fields">
            <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
        </li>
    <?php endif; ?>

    <li class="fields">
        <div class="fieldhalf1">
            <label for="billing:telephone" class="required"><em>*</em> <?php echo $this->__('Telefone principal') ?>:</label>
            <div class="input-box">
                <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text inputtext required-entry" id="billing:telephone" />
            </div>
        </div>
        <div class="fieldhalf2">
            <label for="billing:fax"><?php echo $this->__('Telefone alternativo') ?>:</label>
            <div class="input-box">
                <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Celular') ?>" class="input-text inputtext" id="billing:fax" />
            </div>
        </div>
    </li>	

    <li class="fields">
        <div class="fieldhalf1">
            <label for="billing:postcode" class="required"><em>*</em> <?php echo $this->__('CEP') ?>:</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('CEP') ?>" name="billing[postcode]" onblur="checkCepJapao(this.value, 'billing:')" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text inputtext validate-zip-international required-entry" maxlength="7" />
            </div>
        </div>
        <small>Apenas números</small>
    </li>

    <li class="fields">
        <label for="billing:street1" class="required"><em>*</em> <?php echo $this->__('Província') ?>:</label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Street Address 1') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text inputtext required-entry" />
        </div>
    </li>

    <li class="fields">
        <label for="billing:city" class="required"><em>*</em> <?php echo $this->__('Cidade') ?>:</label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text inputtext required-entry" id="billing:city" />
        </div>
    </li>

	<li class="fields">
		<label for="billing:region_id" class="required"><em>*</em> <?php echo $this->__('Distrito') ?>:</label>
        <div class="input-box">
            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                <option value="">Selecione um Estado</option>
            </select>
            <script type="text/javascript">
                //<![CDATA[
                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
            </script>
            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text inputtext" style="display:none;" />
        </div>
	</li>

    <li class="fields">
        <label for="billing:street2" class="required"><?php echo $this->__('Observações') ?>:</label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Street Address 2') ?>" name="billing[street][]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text inputtext" />
        </div>
        <p>Se Província/Cidade/Distrito acima estão corretos, deixe este campo em branco, se há divergência, registre o correto.</p>
    </li>

    <li class="fields">
        <label for="billing:street3" class="required"><em>*</em> <?php echo $this->__('Complemento do distrito') ?>:</label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Street Address 3') ?>" name="billing[street][]" id="billing:street3" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(3)) ?>" class="input-text inputtext required-entry" />
        </div>
    </li>

    <li class="fields">
        <label for="billing:street4"><?php echo $this->__('Conjunto residencial ou edifício + bloco + apato') ?>:</label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Street Address 4') ?>" name="billing[street][]" id="billing:street4" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(4)) ?>" class="input-text inputtext" />
        </div>
    </li>

    <li class="fields" style="display:none;">
        <div class="fieldhalf1">
            <label for="billing:country_id" class="required"><em>*</em> <?php echo $this->__('País') ?>:</label>
            <div class="input-box">
                <?php echo $this->getCountryHtmlSelect('billing') ?>
            </div>
        </div>
    </li>
<?php endif; ?>