<?php
// Criteo variables
// Advertiser's Criteo Partner ID
// Syntax: "keyword to look for in URLs (never add http://)" => "corresponding partner ID"
$ctoPartnerUrlToId = array( "www.farmadelivery.com.br" => "19941" );
// Type of ID to pass through the tags ('id' or 'sku')
$ctoIdType = 'id';
$ctoEmail = '1';


// What to pass instead of an account ID if the URL is not recognized
$ctoCurrentPartnerId = "0";

// Selecting the correct account ID
$ctoCurrentUrl = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
foreach ($ctoPartnerUrlToId as $ctoPartnerUrl => $ctoPartnerId) {
	if (stripos($ctoCurrentUrl, $ctoPartnerUrl) !== false) {
		$ctoCurrentPartnerId = $ctoPartnerId;
		break;
	}
}



$ctoObserver = 'criteo_onetag_parameters/observer';
$ctoMage = Mage::getSingleton($ctoObserver);



$ctoIsHomePage          = $ctoMage->ctoIsHomePage();
$ctoIsCategoryPage      = $ctoMage->ctoIsCategoryPage();
$ctoIsSearchPage        = $ctoMage->ctoIsSearchPage();
$ctoIsProductPage       = $ctoMage->ctoIsProductPage();
$ctoIsBasketPage        = $ctoMage->ctoIsBasketPage();
$ctoIsCheckoutPage      = $ctoMage->ctoIsCheckoutPage();
$ctoIsConfirmationPage  = $ctoMage->ctoIsConfirmationPage();
$ctoUserId              = $ctoMage->ctoGetUserId();
$ctoSearchQuery         = $ctoMage->ctoGetSearchQuery();
$ctoTransactionId       = $ctoMage->ctoGetTransactionId();
$ctoProductSku          = $ctoMage->ctoGetProductSku();
$ctoProductId           = $ctoMage->ctoGetProductId();
$ctoProductList         = $ctoMage->ctoGetProductList();



if ($ctoIdType == 'id') {
	$ctoProductIdType = $ctoProductId;
} else {
	$ctoProductIdType = $ctoProductSku;
}

$ctoLoader='<script>(function(d,s){var js=d.getElementsByTagName(s)[0];var r=d.createElement(s);r.async=true;r.src=("https:"==location.protocol?"https:":"http:")+"//static.criteo.net/js/ld/ld.js";js.parentNode.insertBefore(r,js)})(document,"script")</script>'

?>

<!-- Criteo OneTag Start -->
 <?php if ($ctoIsConfirmationPage) :?>

<!-- Confirmation page tag -->
<?php echo $ctoLoader; ?>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: <?php echo $ctoCurrentPartnerId; ?> },
 <?php if ($ctoUserId != NULL && $ctoEmail == 1) :?>
 { event: "setHashedEmail", email: "<?php echo $ctoUserId; ?>" },
 <?php endif;?>
 { event: "setSiteType", type: "m"},
 { event: "trackTransaction" , id: 
<?php echo json_encode($ctoTransactionId); ?>,
 item: [
 <?php $item_number = 0 ?>
 <?php while (isset($ctoProductList[$item_number])) :?>
 { id: 
<?php echo json_encode($ctoProductList[$item_number]['product'][$ctoIdType]); ?>, 
price:
 <?php echo json_encode($ctoProductList[$item_number]['product']['unit_final_price']); ?>, 
quantity:
 <?php echo json_encode($ctoProductList[$item_number]['quantity']); ?>
 }
 <?php $item_number++ ?>
 <?php if (isset($ctoProductList[$item_number])) :?>
 ,
 <?php endif;?>
 <?php endwhile;?>
 ]});
 </script>
 <?php elseif ($ctoIsHomePage) :?>

<!-- Home page tag -->
<?php echo $ctoLoader; ?>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: <?php echo $ctoCurrentPartnerId; ?> },
 <?php if ($ctoUserId != NULL && $ctoEmail == 1) :?>
 { event: "setHashedEmail", email: "<?php echo $ctoUserId; ?>" },
 <?php endif;?>
 { event: "setSiteType", type: "m"},
 { event: "viewHome" }
);
</script>
 <?php elseif ($ctoIsCategoryPage) :?>

<!-- Listing page tag -->
<?php echo $ctoLoader; ?>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: <?php echo $ctoCurrentPartnerId; ?> },
 <?php if ($ctoUserId != NULL && $ctoEmail == 1) :?>
 { event: "setHashedEmail", email: "<?php echo $ctoUserId; ?>" },
 <?php endif;?>
 { event: "setSiteType", type: "m"},
 { event: "viewList",
 item: [
<?php $item_number = 0 ?>
<?php while (isset($ctoProductList[$item_number]) && $item_number < 3) :?>
<?php echo json_encode($ctoProductList[$item_number][$ctoIdType]); ?>
<?php $item_number++ ?>
<?php if (isset($ctoProductList[$item_number]) && $item_number < 3) :?>
,
<?php endif;?>
<?php endwhile;?>
]});
</script>
 <?php elseif ($ctoIsSearchPage) :?>

<!-- Listing page tag -->
<?php echo $ctoLoader; ?>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: <?php echo $ctoCurrentPartnerId; ?> },
 <?php if ($ctoUserId != NULL && $ctoEmail == 1) :?>
 { event: "setHashedEmail", email: "<?php echo $ctoUserId; ?>" },
 <?php endif;?>
 { event: "setSiteType", type: "m"},
 { event: "viewList",
 item: []
<?php if ($ctoSearchQuery != NULL) :?>
, keywords: <?php echo json_encode($ctoSearchQuery); ?> 
<?php endif;?>
}
);
</script>
 <?php elseif ($ctoIsProductPage) :?>

<!-- Product page tag -->
<?php echo $ctoLoader; ?>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: <?php echo $ctoCurrentPartnerId; ?> },
 <?php if ($ctoUserId != NULL && $ctoEmail == 1) :?>
 { event: "setHashedEmail", email: "<?php echo $ctoUserId; ?>" },
 <?php endif;?>
 { event: "setSiteType", type: "m"},
 { event: "viewItem", item: <?php echo json_encode($ctoProductIdType); ?>}
);
</script>
 <?php elseif ($ctoIsBasketPage or $ctoIsCheckoutPage) :?>

<!-- Basket page tag -->
<?php echo $ctoLoader; ?>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: <?php echo $ctoCurrentPartnerId; ?> },
 <?php if ($ctoUserId != NULL && $ctoEmail == 1) :?>
 { event: "setHashedEmail", email: "<?php echo $ctoUserId; ?>" },
 <?php endif;?>
 { event: "setSiteType", type: "m"},
 { event: "viewBasket", item: [
 <?php $item_number = 0 ?>
 <?php while (isset($ctoProductList[$item_number])) :?>
 { id: 
<?php echo json_encode($ctoProductList[$item_number]['product'][$ctoIdType]); ?>, 
price:
 <?php echo json_encode($ctoProductList[$item_number]['product']['unit_final_price']); ?>, 
quantity:
 <?php echo json_encode($ctoProductList[$item_number]['quantity']); ?>
 }
 <?php $item_number++ ?>
 <?php if (isset($ctoProductList[$item_number])) :?>
 ,
 <?php endif;?>
 <?php endwhile;?>
	 ]});
 </script>
 <?php endif;?>
<!-- Criteo OneTag End -->
