<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php
	$active = $this->getActive();
	$disable_estimated_shipping = Mage::getStoreConfig( 'checkout/options/disable_estimated_shipping' );
?>
<div class="block block-progress opc-block-progress">
	<div class="block-content">
		<div class="review progress-block<?php if ( $active == 'review' ): ?> active<?php endif; ?>">
 			<h2>
 				<strong>
 					<?php echo $this->__( 'Resumo do pedido' ) ?>
 				</strong>
 			</h2>
 			<h2 class="show-iphone">
 				<?php echo $this->__( 'Resumo do pedido' ) ?>
 			</h2>
            <div class="fullscreen-overlay">
                <div class="lds-facebook"></div>
            </div>
			<div class="progress-block-details">
				<?php if ( $this->getCheckout()->getStepData( 'payment', 'complete' ) ) : ?>
					<p>
						<?php echo $this->__('Verifique os itens do seu pedido e clique em "Finalizar Compra"'); ?>
					</p>
				<?php else : ?>
					<?php $totalQuantity = intval(Mage::getModel('checkout/cart')->getQuote()->getItemsQty()); ?>
					<table class="p-final">
						<tr>
							<td align="right" class="p-sbt-t">
								<?php echo $this->__( $totalQuantity . ' Produto(s)' ) ?>
							</td>
							<td class="p-p">
								<strong>
									<span class="price">
										<?php
											$totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals();
											$_incl = $totals['subtotal']->getValueInclTax();
											if (Mage::getSingleton('tax/config')->displayCartSubtotalExclTax()) {
												$_excl = $totals['subtotal']->getValue();
											} else {
												$_excl = $totals['subtotal']->getValueExclTax();
											}
											if (Mage::getSingleton('tax/config')->displayCartSubtotalInclTax()) {
												echo Mage::helper('core')->currency($_incl, true, false);
											} else {
												echo Mage::helper('core')->currency($_excl, true, false);
											}
											if (Mage::getSingleton('tax/config')->displayCartSubtotalBoth() && $_incl != $_excl) {
												echo '(' . $this->__('Incl. Tax ');
												echo Mage::helper('core')->currency($_incl, true, false) . ')';
											}
										?>
									</span>
								</strong>
							</td>
						</tr>
						<?php if ( isset( $totals['discount'] ) && $totals['discount']->getValue() ) : ?>
							<tr>
								<td><?php echo $totals['discount']->getTitle(); ?></td>
								<td class="p-p">
									<strong>
										<?php echo Mage::helper( 'core' )->currency( $totals['discount']->getValue(), true, false ); ?>
									</strong>
								</td>
							</tr>
						<?php endif; ?>
						<?php if ( isset( $totals['tax'] ) && $totals['tax']->getValue() ) : ?>
							<tr>
								<td><?php echo $totals['tax']->getTitle(); ?></td>
								<td class="p-p">
									<strong>
										<?php echo Mage::helper( 'core' )->currency( $totals['tax']->getValue(), true, false ); ?>
									</strong>
								</td>
							</tr>
						<?php endif; ?>
						<?php if ( $this->getShippingMethod() && trim( $this->getShippingDescription() ) ) : ?>
							<tr class="sm<?php if ( $this->getCheckout()->getStepData( 'shipping_method', 'complete' ) ) echo ' shine' ?>">
								<td align="right" class="p-method-name">
									Frete
								</td>
								<td class="p-p">
									<strong>
										<?php $_excl = $this->getShippingPriceExclTax(); ?>
										<?php $_incl = $this->getShippingPriceInclTax(); ?>
										<?php if ( $this->helper( 'tax' )->displayShippingPriceIncludingTax() ): ?>
											<?php echo $_incl; ?>
										<?php else: ?>
											<?php echo $_excl; ?>
										<?php endif; ?>
										<?php if ( $this->helper( 'tax' )->displayShippingBothPrices() && $_incl != $_excl ): ?>
											(<?php echo $this->__( 'Incl. Tax' ); ?> <?php echo $_incl; ?>)
										<?php endif; ?>
									</strong>
								</td>
							</tr>
						<?php endif; ?>
						<?php if ( isset( $totals['customerbalance'] ) && $totals['customerbalance']->getValue() ) { ?>
							<?php // we are using the shine class here everytime regardless of if the value changes or not, how to determine if the value has changed? ?>
							<tr<?php if ( $this->getCheckout()->getStepData( 'shipping_method', 'complete' ) ) echo ' shine' ?>>
								<td><?php echo $totals['customerbalance']->getTitle(); ?></td>
								<td class="p-p"><strong><?php echo Mage::helper( 'core' )->currency( $totals['customerbalance']->getValue(), true, false ); ?></strong></td>
							</tr>
						<?php } ?>
						<?php if ( isset( $totals['giftcardaccount'] ) && $totals['giftcardaccount']->getValue() ) { ?>
                   <?php // we are using the shine class here everytime regardless of if the value changes or not, how to determine if the value has changed? ?>
                   <tr class="giftcardaccount <?php if ( $this->getCheckout()->getStepData( 'shipping_method', 'complete' ) ) echo ' shine' ?>">
                           <td><?php echo $totals['giftcardaccount']->getTitle(); ?></td>
                           <td class="p-p"><strong><?php echo Mage::helper( 'core' )->currency( $totals['giftcardaccount']->getValue(), true, false ); ?></strong></td>
                   </tr>
           <?php } ?>
           <?php if ( isset( $totals['giftwrapping'] ) && $totals['giftwrapping']->getValue() ) { ?>
                   <?php // we are using the shine class here everytime regardless of if the value changes or not, how to determine if the value has changed? ?>
                  <tr class="giftwrapping <?php if ( $this->getCheckout()->getStepData( 'shipping_method', 'complete' ) ) echo ' shine' ?>">
                           <td><?php echo $totals['giftwrapping']->getTitle(); ?></td>
                           <td class="p-p"><strong><?php echo Mage::helper( 'core' )->currency( $totals['giftwrapping']->getValue(), true, false ); ?></strong></td>
                   </tr>
           <?php } ?>
						<tr class="grand-total<?php if ( $this->getCheckout()->getStepData( 'shipping_method', 'complete' ) ) echo ' shine' ?>">
							<td align="right"  class="p-gt-t">
								<?php echo $this->__( 'Total' ) ?>
							</td>
							<td class="p-p">
								<strong>
									<?php echo $this->helper( 'checkout' )->formatPrice( Mage::getSingleton( 'checkout/session' )->getQuote()->getGrandTotal() ) ?>
								</strong>
							</td>
						</tr>
					</table>
				<?php endif; ?>
				<?php if ( $active == 'review' ): ?>
					<div class="mark-arrow"></div>
				<?php endif; ?>
				<?php echo $this->getChildHtml('progress_review_after') ?>
			</div>
		</div>

		<?php if ( $this->getCheckout()->getStepData( 'shipping', 'is_show' ) ): ?>
			<?php if ( $this->getCheckout()->getStepData( 'shipping', 'complete' ) ): ?>
				<?php if ( $this->getCheckout()->getStepData( 'shipping_method', 'complete' ) ): ?>
					<div class="shipping progress-block complete
						<?php if ( $this->getCheckout()->getStepData( 'payment', 'complete' ) ) echo 'mob-active '; ?>
						<?php if ( $active == 'shipping' || $active == 'shipping_method' ): ?>active<?php endif; ?>">
						<h2>
							<?php echo $this->__( 'Entrega' ) ?>
						</h2>
						<h2 class="show-iphone">
							<a class="close-fullscreen" href="#shipping" onclick="checkout.openSection('shipping');return false;">
								<?php echo $this->__( 'Entrega' ) ?></a>
						</h2>
						<div class="progress-block-details">
							<div class="edit clearfix">
								<address>
									<?php
									// We need Shipping Address data in custom format
									$shippingAddressData = Mage::getSingleton( 'checkout/session' )->getQuote()->getShippingAddress()->getData();
									echo $shippingAddressData['firstname'] . ' ' . $shippingAddressData['middlename'] . ' ' . $shippingAddressData['lastname'] . '<br />';
									echo $shippingAddressData['street'] . '<br />' . $shippingAddressData['city'] . ', ' . $shippingAddressData['region'] . '&nbsp;&nbsp;';
									echo $shippingAddressData['postcode'] . '<br />' . Mage::getModel( 'directory/country' )->load( $shippingAddressData['country_id'] )->getName();
									?>
									<a class="close-fullscreen" href="#shipping" onclick="checkout.openSection('shipping');return false;">
										<?php echo $this->__( 'Alterar' ) ?>
									</a>
								</address>
							</div>
							<div class="edit shipping-method clearfix">
								<address>
									<?php echo $this->__('Shipping Method:'); ?><br/>
									<?php if ( $this->getShippingMethod() ): ?>
										<?php echo $this->getShippingDescription() ?>
									<?php endif; ?>
								</address>
								<?php if ( Mage::getStoreConfig( 'checkout/options/separate_shipping_method_step' ) ): ?>
									<a class="close-fullscreen" href="#shipping_method" onclick="checkout.openSection('shipping_method');return false;">
										<?php echo $this->__( 'Alterar' ) ?>
									</a>
								<?php else: ?>
									<a class="close-fullscreen" href="#shipping_method" onclick="checkout.openSection('shipping');return false;">
										<?php echo $this->__( 'Alterar' ) ?>
									</a>
								<?php endif; ?>
							</div>
							<?php if ( $active == 'shipping' || $active == 'shipping_method' ): ?>
								<div class="mark-arrow"></div>
							<?php endif; ?>
						</div>
					</div>
				<?php else: ?>
					<div class="shipping progress-block <?php if ( $active == 'shipping_method' )  ?>active">
						<div class="edit shipping-to clearfix">
							<h2>
								<?php echo $this->__( 'Entrega' ) ?>
							</h2>
							<h2 class="show-iphone">
								<?php echo $this->__( 'Entrega' ) ?>
							</h2>
							<div class="progress-block-details">
								<address>
									<?php
									// We need Shipping Address data in custom format
									$shippingAddressData = Mage::getSingleton( 'checkout/session' )->getQuote()->getShippingAddress()->getData();
									echo $shippingAddressData['firstname'] . ' ' . $shippingAddressData['middlename'] . ' ' . $shippingAddressData['lastname'] . '<br />';
									echo $shippingAddressData['street'] . '<br />' . $shippingAddressData['city'] . ', ' . $shippingAddressData['region'] . '&nbsp;&nbsp;';
									echo $shippingAddressData['postcode'] . '<br />' . Mage::getModel( 'directory/country' )->load( $shippingAddressData['country_id'] )->getName();
									?>
									<a class="close-fullscreen" href="#shipping" onclick="checkout.openSection('shipping');return false;">
										<?php echo $this->__( 'Alterar' ) ?>
									</a>
								</address>
							</div>
						</div>
						<?php if ( !$disable_estimated_shipping && Mage::helper( 'onestic_checkout' )->getEstimatedShipping() ) { ?>
							<div class="estimated-shipping-block">
								<p><?php echo $this->__( 'Valor do Frete:' ); ?> <strong><?php echo Mage::helper( 'core' )->currency( Mage::helper( 'onestic_checkout' )->getEstimatedShipping(), true, false );?></strong></p>
								<?php $shippingAddressData = Mage::getSingleton( 'checkout/session' )->getQuote()->getShippingAddress()->getData(); ?>
								<?php if ( isset( $shippingAddressData[ 'country_id' ] ) && $shippingAddressData[ 'country_id' ] ) { ?>
								<p><?php echo $this->__( 'Para' ); ?> <?php if ( isset( $shippingAddressData[ 'region' ] ) && $shippingAddressData[ 'region' ] ) echo $shippingAddressData[ 'region' ] . ', '; echo Mage::getModel( 'directory/country' )->load( $shippingAddressData[ 'country_id' ] )->getName() ?></p>
								<?php } ?>
							</div>
						<?php } ?>
						<?php if ( $active == 'shipping_method' ): ?><div class="mark-arrow"></div><?php endif; ?>
					</div>
				<?php endif; ?>
			<?php else: ?>
				<div class="shipping progress-block <?php if ( $active == 'shipping_method' )  ?>active">
					<h2>
						<?php echo $this->__( 'Entrega' ) ?>
					</h2>
					<h2 class="show-iphone">
						<?php echo $this->__( 'Entrega' ) ?>
					</h2>

					<div class="progress-block-details">
						<p>
							<?php echo $this->__('Preencha as informações de entrega e prossiga'); ?>
						</p>

						<?php if ( !$disable_estimated_shipping && Mage::helper( 'onestic_checkout' )->getEstimatedShipping() ) { ?>
							<div class="estimated-shipping-block">
								<p>
									<?php echo $this->__( 'Valor do Frete:' ); ?>
									<strong>
										<?php echo Mage::helper( 'core' )->currency( Mage::helper( 'onestic_checkout' )->getEstimatedShipping(), true, false );?>
									</strong>
								</p>
								<?php $shippingAddressData = Mage::getSingleton( 'checkout/session' )->getQuote()->getShippingAddress()->getData(); ?>
								<?php if ( isset( $shippingAddressData[ 'country_id' ] ) && $shippingAddressData[ 'country_id' ] ) { ?>
									<p>
										<?php echo $this->__( 'For' ); ?>
											<?php if ( isset( $shippingAddressData[ 'region' ] ) && $shippingAddressData[ 'region' ] )
												echo $shippingAddressData[ 'region' ] . ', ';
												echo Mage::getModel( 'directory/country' )->load( $shippingAddressData[ 'country_id' ] )->getName() ?>
									</p>
								<?php } ?>
							</div>
						<?php } ?>

						<?php if ( $active == 'shipping' ): ?>
							<div class="mark-arrow"></div>
						<?php endif; ?>
					</div>
				</div>
			<?php endif; ?>
		<?php endif; ?>
		<?php echo $this->getChildHtml( 'coupon' ) ?>
		<?php if ( $this->getCheckout()->getStepData( 'payment', 'is_show' ) ): ?>
			<?php if ( $this->getCheckout()->getStepData( 'payment', 'complete' ) ): ?>
				<div class="payment progress-block complete<?php if ( $active == 'payment' ): ?> active<?php endif; ?>">
					<div class="edit clearfix">
						<h2>
							<?php echo $this->__( 'Pagamento' ) ?>
						</h2>
						<h2 class="show-iphone">
							<a href="#payment" onclick="checkout.openSection('payment'); return false;">
								<?php echo $this->__( 'Pagamento' ) ?>
							</a>
						</h2>
						<a href="#payment" onclick="checkout.openSection('payment'); return false;">
							<?php echo $this->__( 'Alterar' ) ?>
						</a>
					</div>
					<div class="progress-block-details">
						<?php if ( in_array( Mage::getSingleton( 'checkout/session' )->getQuote()->getPayment()->getMethod(), array( 'ccsave', 'authorizenet', 'radweb_stripe' ) ) ) : ?>
							<ul class="cards">
								<?php
								switch ( Mage::getSingleton( 'checkout/session' )->getQuote()->getPayment()->getCcType() ) {
									case 'Visa':
									case 'VI': echo '<li class="VI">' . $this->__('Visa') . '</li>';
										break;
									case 'MasterCard':
									case 'MC': echo '<li class="MC">' . $this->__('MasterCard') . '</li>';
										break;
									case 'American Express':
									case 'AE': echo '<li class="AE">' . $this->__('American Express') . '</li>';
										break;
									case 'Discover':
									case 'DI': echo '<li class="DI">' . $this->__('Discover') . '</li>';
										break;
								}
								?>
							</ul>
							<address class="card-d">
								<?php
									echo 'xxx-' . Mage::getSingleton( 'checkout/session' )->getQuote()->getPayment()->getCcLast4();
								?>
							</address>
						<?php else : ?>
							<address>
								<?php echo $this->getPaymentHtml(); ?>
							</address>
						<?php endif; ?>
						<address>
							<?php echo $this->__('Billing Address:'); ?><br />
							<?php
							// We need Billing Address data in custom format
							$billingAddressData = Mage::getSingleton( 'checkout/session' )->getQuote()->getBillingAddress()->getData();
							echo $billingAddressData['firstname'] . ' ' . $billingAddressData['middlename'] . ' ' . $billingAddressData['lastname'] . '<br />';
							echo $billingAddressData['street'] . '<br />' . $billingAddressData['city'] . ', ' . $billingAddressData['region'] . '&nbsp;&nbsp;';
							echo $billingAddressData['postcode'] . '<br />' . Mage::getModel( 'directory/country' )->load( $billingAddressData['country_id'] )->getName();
							?>
						</address>
						<?php if ( $active == 'payment' ): ?><div class="mark-arrow"></div><?php endif; ?>
					</div>
				</div>
			<?php else: ?>
				<div class="payment progress-block<?php if ( $active == 'payment' ): ?> active<?php endif; ?>">
					<h2>
						<?php echo $this->__( 'Pagamento' ) ?>
					</h2>
					<h2 class="show-iphone">
						<?php echo $this->__( 'Pagamento' ) ?>
					</h2>

					<div class="progress-block-details">
						<ul class="cards" <?php if ( $active == 'payment' ): ?> style="display:none;" <?php endif; ?>>
							<li class="VI on"><?php echo $this->__('Visa'); ?></li>
							<li class="MC on"><?php echo $this->__('MasterCard'); ?></li>
							<li class="AE on"><?php echo $this->__('American Express'); ?></li>
							<li class="DI on"><?php echo $this->__('Discover'); ?></li>
						</ul>
						<?php if ( Mage::getModel( 'paypal/config' )->isMethodAvailable('paypal_express') || Mage::getModel( 'paypal/config' )->isMethodAvailable('paypal_billing_agreement') || Mage::getModel( 'paypal/config' )->isMethodAvailable('payflow_advanced') ) { ?>
							<span class="paypal"
								<?php if ( $active == 'payment' ): ?> style="display:none;" <?php endif; ?>>
							</span>
						<?php } ?>
						<?php if ( $active == 'payment' ): ?>
							<p>
								<?php echo $this->__(' Selecione uma forma de pagamento'); ?>
							</p>
							<div class="mark-arrow"></div>
						<?php endif; ?>
					</div>
				</div>
			<?php endif; ?>
		<?php endif; ?>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
<script type="text/javascript">
    jQuery(function() {
        jQuery(".close-fullscreen").click(function() {
            jQuery(".fullscreen-overlay").css("display", "none");
        });
    });
</script>
