<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<form id="co-shipping-method-form" action="<?php echo $this->getUrl( 'checkout/onepage/saveShippingMethod' ) ?>" method="post">
	<header class="same-step-header">
		<h2>
			<?php echo $this->__( 'Tipo de envio' ); ?>
		</h2>
		<small id="shipping-buttons-container">
			<small id="shipping-please-wait" class="please-wait" style="display: none;">
				<img src="<?php echo $this->getSkinUrl( 'onestic/checkout/images/opc-ajax-loader.gif' ) ?>" alt="Carregando..." title="Carregando..." class="v-middle">
			</small>
		</small>
	</header>
	<div class="row">
		<div id="checkout-shipping-method-load-wrapper" class="col-sm-6 col-md-8">
			<?php if ( $specialAnnouncement = Mage::getStoreConfig( 'checkout/shipping_method/special_announcement' ) ): ?>
				<div class="special-announcement message">
					<div>
						<h2><?php echo $this->__( 'Special Announcement' ) ?></h2>
						<p><?php echo $specialAnnouncement ?></p>
					</div>
				</div>
			<?php endif; ?>
			<div id="checkout-shipping-method-schedule-wrapper" class="clearfix">
				<div id="checkout-shipping-method-load">
					<?php echo $this->getChildHtml( 'available' ) ?>
				</div>
			</div>
			<script type="text/javascript">
				//<![CDATA[
				var shippingMethod = new ShippingMethod({ form: '#co-shipping-method-form' });
				//]]>
			</script>
		</div>
		<footer id="shipping-method-buttons-container" class="col-sm-6 col-md-4">
			<input type="submit" class="button btn btn-next btn-large loading-shipping" onclick="shippingMethod.save();return false;"
				value="<?php echo $this->__( 'Pr&oacute;ximo &rarr;' ) ?>"/>
			<span id="shipping-method-please-wait" class="please-wait button btn btn-next btn-large lds-dual-ring" style="display:none;">
				<?php echo $this->__( 'Carregando...' ) ?>
			</span>
		</footer>
	</div>
</form>