<?php
/**
 * Magaya
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@logistico.com so we can send you a copy immediately.
 *
 *
 * @category   Integration
 * @package    Magaya_Logistico
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<?php $img = $this->isComplianceEnabled() ? 'success-msg.png' : 'error-msg.png';?>
<h2 class="head-compliance"> WS-I Compliance Enabled </h2> <p><img src="<?php echo $this->getSkinUrl('images/'.$img)?>"/></p>
<?php if(!$this->isComplianceEnabled()):?>
<?php $apiUrl = $this->getUrl("adminhtml/system_config/edit/", array("section" => "api")); ?> 
<form>
    <button formaction="<?php echo $apiUrl?>"> <span><span><span><?php echo $this->__("Enable WS-I") ?></span></span></span></button>
</form>
<?php endif;?>
