<?php
/**
 * @package     universal
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<script src="https://bi.vidaclass.com.br/js/client/login_ext.js"></script>

<style>
	.login_loader {
	    position: fixed;
	    z-index: 9999999;
	    background: rgba(255, 255, 255, 0.5);
	    width: 100vw;
	    height: 100vh;
	    top: 0;
	    left: 0;
	    display: flex;
	    justify-content: center;
	    align-items: center;
	}

	.lds-facebook {
	  display: inline-block;
	  position: relative;
	  width: 64px;
	  height: 64px;
	}
	.lds-facebook div {
	  display: inline-block;
	  position: absolute;
	  left: 6px;
	  width: 13px;
	  background: #F2655D;
	  animation: lds-facebook 1.2s cubic-bezier(0, 0.5, 0.5, 1) infinite;
	}
	.lds-facebook div:nth-child(1) {
	  left: 6px;
	  animation-delay: -0.24s;
	}
	.lds-facebook div:nth-child(2) {
	  left: 26px;
	  animation-delay: -0.12s;
	}
	.lds-facebook div:nth-child(3) {
	  left: 45px;
	  animation-delay: 0;
	}
	@keyframes lds-facebook {
	  0% {
	    top: 6px;
	    height: 51px;
	  }
	  50%, 100% {
	    top: 19px;
	    height: 26px;
	  }
	}
</style>


<?php
	function loginWithoutPassword ($id)
	{

	    $customer = Mage::getModel('customer/customer');
	    $customer->setWebsiteId(Mage::app()->getWebsite()->getId());
	    $customer->load(trim($id));
	    Mage::getSingleton('customer/session')->loginById($customer->getId());

	    // $customer = Mage::getModel('customer/customer')->load($id);
	    $userSession = Mage::getSingleton('customer/session');
	    $userSession->setCustomerAsLoggedIn($customer);

	    Mage::dispatchEvent('customer_login', array('customer'=>$customer));
	    if (isset($_GET['redirect'])) {
	        //header('Location:'.$_GET['redirect']);
	        header('Location: https://'.$_SERVER['HTTP_HOST']);
	        exit;
	    }

	    //header('Location:'.Mage::getUrl('customer/account'));
	    header('Location: https://'.$_SERVER['HTTP_HOST']);
	    exit;

	}

	if (isset($_GET['uid'])) {
	    loginWithoutPassword($_GET['uid']);
	}

/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
// if(Mage::getSingleton('customer/session')->getOnCheckout()) {
// 	$urlRedirect = Mage::helper('checkout/url')->getCheckoutUrl();
// } else {
// 	$urlRedirect = $this->getCreateAccountUrl();
// }

$urlRedirect = $this->getCreateAccountUrl();
?>
<div class="login_loader" id="login_loader" style="display:none">
   <div class="vclass-login"><div></div><div></div><div></div></div>
</div>

<div class="account-login">
	<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="registered-users">
			<div class="auth-box">
				<h2 class="auth-title">Já tem cadastro?</h2>
			</div>
			<div class="content">
				<?php echo $this->getMessagesBlock()->toHtml() ?>
				<div class="email-container">
					<label for="email">E-mail</label>
		        	<div class="input-box">
		            	<input type="text" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" name="login[username]" id="email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" class="input-text validate-user required-entry" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
		        	</div>
		        	<span id="situacao"></span>
		        </div>
		        <div class="pass-container" id="pass-container">
					<label for="pass">Senha</label>
		        	<div class="input-box">
						<input type="password" name="login[password]" autocomplete="off" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
					</div>
					<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="esqueci_senha"><?php echo $this->__('Forgot Your Password?') ?></a>
				</div>
				<?php echo $this->getChildHtml('persistent.remember.me'); ?>
				<div class="clearfix">
					<button type="submit" class="btn ui-button auth-button btn-login"
						title="Login"
						name="send"
						id="send"
						/>
						<span>
							<span>
								Login
							</span>
						</span>
					</button>
						<hr />
						<?php echo $this->getChildHtml('inchoo_socialconnect_facebook_login_button'); ?>
					    <hr />
					<div class="register">
						<p>Voc&ecirc; &eacute; novo aqui?</p>
						<a href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"
							title="<?php echo $this->quoteEscape($this->__('Create an Account')) ?>"
							class="create-count-button">
							<?php echo $this->__('Cadastre-se agora!') ?>
						</a>
				</div>
				
				<div id="vc_login"></div>
				
				<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
			</div>
		</div>
		<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
			<input name="context" type="hidden" value="checkout" />
		<?php endif; ?>
	</form>
</div>
<script type="text/javascript">
//<![CDATA[
	if(!BASE_URL)
		var BASE_URL = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";

	var dataForm = new VarienForm('login-form', true);

	$('email').observe('keypress', bindLoginPost);
	$('email').observe('keypress', mascara);
	$('email').observe('blur', bindExists);
	$('pass').observe('keypress', bindLoginPost);

	function bindLoginPost(evt){
	 	if (evt.keyCode == Event.KEY_RETURN) {
	 		//evt.preventDefault();
	 	}
	}

	function mascara() {
		$('situacao').hide();
		value = this.value;
		if (!checkMail(value)){
			var er = new RegExp(/^[0-9\-\.\/]+/);
			if (er.test(value)) {
				value = value.replace(/\D/g,"");
				if (value.length >= 1 && value.length <= 11) {
					mascaraCPF(this);
				} else {
					mascaraCNPJ(this);
				}
			} else {
				value = this.value;
				value = value.replace(/[^a-zA-Z0-9_\-\.@]/gi,"");
				this.value = value;
			}
		}
	}

	function bindExists() {
		value = $('email').value;
		//$('send').writeAttribute('disabled',true);
		if (value.length > 3) {
		    if (checkMailDocument(value)) {
		   		var ok = false;
		    	var url = BASE_URL + 'onestic_checkout/customer/exists/';

		   		new Ajax.Request(url, {
		      		method: 'post',
		      		async: false,
		     		parameters: 'user=' + encodeURIComponent(value),
		       		onSuccess: function(transport) {
			       		var obj = response = eval('(' + transport.responseText + ')');
			        	if (obj.result === true) {
			          		$('pass-container').show();
			          		$('send').show();
			          		//$('send').writeAttribute('disabled',false);
			          		$('situacao').hide();
		           		} else {
							$('situacao').innerHTML = 'Email ou CPF/CNPJ não encontrado. Tente outro ou clique abaixo para se Cadastrar agora.';
							$('situacao').show();
							//$('send').hide();
		           		}
			        },
		          	onComplete: function() {
		          		//if ($('advice-validate-user-exist-email')) {
		          			//$('advice-validate-user-exist-email').remove();
		            	//}
		        	}
		      	});

		      	return ok;
		    } else {
		  		Validation.add('validate-user', 'Por favor, confira seus dados!', function(value) {
	    			return Validation.get('IsEmpty').test(value);
				});
		    }
		}
	}
//]]>
</script>
<script>
    'use strict';

    var regions = {
        AC: 485,
        AL: 486,
        AP: 487,
        AM: 488,
        BA: 489,
        CE: 490,
        DF: 511,
        ES: 491,
        GO: 492,
        MA: 493,
        MT: 494,
        MS: 495,
        MG: 496,
        PA: 497,
        PB: 498,
        PR: 499,
        PE: 500,
        PI: 501,
        RJ: 502,
        RN: 503,
        RS: 504,
        RO: 505,
        RR: 506,
        SC: 507,
        SP: 508,
        SE: 509,
        TO: 510
    };

    function fncSetForm (data) {
        console.log(data);
        data = JSON.parse(data);
        var loader = document.getElementById('login_loader');
        loader.style.display = 'flex';
        // verifica se usuario da VidaClass existe no Magento
        jQuery.ajax({
            type: 'PUT',
            url: '/api_rest/customer',
            data: JSON.stringify({ email: data.client.mail, checkuser: true }),
            dataType: 'json',
            error: function () {
                // pega nome e sobrenome separadamente
                var cropname = data.client.name.includes(' ') ? data.client.name.split(' ') : [data.client.name];
                var firstname = cropname[0];
                cropname.splice(0, 1);
                var lastname = cropname.length > 0 ? cropname.join(' ') : '';

                // envia request para criar o usuario do vidaclass no Magento
                jQuery.ajax({
                    type: 'PUT',
                    url: '/api_rest/customer',
                    dataType: 'json',
                    data: JSON.stringify({
                        email: data.client.mail,
                        firstname: firstname,
                        group_id: 1,
                        lastname: lastname,
                        taxvat: data.client.cpf,
                        tipopessoa: 'Física'
                    }),
                    error: function () {
                        alert('Erro ao buscar usuário, tente novamente.');
                        loader.style.display = 'none';
                    },
                    success: function (registeredData) {
                        console.log('registeredData', registeredData);
                        // se criou o usuario, agora tenta adicionar o endereço dele ao registro
                        jQuery.ajax({
                            type: 'POST',
                            url: '/api_rest/address',
                            dataType: 'json',
                            data: JSON.stringify({
                                customer_id: registeredData.entity_id,
                                firstname: firstname,
                                country_id: 'BR',
                                postcode: data.client.address.zip.replace('-', ''),
                                lastname: lastname,
                                city: data.client.address.city,
                                telephone: data.client.cellphone,
                                street: [
                                    data.client.address.public_place,
                                    data.client.address.complement,
                                    data.client.address.number,
                                    data.client.address.neighborhood
                                ],
                                region_id: regions[data.client.address.uf] !== undefined ? regions[data.client.address.uf]+'' : 0
                            }),
                            error: function () {
                                alert('Falha ao importar seu e endereço, tente novamente.');
                                loader.style.display = 'none';
                            },
                            success: function (addressData) {
                                console.log('addressData', addressData);
                                loader.style.display = 'none';
                                window.location.href = window.location.href + '?uid=' + registeredData.entity_id;
                            }
                        });
                    }
                }); // fim da request de criar usuario
            },
            success: function (customerData) {
                loader.style.display = 'none';
                window.location.href = window.location.href + '?uid=' + customerData.customer.entity_id;
            }
        });
    }

    function loginCustomerEmail (id) {
        jQuery.ajax({
            type: 'PUT',
            url: '/api_rest/login',
            data: JSON.stringify({ id: id }),
            error: function () {
                alert('Erro ao logar no sistema');
            },
            success: function (loginData) {
                console.log('loginData', loginData);
                // window.location.href = '/';
            }
        });
    }

    Core.btn({
        popup:{
            width: 420,
            height: 325
        },
        element: 'vc_login',
        callback: 'fncSetForm',
        type: 1,
        partner_key: '853c528a-9da4-11e9-93ec-224cb2ff40b1'
    });
</script>