<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php //<input type="hidden" id="billing:same_as_shipping" name="billing[same_as_shipping]" value="0" /> ?>
<input type="hidden" id="billing:address_id" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" />
<input type="hidden" id="billing:fullname" name="billing[fullname]" value="<?php echo Mage::helper( 'onestic_checkout' )->getFullname( $this->getAddress() ) ?>" />
<input type="hidden" id="billing:firstname" name="billing[firstname]" value="<?php echo $this->getAddress()->getFirstname(); ?>" />
<input type="hidden" id="billing:firstname" name="billing[lastname]" value="<?php echo $this->getAddress()->getLastname(); ?>" />
<input type="hidden" id="billing:postcode" name="billing[postcode]" value="<?php echo $this->htmlEscape( $this->getAddress()->getPostcode() ) ?>"/>
<input type="hidden" id="billing:street1" name="billing[street][]" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 1 ) ) ?>" />
<input type="hidden" id="billing:street2" name="billing[street][]" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 2 ) ) ?>" />
<input type="hidden" id="billing:street3" name="billing[street][]" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 3 ) ) ?>" />
<input type="hidden" id="billing:street4" name="billing[street][]" value="<?php echo $this->htmlEscape( $this->getAddress()->getStreet( 4 ) ) ?>" />
<input type="hidden" id="billing:city" name="billing[city]" value="<?php echo $this->htmlEscape( $this->getAddress()->getCity() ) ?>" />
<input type="hidden" id="billing:region_id" name="billing[region_id]" value="<?php echo $this->htmlEscape( $this->getAddress()->getRegionId() ); ?>" />
<input type="hidden" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape( $this->getAddress()->getRegion() ) ?>" />
<input type="hidden" id="billing:country_id" name="billing[country_id]" value="<?php if ( $this->getAddress()->getCountry() ) echo $this->getAddress()->getCountryId(); else echo Mage::helper('core')->getDefaultCountry(); ?>" />
<input type="hidden"  id="billing:telephone" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()); ?>" />