<!-- This Block is called to paginate reviews. -->
<?php if (Mage::helper('avisverifies/Data')->isActive()): ?> 
    <?php $p = ($this->getRequest()->getParam('p')) ? (int) $this->getRequest()->getParam('p') : 1; ?>
    <?php $sorting = ($this->getRequest()->getParam('sorting')) ? $this->getRequest()->getParam('sorting') : "horodate_DESC"; ?>
    <?php $o_av = Mage::getModel('avisverifies/reviews'); ?>
    <?php $ProductId = (int) $this->getRequest()->getParam('id_product'); ?> 
    <?php // to use same code. we are going to call first page from our code.  ?>
    <?php $ProductId = ($ProductId != 0) ? $ProductId : $this->getData('productId'); ?>
    <?php // to use same code. we are going to call first page from our code.  ?>
    <?php $o_av->idProduct = $ProductId; ?>
    <?php $o_av->page = $p; ?>
    <?php $reviews = $o_av->getProductReviews( $sorting ); ?>
    <?php $maxPages = $reviews->getLastPageNumber(); ?>
    <?php $count_reviews = 0; ?>

    <?php // Helpful / Helpless block
        $API = Mage::helper('avisverifies/API');
        $DATA = Mage::helper('avisverifies/Data');
        $API -> av_get_client_ip(); // Set the current ip addresse.
        $currentStoreId = Mage::app()->getStore()->getStoreId();
        $idWebsite = $DATA -> getModuleIdWebsite( $currentStoreId ); // Used only to calculate the sign.
        $secretKey = $DATA -> getModuleSecretKey( $idWebsite ); // Used only to calculate the sign.
        $ip = $API -> getCurrentIp(); // Used only to calculate the sign.
    ?>

    <!-- Reviews section -->
    <div id="ajax_comment_content" class="netreviews_reviews_section" max-pages="<?php echo $maxPages ?>">

        <!-- Reviews -->
        <?php foreach ($reviews as $k_review => $review): ?>
        
            <?php // Helpful / Helpless block
                $idProduitDemo = $review->getData('id_product_av');
                $sign = sha1( $idWebsite . $idProduitDemo . $ip . $secretKey );
//                echo "currentStoreId = $currentStoreId <br>
//                    idProduitDemo = $idProduitDemo <br>
//                    ip = $ip <br>
//                    idWebsite = $idWebsite <br>
//                    secretKey = $secretKey <br>
//                    sign = $sign <br>";
            ?>
        
            <div class="netreviews_review_part">
                <p class="netreviews_customer_name">
                    <?php echo $this->__( $o_av->AV_sgbd_decode( $review->getData('customer_name') ) ) ?>
                    <span>
                        <?php echo $this->__('the') ?>
                        <?php $date = date($this->__('d/m/Y'), ($review->getData('horodate'))) ?>
                        <?php echo $date ?>
                    </span>
                    <span style="font-size: 13px !important;">
                        <?php echo $this->__("following an order made on")."&nbsp;".date($this->__('d/m/Y'), strtotime($review->getData('order_horodate'))); ?>
                    </span>
                </p>
                <div class="netreviews_review_rate_and_stars">
                    <div class="netreviews_bg_stars netreviews_bg_stars_gold">
                        <span style="width:<?php echo ( $review->getData('rate') * 20 ) . "%" ?>;"></span>
                    </div>
                    <div class="netreviews_reviews_rate">
                        <?php echo $review->getData('rate') ?>/5
                    </div>
                </div>
                <p class="netreviews_customer_review">
                    <?php echo $this->htmlEscape($o_av->AV_sgbd_decode($review->getData('review'))) ?>
                </p>

                <!-- Website answers -->
                <?php $discussions = $o_av->discussion($review->getData('discussion'), $review); ?>
                <?php $k_discussion = 0; ?>
                <?php $i = 0; ?>
                <?php if ($discussions): ?>
                    <?php foreach ($discussions as $k_discussion => $discussion): ?>
                        <?php $styleNumber = ( $k_discussion > 0 && $i != 0 ) ? 'none' : 'block' ?>
                        <div class="netreviews_website_answer" style="display:<?php echo $styleNumber ?>" >
                            <p>
                                <span class="netreviews_answer_title">
                                    <?php echo $this->__('Comments of') ?>
                                    <b style="text-transform:capitalize; font-weight:normal">
                                        <?php echo $this->__($discussion['origine']) ?>
                                    </b>
                                    <small>
                                        <?php echo $this->__('on') ?>
                                        <?php echo date($this->__('d/m/Y'), $discussion['horodate']) ?>
                                    </small>
                                </span>
                                <br/>
                                <?php echo $this->htmlEscape($o_av->AV_sgbd_decode($discussion['commentaire'])) ?>
                            </p>
                        </div>
                        <?php $i++; ?>
                    <?php endforeach; ?>

                   <!-- Website answers button -->
                    <?php if ( $k_discussion > 1 && $i > 1 ) : ?>
                        <a class="netreviews_button_comment" href="javascript:void(0)" onclick="window.avisVerifies.showComments(this)" style="display:block;" >
                            <img class="netreviews_more_comment" src="<?php echo $this->getSkinUrl('images/avisverifies/comment.png') ?>">
                            <span><?php echo $this->__('Show conversation') ?></span>
                        </a>
                        <a class="netreviews_button_comment" href="javascript:void(0)" onclick="window.avisVerifies.hideComments(this)" style="display:none;" >
                            <img class="netreviews_more_comment" src="<?php echo $this->getSkinUrl('images/avisverifies/comment.png') ?>">
                            <span><?php echo $this->__('Hide conversation') ?></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                
                <?php if ( Mage::getStoreConfig('avisverifies/extra/add_review_helpful_button') == 1 ): ?>
                    <p class="netreviews_helpful_block">
                        <?php echo $this->__('Was this review helpful?') ?>
                        <a href="javascript:avHelpfulClick('<?php echo $idProduitDemo; ?>','1','<?php echo $sign; ?>')"
                           class="netreviewsVote"
                           data-review-id="<?php echo $idProduitDemo; ?>"
                           id="<?php echo $idProduitDemo; ?>_1">
                            <?php echo $this->__('Yes') ?>
                            <span>
                                <?php echo ( $review->getData('helpful') ) ? $review->getData('helpful') : 0 ?>
                            </span>
                        </a>
                        <a href="javascript:avHelpfulClick('<?php echo $idProduitDemo; ?>','0','<?php echo $sign; ?>')"
                           class="netreviewsVote"
                           data-review-id="<?php echo $idProduitDemo; ?>"
                           id="<?php echo $idProduitDemo; ?>_0">
                            <?php echo $this->__('No') ?>
                            <span>
                                <?php echo ( $review->getData('helpless') ) ? $review->getData('helpless') : 0 ?>
                            </span>
                        </a>
                    </p>
                    <p class="netreviews_helpfulmsg" id="<?php echo $idProduitDemo; ?>_msg"></p>
                <?php endif; ?>
            </div>
            <?php $count_reviews++; ?>
        <?php endforeach; ?>
        
        <!-- Without reviews -->
        <?php if ( $count_reviews == 0 ): ?>
            <div class="netreviews_review_part">
                <p class="netreviews_no_reviews_block">
                    <?php echo $this->__('There are no reviews.') ?>
                </p>
            </div>
        <?php endif; ?>

    </div>
    <!-- end reviews section -->

</div>
<!-- end netreviews tab -->

<?php endif; ?>