<?php
/**
 * Magaya
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@logistico.com so we can send you a copy immediately.
 *
 *
 * @category   Integration
 * @package    Magaya_Logistico
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="logistico-notice">
    
    <a href="http://app.logistico.com" target="_blank"><img src="//app.logistico.com/assets/images/logos/login_logo.png" style="border:none;"></a>
    <p>Copyright &copy; <script>var today=new Date(); document.write(today.getFullYear());</script> <a href="http://app.logistico.com" target="_blank">www.app.logistico.com</a> </p>
    <p>Got questions? Feel like you need help? Mail us at <a href="mailto:logistico@magaya.com">info@logistico.com</a></p>
    <p>Don't have an account? <a href="https://app.logistico.com/#/signup" target="_window">Click here to signup!</a></p>

    
</div>