<?php
$customer = '';
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
  $customer = Mage::getSingleton('customer/session')->getCustomer();
}
?>

<?php
$product_Sku = Mage::registry('current_product')->getSku();
$currentCatIds = Mage::registry('current_product')->getCategoryIds();
$categoryCollection = Mage::getResourceModel('catalog/category_collection')
                     ->addAttributeToSelect('name')
                     ->addAttributeToSelect('url')
                     ->addAttributeToFilter('entity_id', $currentCatIds)
                     ->addIsActiveFilter();

$categoriesNames = '';
$categoriesIds = '';
$sizeOf = sizeof($categoryCollection);
$index = 1;
foreach($categoryCollection as $k => $categorie){
  $categoriesNames = $categoriesNames . $categorie->getName();
  $categoriesIds = $categoriesIds . $categorie->getId();
  if ($index < $sizeOf){
    $categoriesNames = $categoriesNames . ',';
    $categoriesIds = $categoriesIds . ',';
  }
  $index++;
}
?>

<script type="text/javascript">
    dataLayer = [{
        pageName: "product",
        productId: "<?php echo Mage::registry('current_product')->getSku(); ?>",
        productName: "<?php echo Mage::registry('current_product')->getName(); ?>",
        productPriceDefault: "<?php echo number_format(Mage::registry('current_product')->getPrice(), 2, '.', ''); ?>",
        productPrice: "<?php echo number_format(Mage::registry('current_product')->getFinalPrice(), 2, '.', ''); ?>",
        productStock: "<?php echo Mage::getModel('cataloginventory/stock_item')->loadByProduct(Mage::registry('current_product'))->getIsInStock(); ?>",
        productCategoryId: "<?php echo $categoriesIds; ?>",
        productDesc: "",
        productPhoto: "<?php echo Mage::registry('current_product')->getImageUrl(); ?>",
        productDepartment: "",
        productCategory: "<?php echo $categoriesNames; ?>",
        productSubCategory: "",
        productBrand: "<?php echo Mage::registry('current_product')->getAttributeText('manufacturer'); ?>",
        clientEmail: "<?php if($customer): ?><?php echo $customer->getEmail(); ?><?php endif; ?>",
        event: "isProduct"
    }];
</script>