<?php
$customer = '';
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
	$customer = Mage::getSingleton('customer/session')->getCustomer();
}
?>
<?php
$_current_category = Mage::registry('current_category');
?>



<?php
$_productCollection=$this->getLoadedProductCollection();

$productsCart = '';
$productsCartIds = '';
$indexItens = 1;
$sizeOfItens = $_productCollection->count();

if ($_productCollection->count()){
    foreach ($_productCollection as $_product){
    	$product_Sku = $_product->getSku();
?>
	



	<?php
	$product_Sku = $_product->getSku();
	    $productsCartIds = $productsCartIds . $product_Sku;
	?>

    <?php

    $currentCatIds = $_product->getCategoryIds();
    $categoryCollection = Mage::getResourceModel('catalog/category_collection')
                         ->addAttributeToSelect('name')
                         ->addAttributeToSelect('url')
                         ->addAttributeToFilter('entity_id', $currentCatIds)
                         ->addIsActiveFilter();

    $categoriesNames = '';
    $sizeOfCategories = sizeof($categoryCollection);
    $indexCategories = 1;
    foreach($categoryCollection as $categorie){
      $categoriesNames = $categoriesNames . $categorie->getName();
      if ($indexCategories < $sizeOfCategories){
        $categoriesNames = $categoriesNames . ',';
      }
      $indexCategories++;
    }

    $productsCart = $productsCart . '{';
    $productsCart = $productsCart . 'productId: "' . $_product->getSku() . '",';
    $productsCart = $productsCart . 'productName: "' . $_product->getName() . '",';
    $productsCart = $productsCart . 'productPrice: "' . number_format($_product->getFinalPrice(), 2, '.', '') . '",';
    $productsCart = $productsCart . 'productDepartment: "",';
    $productsCart = $productsCart . 'productCategory: "' .  $categoriesNames . '",';
    $productsCart = $productsCart . 'productSubCategory: "",';
    $productsCart = $productsCart . 'productBrand: "' . $_product->getAttributeText('manufacturer') . '"';
    $productsCart = $productsCart . '}'
    ?>

    <?php
    if ($indexItens < $sizeOfItens){
        $productsCart = $productsCart . ',';
        $productsCartIds = $productsCartIds . ',';
    }
    ?>
    <?php $indexItens++; ?>






<?php
	}
}
?>



<script type="text/javascript">
	var productsCart = [];
    
    productsCart.push(<?php echo $productsCart; ?>);

	dataLayer = [{
		pageName: "category",
    categoryId: "<?php echo $_current_category->getId(); ?>",
		categoryName: "<?php echo $_current_category->getName(); ?>",
		clientEmail: "<?php if($customer): ?><?php echo $customer->getEmail(); ?><?php endif; ?>",
		productsShelf: productsCart,
		event: "isCategory"
	}];
</script>