<?php 
$helper = Mage::helper("onestic_skyhub");
?>
<div class="content-header">
    <table class="grid-header">
        <tr>
            <td><h3>Sincronização de Entregas de Pedidos - Skyhub</h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <ul id="andamento">
    	<li id="init" style="display: none;"><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>Sincronizando pedidos, por favor aguarde... </li>
    	<li id="success" style="display: none; background-color:#DDF;">
    		<img src="<?php echo $this->getSkinUrl('images/fam_bullet_success.gif');?>" class="v-middle" style="margin-right:5px"/>
    		Sucessos: <span id="sucesso"></span>
    	</li>
    	<li id="errors" style="display: none;">
    		<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/>
    		Erros: <span id="erros"></span>
    	</li>
    	<li id="finish" style="display: none"><img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>Processo Finalizado</li>
    </ul>
    <div id="loader"><img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/> Processando sincronização...</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var totalService = 0;
    var updatedTotal = 0;
    var current_page = 0;
    var totalSucesso = 0;
    var totalErro = 0;
    function startUpdate() {
    	totalService = 0;
        updatedTotal = 0;
        current_page = 0;
        totalSucesso = 0;
        totalErro = 0;
		$('init').show();
		$('success').hide();
		$('errors').hide();
		$('finish').hide();
		updateProgress();	
    }
    function updateProgress() {
    	new Ajax.Request( '<?php echo $this->getUrl("*/adminhtml_progress/shipment"); ?>', {
			method: 'GET',
			evalScripts: true,
			onLoading: function(transport) {
				$('loader').show();
				$('finish').hide();
			},
			onComplete: function(transport) {
				$('loader').hide();
				$('finish').show();
			},
			onSuccess: function(transport) {
				if (200 == transport.status) {
					response = transport.responseText.evalJSON();
					if(response.count != 0 && response.count != totalService) {
						totalSucesso = totalSucesso + parseInt(response.success);
						totalErro = totalErro + parseInt(response.errors);
						if (totalSucesso > 0) {
							$('success').show();
							$('sucesso').innerHTML = totalSucesso;
						}

						if (totalErro > 0) {
							$('errors').show();
							$('erros').innerHTML = totalErro;
						}
						updatedTotal = parseInt(response.count);
						totalService = parseInt(response.total);
						percent = (updatedTotal / totalService) * 100;
						$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/> Sincronizado ' + Math.round(percent) + '% de ' + totalService + ' pedidos. Processando sincronização...'; 
						updateProgress();
					} else if(response.success == 0 && response.errors == 0 && response.count == 0 && response.total != 0) {
						$('finish').show();
					} else {
						$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/> Ocorreu um erro, verifique o log do sistema.';
					}
				}
			},
			onFailure: function() {
				$('loader').innerHTML = '<img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/> Ocorreu um erro! <a href="javascript: updateProgress();">Repetir processo</a>.';
			}
		});
    }
    document.observe('dom:loaded', function() {
        startUpdate();
    });
//]]>
</script>
<style type="text/css" >
	td.label {
		text-align: right;
		padding-right: 10px;
	}
    ul#andamento { list-style-type:none; padding:0; margin:0; }
    ul#andamento li, #loader { margin-left:0; border:1px solid #ccc; margin:2px; padding:2px 2px 2px 2px; font:normal 12px sans-serif; }
    ul#andamento li img, #loader img { margin-right:5px; }
</style>