<!-- callouts/farmaceutico.phtml -->
<ul class="social"> 	
    <li>
        <a href="http://www.farmadelivery.com.br/fale-com-o-farmaceutico" title="Fale com o Farmacêutico">
            <img width="148" height="48" src="/media/upload/image/fale_farmaceutico.png" alt="" />
        </a>
    </li> 	
    <li>
        <a href="http://blog.farmadelivery.com.br/" target="_blank" title="Blog">
            <img width="156" height="48" src="/media/upload/image/leia-blog.png" alt="" />
        </a>
    </li> 	
    <li>
        <ul class="sociais-redes"> 			
            <li class="twitter">
                <a href="http://twitter.com/farmadelivery" target="_blank" title="Twitter">Twitter</a>
            </li> 			
            <li class="orkut">
                <a href="http://www.orkut.com.br/Main#Profile?uid=12977564243306460270" title="Orkut" target="_blank">Orkut</a>
            </li>
            <!--
            <li class="rss">
                <a href="http://www.farmadelivery.com.br/rss" title="RSS" target="_blank">RSS</a>
            </li>
            -->
            <li class="facebook">
                <a href="https://www.facebook.com/RECFARMADELIVERY" title="Facebook" target="_blank">Facebook</a>
            </li> 			
            <li class="formspring">
                <a href="http://www.formspring.me/Farmadelivery" title="FormSpring" target="_blank">Formspring</a>
            </li> 		
        </ul>
    </li> 
</ul>

<!--
<div class="blk-gm-marcas">
    <ul class="more-banners"> 	
        <li class="adiabc">
            <a target="_blank" href="http://www.adiabc.com.br/">adiabc</a>
        </li>  	
        <li class="agvs">
            <a title="Agência Nacional de Vigilância Sanitária" target="_blank" href="http://www.anvisa.gov.br/">ANVS</a>
        </li> 
          	
        <li class="notafiscal">
            <a title="Nota Fiscal Paulista" target="_blank" href="https://www.nfp.fazenda.sp.gov.br/">notafiscal</a>
        </li> 	
        
    </ul>
</div>
-->